### ISSUE TITLE
Add an upgrade tool (aka inginious-install is too interactive :smile: )

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#100]
inginious-container-update is unable to pull new images added to the config file, and updates images removed from the config file.

We could provide an inginious-update script that reads the current configuration and pulls the containers specified in it. It should look for the config file exactly like inginious-{webapp,lti}.

That way, we could call `inginious-update` and have the _new_ containers pulled.

Optionally, add an option to remove old containers (removed from the config).
Optionally, make it interactive like inginious-install (opt-in).
Optionally, call it inginious-upgrade.
Optionally, make it parse and validate the config file, and fail if it is not valid.

The tool would replace the docker pull part of http://inginious.readthedocs.io/en/latest/install_doc/updating.html

This is inspired from OwnCloud which has `occ upgrade` that checks the config and applies any update necessary for the current version to work. This would also be the place to change the database schema (if there was one :wink: )
See https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#upgrade-wizard

It would be useful for people not using inginious-install, and for every user that wants to update its config without reconfiguring everything via inginious-install.

Sounds like a good idea ?

**Comment by GuillaumeDerval** [comment]
Closed in favor of #111. We should have some way to update in the online tool. The documentation also documents a way to update all containers at once.
