### ISSUE TITLE
Promote Python as the main way to do "run" script

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#101]
Currently, it's bash, and it's not cool.
- modify the doc to move bash to a specific page/set of pages about alternative APIs
- document the python API
- improve it

**Comment by layus** [comment]
Yep, or make it a custom executable with the usual shebang, so we can also use C with tcc ;-)

**Comment by GuillaumeDerval** [comment]
That's already the case :-)

The issue is mainly to modify the doc to remove bash, to document the python API, and to improve it.
I'll update the issue to be more clear :-)

**Comment by 31416r** [comment]
I agree to improve and promote the python API as first choice to run the tasks (the new feedback_s_ methods constitute a first step in that direction), but I think we should keep bash in the doc, at least as an example that INGInious can execute anything.

Also, any improvement in the python API must be translated into new or improved bash commands.

**Comment by GuillaumeDerval** [comment]
I completely agree, issue modified accordingly.

**Comment by anthonygego** [comment]
To be improved over time, but done.
