### ISSUE TITLE
Add a better API for feedback

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#102]
Producing RST from bash (and even Python) is a bit cumbersome. Having a true API for that would be a plus (in python probably #101 )

**Comment by GuillaumeDerval** [comment]
Linked to #94

**Comment by layus** [comment]
I think html is the right language in this context (feedback generated by the run script).
For example, when you want to pass the output from some commands to the user, simply
```
output=$(some command)
feedback ... "<pre>$output</pre>"
```

While RST is great for the description of the problems, feedbacks hardly require all these features.
Feedback is usually some `<p>`'s, some `<pre>`'s for raw output. Why not switch to HTML by default ?

Just ask Olivier, the output of the containers during the 1252 exam was all scrambled. Gcc warnings and errors where parsed as RST.

**Comment by GuillaumeDerval** [comment]
I have some problem with letting users using HTML, as it can break INGInious itself (a wrongly closed tag can scramble the webapp...).

Having an API in Rst/Markdown/... that checks and escape things correctly is a better approach from my point of view.

If you really really want to use HTML, there is a tag in RST that allows to do it:

`.. raw:: html`

**Comment by GuillaumeDerval** [comment]
Another possibility is to use HTML and use HTMLTidy. Not really secure.

**Comment by layus** [comment]
Or use [html purifier](https://pypi.python.org/pypi/html-purifier/). Inginious can cope with just one more module :wink:.
See also http://htmlpurifier.org/comparison

**Comment by GuillaumeDerval** [comment]
it's in php :-(

**Comment by layus** [comment]
Sorry, my mistake. Still, you have https://pypi.python.org/pypi/html-purifier/, which I thought was the same project but is actually based on python's own html.parser. And also https://pypi.python.org/pypi/bleach

**Comment by anthonygego** [comment]
Done in https://github.com/UCL-INGI/INGInious-containers/commit/52f523b386470f31d6070cac4088bd5f01693749
