### ISSUE TITLE
Subtasks

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#104]
Having a nice API/integration of subtasks would be very useful.

Currently, this is completely managed by run scripts. Most of them uses CUnit, JUnit, or SomethingUnit and creates a grading from the results of the tests.
Having an interface in the administration that would display the result of each test, the output, the grading associated with it, ... would be awesome.

This _must_ be a opt-in feature: we still need to be able to not use it if we don't want to.

Ideally, the API given should be independent from CUnit/... but easy to use with them (not sure that's possible... maybe we will have to develop an "agnostic" API with some additional integrations with other tools)

Needs discussion.

**Comment by GuillaumeDerval** [comment]
Should be integrated with #103

**Comment by layus** [comment]
[TAP](http://testanything.org/) is the closest thing to a standard test harness protocol. May be worth investigating.
