### ISSUE TITLE
Deep Thought Simulation (test task) is weird

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#106]
When submitting a valid answer, I get Deep Thought Simulation

> **Your answer passed the tests! Your score is 100.0%**
> Feedback file has been modified by user !

This is rather unexpected. Both should not be possible at the same time :-).

**Comment by anthonygego** [comment]
Fixed in https://github.com/UCL-INGI/INGInious-containers/commit/0b2ecb98b4c3cc6a7d2f6a03832ea4bcaa4fd673
