### ISSUE TITLE
run_student containers do not share CPU time / memory constraints with the grading container

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#121]
It is currently possible to ask a grading container with 1 mo of RAM and then start multiple student containers with 8 Go. 

Their limits should be shared.

**Comment by GuillaumeDerval** [comment]
wrongly closed

**Comment by 31416r** [comment]
Do we have some automatic tests for this kind of stuff ?

**Comment by GuillaumeDerval** [comment]
It's a "new feature" that I haven't started to work on yet, so... not yet ;-)

**Comment by 31416r** [comment]
It may be a good idea to start with the tests :-D

**Comment by anthonygego** [comment]
I think it is better to know and control explicitly what resources are available for what. People already seem to have some difficulties to debug their resources-limitation issues. We should inform them more clearly on what is limited at each step.

Sharing limits would be complex to implement and will not ensure that a weird run-file won't eat all the student allocated memory.

**Comment by GuillaumeDerval** [comment]
Ok.
