### ISSUE TITLE
Use bytes instead of base64 encoded str

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#128]
For now we use base64-encoded `str` objects (in the py3 sense) to send file to the container. However, as we now use msgpack for everything, it would be cool to use only `bytes` and to avoid base64-encoding everything.

The idea is to drop the ugly fix in 4a2b1afc9a6007f59ceefd69f50f835c2a89f786, to stop storing all the submission in GridFS but only the bytes object, and to use msgpack in the container instead of JSON to store everything.

**Comment by anthonygego** [comment]
@GuillaumeDerval Is there base64 remaining ?

**Comment by GuillaumeDerval** [comment]
https://github.com/UCL-INGI/INGInious/search?p=1&q=base64&type=&utf8=✓
