### ISSUE TITLE
Update documentation for new backend/install process/update

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#129]

**Comment by greigdp** [comment]
I spent some time getting INGInious to work using the new backend system. Maybe this will help anyone trying to get it working too.

The main changes I found from the current docs were

- Within configuration.yaml, `backend` should be set to point to a dedicated backend using the form `tcp://192.168.x.x:2001`
- The configuration.yaml section `containers` can be removed
- The docker build images need to be built from source from the latest (seems the topic branch was merged to master) git code - https://github.com/UCL-INGI/INGInious-containers
- If the core image isn't found, it can be built and tagged manually as `ingi/inginious-c-base` (from grading/base in that repo)

I started the backend first, using the command `inginious-backend -v tcp://192.168.x.x:2000 tcp://192.168.x.x:2001`
Then I started the docker agent using the command `inginious-agent-docker --debug-ports 60000-61000 --debug-host 192.168.x.x -v tcp://192.168.x.x:2000`
Finally I started the frontend using `inginious-webapp`.

Monitoring the backend's stdout will show that each component correctly connects - `New client connected...` messages show the webapp is connected, and `Agent ... said hello` shows the docker agent has connected. The webapp should then work. 

When specifying the environment in a task, the string which should be used is the `org.inginious.grading.name` label defined in the docker image. For example, `python3`.
