### ISSUE TITLE
Missing "div" statement in the Oz highlight system

### ISSUE THREAD

**Issue by ffelten** [UCL-INGI/INGInious#138]
Hello,

I just noticed that some students on edX were confused by the fact that the "div" statement is not highlighted when writing their answer.

Regards,

Florian

**Comment by GuillaumeDerval** [comment]
We use codemirror as highlighting system; this bug has to be fixed in https://github.com/codemirror/CodeMirror/blob/master/mode/oz/oz.js.

If you feel motivated, please make a PR there :-)
