### ISSUE TITLE
Improving debugging / logging

### ISSUE THREAD

**Issue by dirkcgrunwald** [UCL-INGI/INGInious#140]
I have a request to have more extensive debugging & logging. I will probably add more myself in order to solve the problem described below, but if there's a standard effort to add more, I would like to follow the conventions you're adopting.

We're debating using INGInious for autograding. I have a current setup on a CENTOS 7 VM, more or less following the directions. Our goal is to eventually use it with LTI for Moodle but it appears we also need to have webapp access in order to have faculty author classes & tests.

I'm running as a user 'centos', and that user can run docker containers and the standard containers are installed.

```
[centos@inginious INGInious]$ docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
docker.io/ingi/inginious-c-java7        latest              1555393b8114        2 weeks ago         651.2 MB
docker.io/ingi/inginious-c-java8scala   latest              606a7f32fcbd        2 weeks ago         1.147 GB
docker.io/ingi/inginious-c-default      latest              1daa35008282        2 weeks ago         373.1 MB
docker.io/ingi/inginious-c-mono         latest              8fb8fe52eb0c        2 weeks ago         668.1 MB
docker.io/ingi/inginious-c-cpp          latest              c5aff918c677        2 weeks ago         767 MB
docker.io/centos                        latest              970633036444        3 weeks ago         196.7 MB
```

However, when I log in as an 'admin' user (super) and use the test course as provided in the install, I am unable to actually run the graders for the sample test program through the webapp, I get the following message (red box):

```

An internal error occured. Please retry later. If the error persists, send an email to the course administrator.
There was an internal error while running the tests
```

Is there an easier debugging method built in?

**Comment by GuillaumeDerval** [comment]
There should be some output from the inginious-webapp / inginious-lti command.

If you are running webapp/LTI behind lighttpd, you have to configure lighttpd to store the stdout of the fastcgi command (inginious-webapp/lti) somewhere.

The simplest way to do that is to modify the bash script that is started by lighttpd. If you followed the tutorial (http://inginious.readthedocs.io/en/latest/install_doc/installation.html), it should be named `/var/www/INGInious/start-lti.sh`. (adapt for webapp accordingly)

You can modify its content to something like:
```bash
#! /bin/bash
cd /var/www/INGInious
inginious-lti &>> lti.log
```
You that will log everything to `/var/www/INGInious/lti.log`.

Moreover, we have fixed some problems in the branch `new_backend`, but we are waiting for some dependencies to update (we have waiting PRs). If you want, I can make a short tutorial for you to update to the future release of INGInious that hopefully logs way more information.

**Comment by dirkcgrunwald** [comment]
I'd be happy to test the new backend. 

I'm just running ./inginious-webapp on the command line and there wasn't any log output related to the backend. E.g. in the period where the error arose, I'm getting

```
2016-08-22 21:25:33,218 - inginious.webapp.requests - INFO - 128.138.64.207:59876 - "HTTP/1.1 GET js/codemirror/mode/\
python/python.js" - 304 Not Modified
2016-08-22 21:25:40,203 - agent - INFO - Received request for jobid bb5e7648-9f07-463d-84b6-6e2d7a9dc467
2016-08-22 21:25:40,209 - inginious.webapp.requests - INFO - 128.138.64.207:59876 - "HTTP/1.1 POST /course/test/hello\
world" - 200 OK
2016-08-22 21:25:41,262 - inginious.webapp.requests - INFO - 128.138.64.207:59876 - "HTTP/1.1 POST /course/test/hello\
world" - 200 OK
```

**Comment by 31416r** [comment]
While we are waiting for our PRs to be merged, it would be great to have a doc on how to use the new backend. I can confirm that it logs a lot more information !

@GuillaumeDerval, if you have the time, please put that doc somewhere, even temporarily.

**Comment by dirkcgrunwald** [comment]
I added some more logging but it leaves be more confused than before. The basic problem is that the container ingi/inginious-c-default runs but dies with the error

```
[centos@inginious agent]$ docker logs insane_raman
Traceback (most recent call last):
  File "/usr/bin/INGInious", line 116, in <module>
    setDirectoryRights("/task")
  File "/usr/bin/INGInious", line 33, in setDirectoryRights
    os.chmod(path, 0o777)
```

where /task has been mapped to /tmp/inginious/0/task

```
[centos@inginious agent]$ ls -lR /tmp/inginious_agent/0/task
/tmp/inginious_agent/0/task:
total 12
-rwxr-xr-x. 1 centos centos 702 Aug 22 16:37 run
drwxrwxrwx. 2 centos centos   6 Aug 23 21:28 student
-rw-rw-r--. 1 centos centos 593 Aug 22 20:57 task.yaml
-rw-r--r--. 1 centos centos  35 Aug 22 16:37 template.py

/tmp/inginious_agent/0/task/student:
total 0
```
If I run..

```
docker run -it --rm -v /tmp/inginious_agent/0/task:/task ingi/inginious-c-default  ls -l /task
ls: cannot open directory /task: Permission denied
```

it appears that the /tmp/igninious_agent/0/task directory is protected somehow -- is this something to do with SElinux?

**Comment by dirkcgrunwald** [comment]
And, indeed it is an issue with selinux. If I do "sudo setenforce 0", thing work.

This article: http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

mentions a 'Z' argument that can be added to volume mounts to cause the context to be changed to the context of the executing program. I didn't see anything similar in the Python docker library.

**Comment by GuillaumeDerval** [comment]
INGInious is not yet compatible with Selinux, as it is very complex to make it work properly with the combo lighttpd/inginious-webapp/docker/container app with sockets.

For now, selinux should be set as permissive or told to ignore INGInious specifically.

**Comment by GuillaumeDerval** [comment]
I'm currently abroad (till the end of the week), I will spend some time to make a tutorial for the new backend when I'll be back in Belgium.
