### ISSUE TITLE
inginious/frontend/lti/pages/download.py uses 'lti_download' w/o configuration option

### ISSUE THREAD

**Issue by dirkcgrunwald** [UCL-INGI/INGInious#144]
In inginious/frontend/lti/pages/, the directory 'lti_download/tmp' is created in the current directory. This fails if the current directory does not have an 'lti_download' directory and/or if you can't write to it.

I think the 'lti_download' directory should be specified in the YAML configuration file with a sensible default (e.g. /tmp/lti_download). I haven't figured out how to get to the config information from this location, but will do so and submit a PR unless it's a quick fix for someone else.

**Comment by anthonygego** [comment]
Download page in 2c14ce89cf68d6bd554d99f2a1cf596439c95a4a
