### ISSUE TITLE
iproute not available in the container ?

### ISSUE THREAD

**Issue by oliviertilmans** [UCL-INGI/INGInious#156]
Neither /(s)bin/ip nor  /(s)bin/ifconfig is available in the containers.
Is that expected ? Having to do ioctl()'s etc just to get an ip address in the run file sounds a bit overkill ...

**Comment by GuillaumeDerval** [comment]
That should definitely be added in ingi/inginious-c-base. PR are always welcome, I you do not find the time I'll do it as soon as I have time to build some containers  :-)
