### ISSUE TITLE
Sort tasks in the download page.

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#158]
For the record, as we already discussed this elsewhere, but could not find an issue here.

**Comment by ancailliau** [comment]
And sort teams properly. Gr 1., then Gr 2., not Gr 10.

**Comment by layus** [comment]
Aka version sort: https://www.gnu.org/software/coreutils/manual/html_node/Details-about-version-sort.html

**Comment by GuillaumeDerval** [comment]
@ancailliau As said (later) on the slack, there is no need for very strange sorts as you name yourself the group; just prefix a 0.

**Comment by layus** [comment]
WONTFIX LOL ?
