### ISSUE TITLE
Uploading a file using Return key in a task redirect user to JSON text

### ISSUE THREAD

**Issue by ancailliau** [UCL-INGI/INGInious#163]
Uploading a file in task files and validating the upload with the Return key redirect to a page containing 

```
{"message": "Your browser returned an invalid form ('@action')", "status": "error"}
```

And the image is not uploaded. It is mandatory to click on the button "Save change" (which is, btw, mislabelled).

Steps to reproduce (when editing a task):
1. Click on "Task Files"
2. Click on "Upload a file"
3. Select a file
4. Click in the "File path:" field
5. Hit Return/Enter key.

**Comment by anthonygego** [comment]
Fixed in f2fb9ed9728b9b20eb8fd12fec6aef718132b261
