### ISSUE TITLE
Downloading task submissions in another format

### ISSUE THREAD

**Issue by shlomihod** [UCL-INGI/INGInious#167]
The files for the student code will be separate than the submission metadata and feedback (as JSON).
In other words, separating `submission.test` into 2 parts: the `input` field as a separate file and all the rest as `submission.test`.

**Comment by GuillaumeDerval** [comment]
I suppose the current format is good enough for most purposes. As there are no other users that ask for this functionnality, I'll close the issue. If you believe it's really super-nice-to-have, feel free to repoen another issue with more details.
