### ISSUE TITLE
task.yaml wrong format gives no error log

### ISSUE THREAD

**Issue by ogoletti** [UCL-INGI/INGInious#168]
When one tries to create a task with a wrongly formatted `task.yaml`. The task is just not visible in the course interface and no error message is logged as far as I can see. 

I was trying to make tasks either accessible or not without bothering with deadlines. So I used `true`/`false` values in the `accessible` field as suggested in the doc (http://inginious.readthedocs.io/en/latest/teacher_doc/task_file.html?highlight=task.yaml). A mistake in my script made me push `'false'` values instead of `false`.

To reproduce, juste replace the accessible field of a `task.yaml` with `'false'`.

**Comment by GuillaumeDerval** [comment]
When you go in the administration of the webapp, the error should appear below the list of tasks. Is that not the case?

**Comment by ogoletti** [comment]
yes indeed : Unknown format for false
