### ISSUE TITLE
Dragging code file to a text box

### ISSUE THREAD

**Issue by shlomihod** [UCL-INGI/INGInious#174]
The user can drag a code file to a code text box, and the content of the file will be copied to the text box.

**Comment by Drumor** [comment]
Just tested it with Brave (Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) unknown (64-bit)) and Firefox (106.0.3 (64-bit)) and it effectively works without extra code needed. I close this for now but feel free to reopen if needed.
