### ISSUE TITLE
Tutorial: error in example run file

### ISSUE THREAD

**Issue by AugustH** [UCL-INGI/INGInious#175]
In  http://inginious.readthedocs.io/en/latest/teacher_doc/task_tuto.html (= doc/teacher_doc/task_tuto.rst) it says:

    parsetemplate --output studentcode.py template.py

    # Verify the output of the code...
    output=$(run_student python studentcode.py)

but this fails -- which is bad as a new users first experience. Comparing to `INGInious-demo-tasks:tutorial/04_run_student` it should be (with an additional `student/`):

    parsetemplate --output student/studentcode.py template.py
    output=$(run_student python student/studentcode.py)

Additional a link from the tutorial to the INGInious-demo-tasks repository would be helpful for new users.

**Comment by anthonygego** [comment]
Thank you for reporting that mistake!
