### ISSUE TITLE
Can't install INGInious

### ISSUE THREAD

**Issue by bogem** [UCL-INGI/INGInious#177]
In documentation it says: 
```
You may want to enable the LDAP plugin or use (F)CGI instead of the web.py default webserver. In this case, you have to install more packages: simply add [cgi], [ldap] or [cgi,ldap] to the above command, depending on your needs:
```
I need these two plugins so I execute `sudo pip3 install --upgrade git+https://github.com/UCL-INGI/INGInious.git[cgi,ldap]` but become this message:
```
Collecting git+https://github.com/UCL-INGI/INGInious.git[cgi,ldap]
  Cloning https://github.com/UCL-INGI/INGInious.git[cgi,ldap] to /tmp/pip-97qj4783-build
fatal: unable to access 'https://github.com/UCL-INGI/INGInious.git[cgi,ldap]/': The requested URL returned error: 400
Command "git clone -q https://github.com/UCL-INGI/INGInious.git[cgi,ldap] /tmp/pip-97qj4783-build" failed with error code 128 in None
```

**Comment by anthonygego** [comment]
Indeed, it seems the only way to make this work with VCS urls is to explicit set the package name such that the command to type becomes : 

    pip3 install --upgrade git+https://github.com/UCL-INGI/INGInious.git#egg=INGInious[cgi,ldap]

As this is suggested in the [pip documentation](https://pip.pypa.io/en/latest/reference/pip_install/#examples) I'll fix this in the docs.

**Comment by bogem** [comment]
Thank you!
