### ISSUE TITLE
INGInious + Ubuntu + Apache

### ISSUE THREAD

**Issue by bogem** [UCL-INGI/INGInious#178]
I will really appreciate it, when someone will write the documentation, how to make INGInious work on Ubuntu with Apache. I'm trying to make it, but the wsgi is always a problem :(

**Comment by bogem** [comment]
I always become 500 error from apache. Logs (`error.log`):
```
[Sat Feb 25 18:40:15.183315 2017] [so:warn] [pid 14385:tid 140128475404160] AH01574: module wsgi_module is already loaded, skipping
[Sat Feb 25 18:40:15.187644 2017] [wsgi:warn] [pid 14386:tid 140128475404160] mod_wsgi: Compiled for Python/3.5.1+.
[Sat Feb 25 18:40:15.187662 2017] [wsgi:warn] [pid 14386:tid 140128475404160] mod_wsgi: Runtime using Python/3.5.2.
[Sat Feb 25 18:40:15.188730 2017] [mpm_event:notice] [pid 14386:tid 140128475404160] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/3.5.2 configured -- resuming normal operations
[Sat Feb 25 18:40:15.188781 2017] [core:notice] [pid 14386:tid 140128475404160] AH00094: Command line: '/usr/sbin/apache2'
[Sat Feb 25 18:40:22.183690 2017] [wsgi:error] [pid 14390:tid 140128385595136] [client %CLIENT IP%] mod_wsgi (pid=14390): Target WSGI script '/usr/local/bin/inginious-webapp' cannot be loaded as Python module.
[Sat Feb 25 18:40:22.183781 2017] [wsgi:error] [pid 14390:tid 140128385595136] [client %CLIENT IP%] mod_wsgi (pid=14390): Exception occurred processing WSGI script '/usr/local/bin/inginious-webapp'.
[Sat Feb 25 18:40:22.184184 2017] [wsgi:error] [pid 14390:tid 140128385595136] [client %CLIENT IP%] Traceback (most recent call last):
[Sat Feb 25 18:40:22.184232 2017] [wsgi:error] [pid 14390:tid 140128385595136] [client %CLIENT IP%]   File "/usr/local/bin/inginious-webapp", line 13, in <module>
[Sat Feb 25 18:40:22.184241 2017] [wsgi:error] [pid 14390:tid 140128385595136] [client %CLIENT IP%]     import web
[Sat Feb 25 18:40:22.184266 2017] [wsgi:error] [pid 14390:tid 140128385595136] [client %CLIENT IP%] ImportError: No module named 'web'
[Sat Feb 25 18:40:22.646382 2017] [wsgi:error] [pid 14389:tid 140128352024320] [client %CLIENT IP%] mod_wsgi (pid=14389): Target WSGI script '/usr/local/bin/inginious-webapp' cannot be loaded as Python module., referer: %CLIENT IP%
[Sat Feb 25 18:40:22.646473 2017] [wsgi:error] [pid 14389:tid 140128352024320] [client %CLIENT IP%] mod_wsgi (pid=14389): Exception occurred processing WSGI script '/usr/local/bin/inginious-webapp'., referer: %CLIENT IP%
[Sat Feb 25 18:40:22.646804 2017] [wsgi:error] [pid 14389:tid 140128352024320] [client %CLIENT IP%] Traceback (most recent call last):, referer: %CLIENT IP%
[Sat Feb 25 18:40:22.646851 2017] [wsgi:error] [pid 14389:tid 140128352024320] [client %CLIENT IP%]   File "/usr/local/bin/inginious-webapp", line 13, in <module>, referer: %CLIENT IP%
[Sat Feb 25 18:40:22.646861 2017] [wsgi:error] [pid 14389:tid 140128352024320] [client %CLIENT IP%]     import web, referer: %CLIENT IP%
[Sat Feb 25 18:40:22.646886 2017] [wsgi:error] [pid 14389:tid 140128352024320] [client %CLIENT IP%] ImportError: No module named 'web', referer: %CLIENT IP%
```

`/etc/apache2/apache2.conf`
```
...
# Need to INGINIOUS (TODO: move to another file)
SetEnv INGINIOUS_WEBAPP_CONFIG /var/www/INGInious/configuration.yaml
SetEnv INGINIOUS_WEBAPP_HOST 0.0.0.0
SetEnv INGINIOUS_WEBAPP_PORT 80
LoadModule wsgi_module /usr/local/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so

WSGIScriptAlias / "/usr/local/bin/inginious-webapp"
WSGIScriptReloading On

Alias /static/common /usr/local/lib/python3.5/site-packages/inginious/frontend/common/static/
Alias /static/webapp /usr/local/lib/python3.5/site-packages/inginious/frontend/webapp/static/
Alias /static/lti /usr/local/lib/python3.5/site-packages/inginious/frontend/lti/static/

<Directory "/usr/local/bin">
    <Files "inginious-webapp">
        Require all 
    </Files>
</Directory>

<DirectoryMatch "/usr/local/lib/python3.5/site-packages/inginious/frontend/(.+)/static/">
    Require all granted
</DirectoryMatch>
```

**Comment by dirkcgrunwald** [comment]
I recall having a similar issue. Looking at my apache config, I see the following.  I'm not certain if I added this to the docs or not. Let's see if it fixes your problem and then update the docs.

```
WSGIPythonPath /var/www/INGInious/

# This is a desired solution, but does not work.
# See https://gist.github.com/GrahamDumpleton/b380652b768e81a7f60c
# for alternate solutions
#
#SetEnv INGInious_CONFIG_WEBAPP /var/www/INGInious/configuration.yaml
#SetEnv INGInious_PATH_WEBAPP /var/www/INGInious/

Listen 80
<VirtualHost *:80>
	ServerName inginious.cs.colorado.edu
	Redirect temp / https://inginious.cs.colorado.edu/
</VirtualHost>

Listen 443
<VirtualHost inginious.cs.colorado.edu:443>

	ServerName inginious.cs.colorado.edu
	ServerAdmin help@cs.colorado.edu

	WSGIDaemonProcess inginious-webapp-wsgi user=apache group=apache threads=5 display-name=%{GROUP}
	WSGIProcessGroup inginious-webapp-wsgi
        WSGIScriptAlias / /var/www/INGInious/inginious-webapp-wsgi.py
	WSGIScriptReloading On
```

**Comment by anthonygego** [comment]
@bogem  I've just tested the setup on an Ubuntu Server 16.04 and did not experienced such an issue.

The only things I've changed from the CentOS docs is renaming ``httpd-devel`` to ``apache2-dev``, putting env variables into ``/etc/apache2/envvars`` instead, allowing user ``www-data`` instead of ``apache`` on Docker and MongoDB and changing paths in apache config file as you did (except I've ``dist-packages`` instead of ``site-packages``).

Are you actually able to run the app with the integrated webserver ?

**Comment by bogem** [comment]
@anthonygego thank you, but that didn't help. I become the same problem :(
Trying the solution of @dirkcgrunwald

**Comment by bogem** [comment]
@dirkcgrunwald what is `inginious-webapp-wsgi`? Can you please send me the content of this file? I will be very thankful

**Comment by dirkcgrunwald** [comment]
I put the full config at http://pastebin.com/hDLXkkq9

See http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIProcessGroup.html

i have two separate process groups for the LTI and APP interface. I don't know if that's needed, I hadn't set up WSGI before and this seemed to be a good idea from the docs.

**Comment by bogem** [comment]
Thank you! But I mean, what is `/var/www/INGInious/inginious-webapp-wsgi.py` file for? Did you write it by yourself?

**Comment by bogem** [comment]
> Are you actually able to run the app with the integrated webserver ?

And yes, I can run the integrated webserver

**Comment by anthonygego** [comment]
OK, this would be strange, but can you try specifying your ``site-packages`` folder, which should contain the web.py ``web`` module, into the [``WSGIPythonPath``](http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIPythonPath.html) directive and tell us if that helps ?

The file ``inginious-webapp-wsgi.py`` was written by @dirkcgrunwald and was merged into the global ``inginious-webapp`` script after some tiny refactor to allow this, so you should actually use ``inginious-webbapp`` in your Apache config with the current master branch.

**Comment by bogem** [comment]
> OK, this would be strange, but can you try specifying your site-packages folder, which should contain the web.py web module, into the WSGIPythonPath directive and tell us if that helps ?

I become the same error :(

**Comment by bogem** [comment]
Solved! More in previous comment. 
Thanks to @anthonygego for your assistance!
Thanks to @dirkcgrunwald for config! It was really useful
