### ISSUE TITLE
Navigation between tasks

### ISSUE THREAD

**Issue by ogoletti** [UCL-INGI/INGInious#182]
In the webapp, there should be a way to navigate easily between related tasks. Such as a previous/next or go-to button. 

Maybe via a grouping/tagging of the tasks (all tasks within a sequence are linked by default in a specific order).

**Comment by ogoletti** [comment]
To describe a bit more what could be user freindly. 
I like on the interactivepython.org/runestone platform the simple previous/next button on the bottom left/right corners of the screen, they stay there while scrolling a specific page and a tooltip gives you the title of the previous/next page.
I like on openclassrooms.com and on studio.code.org the idea of a progress bar on top of the task in which each button is a task in the section/course and has a tooltip.

**Comment by anthonygego** [comment]
Previous/next buttons done.
