### ISSUE TITLE
Better documentation on inginious agent / kubernetes

### ISSUE THREAD

**Issue by dirkcgrunwald** [UCL-INGI/INGInious#189]
We've moved much of our infrastructure to run on Google Compute Engine using containers (e.g. we do this for Moodle, another grading thing called Jobe/CodeRunner), and rather than devote multiple fixed servers to either one inginious+docker host (as I do now) or inginous_agent's to run docker on other fixed-sized hosts, it would be better to have an inginious_agent that farms out jobs to Kubernetes so that we can enable autoscaling and thus save money. 

We would pattern that code after the e.g. the way that JupyterHub spawns IPython notebooks (i.e. https://github.com/jupyterhub/kubespawner ). Kubernetes has a REST interface to create 'pods' and attach storage.

But to do this, it would be useful to have more documentation about the inginious_agent method and warnings / gotchas or information about pragmatic issues that arise from someone that has used it.

Is that method in used? The documentation at http://inginious.readthedocs.io/en/latest/commands.html is a little thin.

**Comment by GuillaumeDerval** [comment]
In fact, we are currently investigating various ways to allow to scale INGInious correctly and transparently in a cloud env.

Kubernetes is a promising method, but we haven't tested it yet; do you have an idea of the time taken to spawn a new container over Kubernetes?

**Comment by dirkcgrunwald** [comment]
Benchmarks indicate that median startup time used to be about 2 seconds (vs. 0.5 for docker swarm) -- see https://blog.docker.com/2016/03/swarmweek-docker-swarm-exceeds-kubernetes-scale/ -- but that's been reduced to ~1.75-1.5 seconds ( http://blog.kubernetes.io/2016/07/kubernetes-updates-to-performance-and-scalability-in-1.3.html ). These are fairly large clusters (1000's of nodes), and I haven't seen any benchmarks for small clusters.

I find that inginious takes about 5-6 seconds to run a very simple "hello world" test in my docker-only setup but this is an old AMD processor. I suspect that the file system mapping etc adds to the delay beyond basic pod creation.

**Comment by GuillaumeDerval** [comment]
Thanks for the links :-)

> I find that inginious takes about 5-6 seconds to run a very simple "hello world" test in my docker-only setup but this is an old AMD processor. I suspect that the file system mapping etc adds to the delay beyond basic pod creation.
The delay is typically the time taken by Docker to create the filesystem for the container. You can obtain < 1s only with SSDs, from what we have seen.

**Comment by GuillaumeDerval** [comment]
We are moving away from the possibility to use Kubernetes to start containers in the agent (for various technical reasons such as student containers). What could be possible is to start an Agent inside Kubernetes and allow it to access the docker instance of the host, but I don't think it would play nice with Kubernetes.

Another possibility would be to rewrite a specific agent for kubernetes, which is not easy and in our goals for now.

I'm then closing this issue, for now at least.
