### ISSUE TITLE
Randomly generated inputs

### ISSUE THREAD

**Issue by anthonygego** [UCL-INGI/INGInious#195]
We should provide a way to generate some random values that are used for checking the submission. This could be some regex fields in the task files that are then included in the task context using patterns, for instance, and injected into the submission input data for execution.

We also need to be careful concerning the different APIs, because the generated values have to be kept after reading the task context until submission.

**Comment by GuillaumeDerval** [comment]
@anthonygego can we close this now that #300 is merged?

**Comment by anthonygego** [comment]
I suppose.
