### ISSUE TITLE
Invalid task id, although it's valid

### ISSUE THREAD

**Issue by bogem** [UCL-INGI/INGInious#198]
If you create task with invalid id in webapp, ingi shows warning:
![2017-04-08 20 31 50](https://cloud.githubusercontent.com/assets/13235519/24831505/cbc15c9e-1c9a-11e7-9796-3597d4e32fb2.png)
But if you create task id with dots like "8.04.17", ingi fails with error:
![2017-04-08 20 33 26](https://cloud.githubusercontent.com/assets/13235519/24831510/041dc9ba-1c9b-11e7-80c8-4b38a04d838c.png)

**Comment by GuillaumeDerval** [comment]
Fixed, thanks for the report. The error is in fact in the JS; we don't allow `.` in course/taskid (because `..` has a special meaning in most filesystems :-))
