### ISSUE TITLE
Library import error

### ISSUE THREAD

**Issue by yesh-r** [UCL-INGI/INGInious#209]
Where does one install the required libraries for code evaluations of python/R?
```stderr
/task/run: line 4: which: command not found
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import pandas as pd
ImportError: No module named 'pandas'

**Comment by anthonygego** [comment]
Additional software can be provided by modifying existing environment Dockerfile or defining new one.
Typically, you can create a new environment inheriting from the "R" environment by defining, in a new folder, a ``Dockerfile`` file which would look like this :

    # DOCKER-VERSION 1.1.0

    FROM    ingi/inginious-c-r
    LABEL   org.inginious.grading.name="MyCustomR"

    # Install pandas
    RUN     yum -y install python-pandas && \
            yum clean all && \
            # Install Python3 version as well
            pip3.5 install pandas

Then build the container by typing :
   
    docker build -t some_tag .

Then restart INGInious. The environment ``MyCustomR`` should be available with your dependencies :-)

**Comment by yesh-r** [comment]
Where do I edit/create this docker file?

**Comment by anthonygego** [comment]
As long as the Docker image is pulled on the machine hosting INGInious (or the Docker agent), you can create or edit this file anywhere on any computer. The procedure I gave you is in case you do this on the host machine. The ``Dockerfile`` can be located in any empty directory which will act like some sort of a *project folder*.

You can find additional information here : http://inginious.readthedocs.io/en/latest/teacher_doc/create_container.html or in the tutorial tasks.

You can also have a look at Docker documentation : https://docs.docker.com/get-started/part2/
Or at this tutorial : https://rominirani.com/docker-tutorial-series-writing-a-dockerfile-ce5746617cd
to have more info about how to build images using Dockerfiles.
