### ISSUE TITLE
reStructuredText values in JSON strings drive me crazy :-)

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#21]
It is nearly impossible to enter reStructuredText in json strings, and there are cases where the user enters a simple string that gets involuntarily evaluated as restructured text.

My point is that in tasj.json, strings should only be plain strings, or html chunks.
In task.rst, everything should be reStructuredText (obviously).

So
1) parsing of strings in task.json should be disabled by default, and
2) Either task.rst or "{context,name,header}IsHTML" should be documented to avoid asking the user to enter reStructuredText values in JSON strings.

What do you think of that ?

**Comment by GuillaumeDerval** [comment]
I always found that the .rst are more a substitute for the .json files, and are really complicated to maintain (docutils is probably the worst lib used in INGInious). For me, we should clearly separate configuration from task description, using two different languages, such as JSON+RST as originally intended. 

This separation also allows to use directly HTML, and, possibly in the future, other markup languages.

I also think that the usage of JSON is a bad design choice, but we were not aware at that time of the problems with the strings that have to be on a single line.

The true solution (for me, please tell me what you think about it) would be to simply drop JSON and RST (as a method to parse configuration) and to use something that is
* more user friendly: possibility to have multiline string, comments, ...
* "clean" (== not like RST);
* lightweight (== like JSON and not like RST).

From the other markup languages I known, XML is too heavy. YAML is probably a good candidate.
Please tell me if you have another ideas.

(I'm clearly going to deprecate parsing with JSON/RST at some point, unless someone (== @31416r) use his super-sysadmin-veto-power)

**Comment by GuillaumeDerval** [comment]
Another solution would be to modify a bit the JSON we accept. I already did this in PR #36 to allow comments in JSON. Giving the possibility to do multiline strings in JSON would solve the problem, without modifying the current files. However, it's still a bit unclean.

**Comment by 31416r** [comment]
I agree with the YAML idea (and don't mention XML again please, it hurts my eyes).

JSON+RST was more of a quick hack to bite on something without loosing too much time with the task description issue. As I remember, we where always aware that it was not a wonderful choice, nor a definitive one.

While I think that YAML would be much cleaner, and would allow direct inclusion of HTML (is that a good idea ?), I also think that it would be a pity if we drop the support for JSON+RST or pure RST for task description. It provides backward compatibility and offers a choice to the teacher. All the more as the code is already there and don't pose any maintenance issue (for now). From this point of view, it would be nice to allow multi-line strings in our JSON format. As you said, it has already been altered for INGInious and I think it is not that crappy, as it is not uncommon for other projects to use modified JSON formats for internal purposes.
