### ISSUE TITLE
Unable to register for course

### ISSUE THREAD

**Issue by sizhky** [UCL-INGI/INGInious#212]
Hi,

I'm unable to sign up for any course and it gives the following error ```Registration failed. Please check that you properly typed the password.``` Even if there is no password. What am I missing here?
![image](https://user-images.githubusercontent.com/3656100/26880197-4458bf18-4bb1-11e7-8826-c1ede60f845b.png)

**Comment by codesagar** [comment]
I have noticed this issue when using dual authentication methods. ie Local and dbAuth (MongoDB). Should mark it as a bug.

However you should be able to run fine when using single authentication method.

**Comment by anthonygego** [comment]
Can you replace the line :

https://github.com/UCL-INGI/INGInious/blob/d193aef77c68c4b5ff3e1ef510aacc136bfd069f/inginious/frontend/webapp/pages/index.py#L40

by 

    raise 

and restart INGInious ? The stacktrace that will be printed will give more information about how to solve this issue. Logging is missing in this portion of code btw...

**Comment by GuillaumeDerval** [comment]
The bug has probably been fixed since you reported the bug. If it's not the case, feel free to reopen a new issue.
