### ISSUE TITLE
User unable to access the portal. Activation workflow needs some work.

### ISSUE THREAD

**Issue by codesagar** [UCL-INGI/INGInious#213]
If authentication plugin is set to db-auth (MongoDB) and **if by any cause the initial activation mail is not delivered or lost by user, there is no way he can access the system.** 

Even after setting new password through "lost password" utility the user is not granted access to the portal. I explored MongoDB and found an _additional key "activate" with some hash value for users whose activation is pending._ Hence it can be safely assumed that it is happening because the user didn't activate his account from the link provided in the first mail (which supposedly is lost).

This might be a bug or unplanned scenario; in which case **I suggest a change in workflow where the activation mail is resent in case the user has not been activated.**

**Comment by GuillaumeDerval** [comment]
@anthonygego what's the status of this?

**Comment by anthonygego** [comment]
Currently the password recovery is allowed if the account has not been activated yet, so this could be closed. But I think this not the best solution as it can be used to send mails to a non existing address...

**Comment by GuillaumeDerval** [comment]
I do not really see how we could improve this... Many websites does it like this, and there are no way an attacker could send a customized email with this method.

**Comment by codesagar** [comment]
A big problem - When a user registers for first time, we send out activation mail - which ideally should be activated, but there are a couple of exceptions:
1. The mail doesn't go through. (mail delivery problem - in spite of the email address being correct)
2. The mail being lost in spam folder or deleted
3. User forgot to activate email
In all of the above cases, if the user tries to log in to the system, he is greeted with invalid id/password message and thereby unable to use the system. There has to be better recovery options. Either we resend the activation email or at least give relevant feedback i.e. "You haven't activated your mail"
