### ISSUE TITLE
local installation in mac - failed parsing 

### ISSUE THREAD

**Issue by ohadperry** [UCL-INGI/INGInious#217]
Have a question regrading a local installation in mac 10.12. new to INGInious. I am getting "<b>Parsing failed</b>" when trying to parse rst. I think it's related to the installation on html to pdf https://wkhtmltopdf.org/ . getting 
```
{AttributeError}'_CustomHTMLTranslator' object has no attribute 'sollbruchstelle'
```
in 
`~/.virtualenvs/INGInious/lib/python3.5/site-packages/docutils-0.14rc1-py3.5.egg!/docutils/core.py -> publish`

**Comment by ohadperry** [comment]
don't know if it's related. but also getting 
```
Cannot embed stylesheet 'html4css1.css':
```

**Comment by GuillaumeDerval** [comment]
Can you provide a full stack trace or a screenshot of the error?

**Comment by ohadperry** [comment]
here is the error for the user
<img width="882" alt="screen shot 2017-07-03 at 12 05 10" src="https://user-images.githubusercontent.com/2236337/27785950-e7022624-5fe7-11e7-9e5b-36ff0b10a0f1.png">

here is the stacktrace from pycharm IDE
<img width="395" alt="screen shot 2017-07-03 at 12 08 38" src="https://user-images.githubusercontent.com/2236337/27786076-6640583e-5fe8-11e7-8a58-43a42f15d22c.png">

I've installed https://wkhtmltopdf.org/ and i think maybe my installation is the source of this issue
<img width="734" alt="installing html to pds" src="https://user-images.githubusercontent.com/2236337/27786251-19f81c2c-5fe9-11e7-9881-6962f896ae02.png">
