### ISSUE TITLE
Hyperlinks in task descriptions

### ISSUE THREAD

**Issue by sizhky** [UCL-INGI/INGInious#219]
Hi,

I've tried markdown and raw HTML tagging but I'm unable to create a hyperlink in the text. What does ingenious use as markdown text and how do I create anchors and tables?

**Comment by anthonygego** [comment]
Hi,

INGInious uses reStructredText. You'll find useful information on the docutils reStructuredText reference manual, available [here](http://docutils.sourceforge.net/docs/user/rst/quickref.html) about how to make links and tables. If something you want cannot be done using RST, you can still use the ``..raw: html`` directive.
