### ISSUE TITLE
Duplicate a course

### ISSUE THREAD

**Issue by ogoletti** [UCL-INGI/INGInious#221]
Following the proposition in  #179, it should be possible to just duplicate an entire course. 
The use case is to handle for a teacher to give the same course to two different groups at the same time with different deadlines, maybe different tasks, ... 
This feature request is linked to a mail with @anthonygego @Drumor "Plugin INGInious" dated 02/12/2016.

**Comment by anthonygego** [comment]
Won't fix...this would allow course administrators to bypass the superadmin to create courses.

**Comment by ogoletti** [comment]
Concerning this "won't fix" and the one in #222 is this not possible now through the marketplace ? Maybe I am mistaken I have to say I don't really know in the end what has been decided there.
