### ISSUE TITLE
Personalize a course template

### ISSUE THREAD

**Issue by ogoletti** [UCL-INGI/INGInious#222]
Following on the idea of #221, if it's possible to duplicate a course (for example to use it as a template), it could be nice to be able to select sections (if #221 ) or tasks based on tags (as suggested in #220  or in #182). 
The use case here : a user (not a task editor) wants to duplicate provided course material and select some tasks (for example because for a topic/section he can choose between two proposed paths, or because they want to be able to select/remove proposed extra exercices for their class).

**Comment by anthonygego** [comment]
Same answer as #221.
