### ISSUE TITLE
Trying to edit the form data using js in task.html

### ISSUE THREAD

**Issue by ohadperry** [UCL-INGI/INGInious#228]
I'm struggling with this for too long. 
created an input 
```
<input type="file" class="upload-file-btn-js">
```
in `inginious/frontend/webapp/templates/task.html`

the user uploads a text file with the solution and I'm reading it's content and supposed to "type" it in the textarea as if the user typed it herself. 

the code for "typing" is 
```
    var numberOfPres = $('.upload-file-btn-js').closest('div').find('pre').length;
    var fileDisplayArea = $('.upload-file-btn-js').closest('div').find('pre')[numberOfPres-1];
    $(fileDisplayArea).text('bla bla')
```
It changes the code but, The js code to validate the input is raising 

due to 

```
if($(this).val() == "" && $(this).attr('data-optional') != "True")
                answered_to_all = false;
```
in `task.js`

I can edit the textarea
```
<textarea name="program" class="code-editor form-control single" data-x-language="C" data-x-lines="8" data-optional="False" style="display: none;"></textarea>
```

using 

```
$('.upload-file-btn-js').closest('div').find('textarea.code-editor').val('bla bla')
```

but I don't see any difference.
The text doesn't get updated in the DOM

any suggestions ??

**Comment by anthonygego** [comment]
You should look at CodeMirror documentation, which is the editor used in INGInious. This may be useful : https://github.com/codemirror/CodeMirror/issues/555

**Comment by ohadperry** [comment]
Solved indeed using `CodeMirror`. Thanks @anthonygego 

My mistake was addressing the DOM elements as plain elements instead of finding the relevant CodeMirror object and working with it like 

```
relevantCodeMirrorObject.getDoc().setValue(output)
```

how to find the relevantCodeMirrorObject? that is dependant on your code.
