### ISSUE TITLE
Tutorial Tasks not working on webapp installation

### ISSUE THREAD

**Issue by Arnei** [UCL-INGI/INGInious#229]
Hello INGinious users,

we have installed the inginious webapp frontend on Ubuntu 16.04 and have encountered a rather peculiar problem. When we tried to solve the task "01_getting_started" from the tutorial section, the output string is always empty. We have no idea what could cause this, as the task is equivalent to the task from the online demo.

**Comment by anthonygego** [comment]
Can you provide more information about what is not working ?

**Comment by Arnei** [comment]
In order to "solve the first tutorial task, you're supposed to write a hello world program in python. If you do that on the demo server, you either get a "Success! You did it!" message or a "Wrong! Your output was XXX" message, where XXX is the output of your hello world program. On our local webapp server, when we enter a hello world program we always get the failure message, and the feedback message will not display whatever output our hello world program had.

**Comment by anthonygego** [comment]
What the failure message do you get ? The problem seems not to come from the tasks files but from the INGInious setup.

**Comment by Arnei** [comment]
It looks like this:
http://i.imgur.com/qkwFJEu.png
Which is the feedback message defined in the run file, but without the output. We already tried reinstalling INGinious, but it did not help because we are not sure where the problem is, and therefore did not do anything differently.

**Comment by GuillaumeDerval** [comment]
On the right of the task page, you should have a "debug information" button; can you send us a copy or a screenshot of the content of the popup that appears when you click on it?

**Comment by Arnei** [comment]
Here you go:
http://i.imgur.com/Fy8mOoo.png

**Comment by GuillaumeDerval** [comment]
Mea culpa; we spotted the bug, it is caused by a recent modification in the containers.

Please wait some time to allow them to rebuild on Docker Hub, then update them with the command `inginious-container-update`.

**Comment by Arnei** [comment]
Wonderful, it works now. Thank you very much!
