### ISSUE TITLE
inginious-install fails with ImportError

### ISSUE THREAD

**Issue by waegaein** [UCL-INGI/INGInious#230]
Hi, I just started experimenting INGInious and am facing an issue with installing frontends.
My VM is in CentOS 7, installed dependencies and INGInious package according to the docs.
I get the following error msg when I use "inginious-install" command with any arguments.

`Traceback (most recent call last):
  File "/usr/bin/inginious-install", line 11, in <module>
    import inginious.frontend.lti.installer
ImportError: No module named 'inginious.frontend.lti'`

It seems that the 'lti' directory is missing under the 'frontend' directory for the latest version.
Is it under development better to use some older version?
Any guidance would be appreciated. Thanks in advance!  :)

**Comment by anthonygego** [comment]
Indeed, you need to use the `v0.4` branch. The links should have been updated in the docs.
