### ISSUE TITLE
Grading Environment only mcq

### ISSUE THREAD

**Issue by Arnei** [UCL-INGI/INGInious#233]
Hey INGInious users,

so I had not been using my local inginious-webapp installation for a couple of days, and when I tried to use it again today, I found that all my tasks hat switched their grading environment to "mcq". Other installed grading environments such as default and cpp are not available. I tried to reconfigure the installation with "inginious-install webapp", but that did not do any good. I would rather avoid a complete reinstall, since this sounds like just a silly little bug. Any idea what might have gone wrong?

**Comment by anthonygego** [comment]
The environments are detected using a Docker image label. Check that the container images are still listed in Docker using ``docker images``. Also try to pull the container images again and reload the webapp.

**Comment by Arnei** [comment]
It seems that the container images are not listed

> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

Pulling the container images again did not change that.

**Comment by GuillaumeDerval** [comment]
Check your Docker installation; this should never happen and is not dependent of INGInious.

When you run
`docker pull centos`

You should at least obtain
```
$ docker images                                                                                                                                                                                                                                                                                         
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
centos                     latest              36540f359ca3        2 weeks ago         193MB
```

**Comment by Arnei** [comment]
Yes, the problem was with my docker installation. After a clean install everything is working fine again
