### ISSUE TITLE
How to run Tasks Tests 

### ISSUE THREAD

**Issue by ohadperry** [UCL-INGI/INGInious#235]
Hi, 
trying to run unit tests on tasks
http://inginious.readthedocs.io/en/v0.4/teacher_doc/testing.html#defining-a-new-unit-test

I don't understand 
1. how to run the tests? what's the command 
2. "problem id, which you defined in your task file" - I have no problem id's in my task.yaml..
3. what is this `definetest ` tool ? where do I use it exactly ?

This is a classic Getting started issue. 

I have no problem contributing to the docs to make this clearer once I understand it myself.

**Comment by ohadperry** [comment]
@anthonygego

**Comment by anthonygego** [comment]
1. You need to use [inginious-test-task](http://inginious.readthedocs.io/en/v0.4/commands_doc/inginious-test-task.html#inginious-test-task) tool. You'll have to specify the config file and course and task ids in arguments. It will therefore launch the task using inputs in ``*.test`` files located in your task folder and check if all computed fields match the test file ones.
1. You probably do not want to write the ``.test`` file by yourself. All submissions done can be downloaded as a test file which consists in input and output. However, all the subproblems you define inside a task have an associated problem id. Using the frontend, this is the first thing you specify in order to add a subproblem. For the YAML version, have a look [here](http://inginious.readthedocs.io/en/v0.4/teacher_doc/task_file.html)
1. It is used for defining additional intermediate entries in the test file. Use it, download a submission and have a look at the generated test file, you'll find your additional entry.

**Comment by ohadperry** [comment]
@anthonygego  thanks for the reply. 
I have successfully setup a simple test 

`run` file
```
feedback-result success
```
and `simple_test.test` file
```
input:
    program:"answer is fake"
result: success
```
works:
```
[1/1] Testing input file : simple_test.test    
-> All tests passed                            
```
Now, trying a slightly more complex test:
`run` file
```
feedback-msg -a -m "feedback test"
feedback-result success
```
and `simple_test.test` file
```
input:
    program:"answer is fake"
result: success
tests:
    text: "feedback test"
```
and the output is :
```
[1/1] Testing input file : simple_test.test
-> No test result with tag 'text' given 
	 Expected result : feedback test                        
```

BTW:
I have exported a submission file from my production env. 
I don't understand how to use the `definetest` tool. when trying to run it 
in the terminal 
```
command not found: definetest
```

**Comment by ohadperry** [comment]
**update **
I've realized that `definetest` should be in the `run` bash file.

**Comment by ohadperry** [comment]
My question is, 
what is `feedback-msg` and if I'm using that in my run file, how can verify 
```
feedback-msg -a -m " bla bla"
```
in the test file without changing the `run` file ?

**Comment by ohadperry** [comment]
update on number 2. solved it by passing the username and program like so 
`simple_test.test`
```
input:
    program: |-
        birth = input('Enter your birth year: ')
        current = input('Enter current year: ')
        print "Your age is: ", current - birth
    username: "my_username"
```

**Comment by ohadperry** [comment]
I'm having troubles running the code. 
it's `C` code. 
getting 
```
program.c:2:11: error: initializer element is not a compile-time constant
current = input('Enter current year: ');
	       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
It even errors with simple code.

The code runs inside a container, right?
The container to run the code is selected randomly?
```
self.ssh_host = self._docker.get_host_ip(next(iter(self._containers.values()))["id"])
```
`self._containers` is 
```
{
'default': {'id': 'sha256:b69e52574ad1df4794cec2e3b6cec8e24fee2eb553b31dcfd6a07a0903071048', 'created': 1496218510}, 
'cpp': {'id': 'sha256:9f81381415b03e9cfb94be4ca33b02bcfd16b4ddc7328bc3abc2178a06c98802', 'created': 1496221369}, 
'intro': {'id': 'sha256:32e59402b3954cf5d2efa4adf4a3f6942b55d7ed5fbadbc1c0c79d11a5375128', 'created': 1498749235}, 
'php': {'id': 'sha256:a2cdf1344f8adc6905682ac2ad1ffa51aad5e8325e182294942ce378a360aeed', 'created': 1496218928}}
```
am I supposed to choose one for running C code ? if yes, which one and how?

**Comment by ohadperry** [comment]
This slowly appears like I'm talking to my self :-)
Found out what was the issue, The Iniginious export exported the code only like so
```
input:
    program: |-
        birth = input('Enter your birth year: ')
        current = input('Enter current year: ')
        print "Your age is: ", current - birth
```
where it should have exported like so 
```
input:
    program: |-
        #include<stdio.h>

        int main(void)
        {
        birth = input('Enter your birth year: ')
        current = input('Enter current year: ')
        print "Your age is: ", current - birth
    }
```

**Comment by ohadperry** [comment]
@anthonygego I have a question regrading the unit tests. do I have to use the `definetest` tool? If I want to test the output of my `feedback-grade` or my `feedback-msg`? can I test those in my *.test files?

**Comment by anthonygego** [comment]
1. Feedback is divided into several fields in the ``.test`` file. Once again, you should not write these files from scratch but instead select a set of submissions and use the autogenerated ``.test`` files for those submissions. However, the main fields are quickly described in the docs.
1. It actually seems the frontend-added fields are not saved in database and won't reflect in the autogenerated ``test`` files. Adding an ``username`` field to the ``input`` entry will indeed fix this temporarily.
1. You can create a new container layer with the common files used. Then, you only put the varying files in your task folder and use that new container as the grading environment for those tasks.
1. GCC is available in the ``cpp`` environment. You can use it to compile C code. It can be selected in the *Container setup* tab.
1. Indeed, it reflects the code actually typed into the input field, which is expected. If you want to export a parsed template, you'll need to use the ``archive`` command on the final C file.
1. You do not need to use ``definetest`` if you want to check basic fields like submission score or feedback.

**Comment by ohadperry** [comment]
@anthonygego  thank you.
question regarding 4. `Container setup tab` where is that exactly ?

**Comment by anthonygego** [comment]
This tab is located in the task edition page, when you click on *Edit task*.
