### ISSUE TITLE
get_users_info method in user_managed error

### ISSUE THREAD

**Issue by kolmant** [UCL-INGI/INGInious#236]
The get_users_info method of user_manager class tries to obtain info from non-cached auth methods using this block of code:

```        for method in self._auth_methods:
            if method.should_cache() is False:
                infos = method.get_users_info(remaining_users)
                if infos is not None:
                    for user, val in infos.items():
                        retval[user] = val
```

But the method.get_users_info in auth_db plugin doesn't return None if the method doesn't find info, it returns {username: None}, and then the condition "if infos is not None" is valid, replacing existing information with fake information (None in this case).

For example, I'm implementing a new db_auth method called eci_auth. eci_auth have information about "user1", but db_auth doesn't have it. The block of code finds the user information in eci_auth, and then doesn't find information in db_auth but "if infos is not None" is True, so it replace the information with None.

Sorry for my bad English.

**Comment by anthonygego** [comment]
Indeed, ``retval[user] = val`` should occur only if ``val is not None``, as this is actually the case for cache methods later in the code. This will be updated in ``v0.4`` branch.
