### ISSUE TITLE
running inginious-test-task with python run file getting stderr 

### ISSUE THREAD

**Issue by ohadperry** [UCL-INGI/INGInious#238]
Hi, 
I've written a run file for my tasks in python. 
I'm writing text to logging. for example, like so:
```
logging.debug('clang return ...')
```
I'm getting these in the `stderr` return value. traced it back to 
`return_value` in `docker_agent.py` line 571. 

```
return_value = await future_results
```

and because of `stderr` in my results, I'm failing the test with `noprobs = True`

**Comment by ohadperry** [comment]
@anthonygego pls help

**Comment by ohadperry** [comment]
Nvm, fixed using this init
```
logging.basicConfig(format='%(levelname)s :: %(message)s', level=logging.DEBUG,
                    handlers=[logging.StreamHandler(sys.stdout)])

```

**Comment by GuillaumeDerval** [comment]
Can we close this then?

Also, can you avoid tagging directly @anthonygego and me in the issues? It's useless as we already receive a mail at each new issue; no need to send two mails 😉

**Comment by ohadperry** [comment]
no probs. thanks
