### ISSUE TITLE
wsgi error "Cannot make container temp directory!"

### ISSUE THREAD

**Issue by mikeweyandt** [UCL-INGI/INGInious#240]
Running into the following error on a centos 7 install using apache as the webserver.

```
[Wed Aug 16 16:09:42.160978 2017] [wsgi:error] [pid 2490] 2017-08-16 16:09:42,160 - inginious.backend - INFO - Adding a new job b'\\x00\\xe2UX\\xec' 18306aba-09d1-4902-a631-7dda50d48d93 to the queue
[Wed Aug 16 16:09:42.161138 2017] [wsgi:error] [pid 2490] 2017-08-16 16:09:42,161 - inginious.backend - INFO - Sending job b'\\x00\\xe2UX\\xec' 18306aba-09d1-4902-a631-7dda50d48d93 to agent b'\\x00\\x19I\\\\\\xff'
[Wed Aug 16 16:09:42.161698 2017] [wsgi:error] [pid 2490] [client 10.180.44.118:49364] 2017-08-16 16:09:42,161 - inginious.webapp.submissions - INFO - New submission from mweyandt - mweyandt@inginious.org - tutorial/01_getting_started - 10.180.44.118, referer: http://inginious.uakron.edu/course/tutorial/01_getting_started
[Wed Aug 16 16:09:42.163690 2017] [wsgi:error] [pid 2490] 2017-08-16 16:09:42,163 - inginious.agent.docker - INFO - Received request for jobid (b'\\x00\\xe2UX\\xec', '18306aba-09d1-4902-a631-7dda50d48d93')
[Wed Aug 16 16:09:42.165747 2017] [wsgi:error] [pid 2490] 2017-08-16 16:09:42,164 - inginious.agent.docker - ERROR - Cannot make container temp directory! [Errno 2] No such file or directory: './agent_tmp/tmpberlgr0q'
[Wed Aug 16 16:09:42.165764 2017] [wsgi:error] [pid 2490] Traceback (most recent call last):
[Wed Aug 16 16:09:42.165767 2017] [wsgi:error] [pid 2490]   File "/lib/python3.5/site-packages/inginious/agent/docker_agent.py", line 327, in handle_new_job
[Wed Aug 16 16:09:42.165769 2017] [wsgi:error] [pid 2490]     container_path = tempfile.mkdtemp(dir=self.tmp_dir)
[Wed Aug 16 16:09:42.165771 2017] [wsgi:error] [pid 2490]   File "/lib64/python3.5/tempfile.py", line 368, in mkdtemp
[Wed Aug 16 16:09:42.165773 2017] [wsgi:error] [pid 2490]     _os.mkdir(file, 0o700)
[Wed Aug 16 16:09:42.165776 2017] [wsgi:error] [pid 2490] FileNotFoundError: [Errno 2] No such file or directory: './agent_tmp/tmpberlgr0q'
[Wed Aug 16 16:09:42.165781 2017] [wsgi:error] [pid 2490] 
[Wed Aug 16 16:09:42.166819 2017] [wsgi:error] [pid 2490] 2017-08-16 16:09:42,166 - inginious.backend - INFO - Job b'\\x00\\xe2UX\\xec' 18306aba-09d1-4902-a631-7dda50d48d93 finished on agent b'\\x00\\x19I\\\\\\xff'
```

Also getting a 'Parsing failed' message in the webapp.

SELinux is turned off, apache is a member of both mongodb and docker, tasks directory and web directory both have apache:apache permissions.

Tasks Dir: /opt/inginious
Web Dir: /var/www/inginious

Let me know if anyone has run into this, or if there is more info you'd like me to send you.

**Comment by anthonygego** [comment]
Did you try to set the ``local-config`` ``tmp_dir`` (See [here](http://inginious.readthedocs.io/en/v0.4/install_doc/config_reference.html)) parameter to some absolute path that apache has permissions to ? Services are sometimes launched with ``/`` as working dir...

Does your 'Parsing failed' issue is related to restructuredText parsing ? What error message do you get ?

**Comment by larkov** [comment]
I'm getting the same error and I've set the tmp_dir in the config.

`[Tue Sep 05 14:05:02.641089 2017] [wsgi:error] [pid 2136] 2017-09-05 14:05:02,640 - inginious.agent.docker - INFO - Received request for jobid (b'\\x00\\xb5\\x93\\xa4s', '10d86ac8-7c2f-4e61-af8c-7e3be677ab8b')
[Tue Sep 05 14:05:02.642235 2017] [wsgi:error] [pid 2136] 2017-09-05 14:05:02,641 - inginious.agent.docker - ERROR - Cannot make container temp directory! [Errno 2] No such file or directory: './agent_tmp/tmpyamchr3r'
[Tue Sep 05 14:05:02.642246 2017] [wsgi:error] [pid 2136] Traceback (most recent call last):
[Tue Sep 05 14:05:02.642248 2017] [wsgi:error] [pid 2136]   File "/usr/lib/python3.5/site-packages/inginious/agent/docker_agent.py", line 327, in handle_new_job
[Tue Sep 05 14:05:02.642256 2017] [wsgi:error] [pid 2136]     container_path = tempfile.mkdtemp(dir=self.tmp_dir)
[Tue Sep 05 14:05:02.642257 2017] [wsgi:error] [pid 2136]   File "/usr/lib64/python3.5/tempfile.py", line 368, in mkdtemp
[Tue Sep 05 14:05:02.642259 2017] [wsgi:error] [pid 2136]     _os.mkdir(file, 0o700)
[Tue Sep 05 14:05:02.642261 2017] [wsgi:error] [pid 2136] FileNotFoundError: [Errno 2] No such file or directory: './agent_tmp/tmpyamchr3r'
[Tue Sep 05 14:05:02.642265 2017] [wsgi:error] [pid 2136] 
[Tue Sep 05 14:05:02.643604 2017] [wsgi:error] [pid 2136] 2017-09-05 14:05:02,642 - inginious.backend - INFO - Job b'\\x00\\xb5\\x93\\xa4s' 10d86ac8-7c2f-4e61-af8c-7e3be677ab8b finished on agent b'\\x00\\xf8u\\xcb\\x9d'`

**Comment by anthonygego** [comment]
What path did you provide ? Normally, if you provide an absolute path to which the webserver user has permission, this issue should not happen.

Here's an example of configuration:

    backend: local
    local-config:
        tmp_dir: "/tmp/inginious-agent-frontend"
        debug_host: some-host.com
        debug_ports: 10000-10050

In this config the ``/tmp/inginious-agent-frontend`` dir is owned by the webserver user.

**Comment by larkov** [comment]
My misstake for writing the tmp_dir at the wrong place in the config. For me it's working fine now.

**Comment by anthonygego** [comment]
Great !

@mikeweyandt Do you still experience any issue ?
