### ISSUE TITLE
task submit button after submitting once 

### ISSUE THREAD

**Issue by ohadperry** [UCL-INGI/INGInious#243]
I'm having trouble debugging this. 
The submit button for the task page looks like this at first
<img width="796" alt="submit button before the first submit" src="https://user-images.githubusercontent.com/2236337/29749139-58553912-8b2e-11e7-8880-5ad07adff293.png">

after placing the solution in the textarea, submitting and receiving the feedback, the button looks like this
<img width="833" alt="submit button after first submit" src="https://user-images.githubusercontent.com/2236337/29749144-7ba5fabe-8b2e-11e7-9877-dbd4d53618fd.png">

if I submit again I get back a json response
<img width="473" alt="submit result is json in the second submit" src="https://user-images.githubusercontent.com/2236337/29749154-8ed4912c-8b2e-11e7-96f7-859ad26064b3.png">

The feedback is html. after playing around with it for a while, found the button not changing  If I remove the css stylesheets but the json response is still happening. 

@anthonygego how would you debug this?

**Comment by ohadperry** [comment]
@GuillaumeDerval ? any clue?

**Comment by GuillaumeDerval** [comment]
I'm currently abroad on the other side of the world with no really correct internet connection, so I won't have any clues for some time ;-)

Please avoid tagging us directly in github, we receive a mail for each issue, but sometimes it's complicated to answer rapidly to each question :-)

**Comment by ohadperry** [comment]
sorry for that.

**Comment by ohadperry** [comment]
The issue was my feedback html. It contained loading jquery js. 
apparently, when loading jquery after the jQuery Form Plugin, creates a bug in submitting. 
my code changed from always loading jquery 
```
<script src="path_to_jquery.js"></script>
```

to 
```
if(typeof jQuery=='undefined') {{
      loadjquery async and then processJqueryRequiredCode()
}} else {{
            processJqueryRequiredCode()
 }}
```
