### ISSUE TITLE
Getting a 404 while downloading the submissions.

### ISSUE THREAD

**Issue by codesagar** [UCL-INGI/INGInious#246]
While downloading the submissions I get a 404 page. Following is the console output.

```
inginious.webapp.requests - INFO - ::1:47204 - "HTTP/1.1 POST /admin/CSE7302c-Batch31/download" - 404 Not Found
```

Any ideas on how to debug?

**Comment by sizhky** [comment]
I'm having the same issue. To give some more info, I am able to download individual submissions without any problem.
```
127.0.0.1:40912 - "HTTP/1.1 GET /admin/CSE7302c-Batch31/student/XXX@gmail.com/CSE7302c-Batch31/59859a5f34bb0f5b0d217916" - 200 OK
```

**Comment by GuillaumeDerval** [comment]
https://github.com/UCL-INGI/INGInious/blob/master/inginious/frontend/webapp/pages/course_admin/utils.py#L80

The error is here; it fails when there are no "aggregations", i.e. no groups nor classrooms.

**Comment by GuillaumeDerval** [comment]
So for now you can simply create an empty group/classroom, we will push a fix in the following days

**Comment by codesagar** [comment]
Yep we do have a classroom defined and I'm able to download the submissions based on classrooms. I face error only when I try to download submission by selecting students.
