### ISSUE TITLE
Student view for admin

### ISSUE THREAD

**Issue by ogoletti** [UCL-INGI/INGInious#249]
All is in the title, an admin should have the possibility to change is view of the interface as another permission group : tutor or student

**Comment by anthonygego** [comment]
Behaviour has changed. Not relevant anymore.

**Comment by ogoletti** [comment]
Meh. Still I think with some options that are not always documented, or just to be 100% sure when changing deadline to know what exactly a student can view or not, the feature would still make sense. For example by providing in the admin interface a dummy student and a dummy tutor access. 
Would this still make sense ?

**Comment by GuillaumeDerval** [comment]
It's a lot of work (and maintainance) for something that could just be solved with some additional documentation...

**Comment by darkyne** [comment]
Admins already have access to the student view... no ?

**Comment by ogoletti** [comment]
admins kind of have access to the exercises list as shown to the students (even though it's not explicitly said in the interface) but this is not the whole course view. How can I check for example that an exercise is available in read-only mode for students after an exam. 
Of course I could just know that setting a deadline in the past (and exiting the exam mode) would do the trick. But I certainly do not want students to be able to submit again. Allowing a quick check to be sure of the effects of an indirect manipulation of the course settings through a student view would be a nice to have. 

No idea about the dev/maintenance cost though. I was just answering to the "Not relevant anymore".

**Comment by darkyne** [comment]
ok I get it. Actually you want to press a button and get into a real student experience to test the entire course and parameters (verify you can't access to x etc). This is not a bad idea, especially for new teachers who are not sure about their course configuration but I don't know the cost to implement this. Still, this is totally doable if you created a second account (to play as a student) but the feature is interesting.

**Comment by ogoletti** [comment]
It's doable if I create an account with another email address... Also, with lti-course for example, I might have to register that account to the lti-hosting platform, I can't just "add" a user from the admin interface. A lot of trouble in my user opinion to have access to that view. 
In the end, what I end up to do is ask another admin for the course (sometimes someone unfamiliar with the inginious settings interface) to remove me from the admin list, and put me back in later. 
Again, no idea of the dev costs, just saying from a user point of view, it would be nice to have.
