### ISSUE TITLE
Read-only submission

### ISSUE THREAD

**Issue by ogoletti** [UCL-INGI/INGInious#250]
A student should be able to get an anonymised link of their submission so that they could share it (e.g. on social network). The view would be a readonly view with the feedback of the submission still visible. The link should only contain the submission id. 
There should be an option in the task conf to allow or not this feature on a par-task basis.
If an admin follow such a link, he should be redirected towards the current submission link with the user details.

**Comment by anthonygego** [comment]
A submission link is now available.
