### ISSUE TITLE
getinput does not provide the filename.

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#26]
The api within the sandbox (getinput, parsetemplate) does not provide any way to extract the original filename.

If a file submission box allows both .zip and .tgz, then it is difficult for the "run" script to unarchive the file without the original extension.

**Comment by layus** [comment]
https://gist.github.com/layus/64d9d2a0d6c051b86974 is what I had to do to uncompress the archive within the container.

**Comment by oliviertilmans** [comment]
:+1:  :100:
Getting students to follow naming convention is surprisingly difficult ...

**Comment by layus** [comment]
The versioned file is at https://github.com/layus/FSAB1402-INGInious/blob/master/project/extract.py

**Comment by 31416r** [comment]
This should be fixed/merge quickly. Anthony ?

**Comment by 31416r** [comment]
Do not forget to update the documentation !

http://inginious.readthedocs.io/en/latest/teacher_doc/run_file.html#getinput

**Comment by GuillaumeDerval** [comment]
1c21c64b9be7e4e4f73327758d30c9659fed3e80

**Comment by GuillaumeDerval** [comment]
and 4919966cf1fe8d40702d43c01f63b2cd1f1f2878, also
