### ISSUE TITLE
Is Stata supported?

### ISSUE THREAD

**Issue by joshjacobson** [UCL-INGI/INGInious#262]
Is Stata coding supported in this?

**Comment by anthonygego** [comment]
Yes of course, almost all Linux software will run in Docker containers. You'll need to write your own Dockerfile that will setup it, as well as an appropriate license. Look at https://github.com/UCL-INGI/INGInious-containers/tree/master/grading for examples, and refer to both Docker documentation and INGInious last tutorial task "Creating new environments".
