### ISSUE TITLE
can't find how to tail the logs of mcq and backend agent

### ISSUE THREAD

**Issue by ohadperry** [UCL-INGI/INGInious#263]
I'm asking regarding this
http://inginious.readthedocs.io/en/v0.4/commands_doc/inginious-agent-mcq.html
I have an issue where my queue is full and jobs are not emptied. 
I'm trying to tail the log of `/bin/inginious-agent-mcq`
The process is running 
```
ps aux |grep ingi
root      1986  0.0  0.2 331200 20700 ?        Sl   Nov06   1:02 /usr/bin/python3.5 /bin/inginious-agent-mcq --tasks /mnt/efs/tasks tcp://my_ip:2001
root      1988  0.1  0.6 1398184 47236 ?       Sl   Nov06   1:19 /usr/bin/python3.5 /bin/inginious-agent-docker --tasks /mnt/efs/tasks tcp://my_ip:2001
```
the file `/bin/inginious-agent-mcq` has `logging.error` and `logger.error` but I don't knwo where it's logging to? which file ?

**Comment by ohadperry** [comment]
attaching the content of mcq just in case
```
#!/usr/bin/python3.5
# -*- coding: utf-8 -*-
#
# This file is part of INGInious. See the LICENSE and the COPYRIGHTS files for
# more information about the licensing of this file.
#

""" Starts an agent """

import argparse
import logging

from zmq.asyncio import ZMQEventLoop, Context
import asyncio

from inginious.agent.mcq_agent import MCQAgent

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("backend", help="Address to the backend, in the form protocol://host:port. For example, tcp://127.0.0.1:2000", type=str)
    parser.add_argument("--friendly-name", help="Friendly name to help identify agent.", default="", type=str)
    parser.add_argument("--tasks", help="Path to the task directory. "
                                        "By default, it is ./tasks. You must ensure that this directory is synchronized at any time"
                                        "with the backend and the client", default="./tasks")
    parser.add_argument("-v", "--verbose", help="increase output verbosity",
                        action="store_true")
    args = parser.parse_args()

    # create logger
    logger = logging.getLogger("inginious")
    logger.setLevel(logging.INFO if not args.verbose else logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO if not args.verbose else logging.DEBUG)
    formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    ch.setFormatter(formatter)
    logger.addHandler(ch)

    # start asyncio and zmq
    loop = ZMQEventLoop()
    asyncio.set_event_loop(loop)
    context = Context()

    # Create agent
    agent = MCQAgent(context, args.backend, args.friendly_name, args.tasks)

    # Run!
    try:
        loop.run_until_complete(agent.run_dealer())
    except:
        pass
    finally:
        logger.info("Closing loop")
        loop.close()
        logger.info("Waiting for ZMQ to send remaining messages to backend (can take 1 sec)")
        context.destroy(1000)  # give zeromq 1 sec to send remaining messages
```

**Comment by anthonygego** [comment]
The location of logs depends on your configuration. If you have setup a CentOS/Fedora service for instance, you'll see the logs using ``journalctl``. You can also simply see the logs by running the ``inginious-agent-*`` commands directly in the shell.

**Comment by ohadperry** [comment]
@anthonygego thanks, will check it out. 
when running `inginious-agent-*` from shell the problem doesn't occur. so tailing the log is a must in this case. tried to find a command to keep displaying the last lines and update the console as they appear (tailing).

all I found was
```
journalctl  | tail -n 20
```
which displays the last lines and then exits.

**Comment by anthonygego** [comment]
You can use ``journalctl -f`` to follow and print new entries.

**Comment by ohadperry** [comment]
Thanks, 
I just had an issue in production where I had 119 tasks in queue. 
My configuration is 2 separate servers. 
1 for frontend that runs the inginious webapp and backend 
1 for backend which runs the `inginious-agent-mcq` and `inginious-agent-docker`

tried to ssh to backend production and start the
`/usr/bin/python3.5 /bin/inginious-agent-mcq --tasks /mnt/efs/tasks tcp://<frontend>:2001`
didn't work. 
tried`journalctl -f`. was frozen. didn't show anything.

tried to ssh to frontend production and kill the `/bin/inginious-backend`

sudo kill -9 1961 <process id of /bin/inginious-backend>
now error is `"Environment not available."`
restarted the frontend. didn't work.
restarted the backend. worked.

My Guess. there is a network issue because it's 2 servers.

**Comment by GuillaumeDerval** [comment]
Ok, strange. If you can reproduce, please open a specific issue. Thanks! :-)
