### ISSUE TITLE
There should be a way to disable submission without hiding a task.

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#27]
When a task reaches the deadline, the students are no more able to see the task.

This raises two concerns
 1. Students cannot see their previous submissions, nor check if their last (in-extremis) submission was accepted or not. 
 1. The progress indicator changes because the task is removed from the course.

We need to distinguish submission deadline and task availability.

**Comment by GuillaumeDerval** [comment]
Fixed in ca256e9cf9a50f289b79e1a562b1b0c54f6205b0

**Comment by layus** [comment]
Ouch ! ca256e9 is a mega multi-features update :-)

Did you know that you can add "fixes #27" to a commit message to auto-close github issues ?

**Comment by GuillaumeDerval** [comment]
In fact, these new features are really heavily linked, so I did not try to separate each small feature from the big one.

Yep I know about that I could have used "fixes #blabla" but I only remembered that after I pushed ;-)

**Comment by layus** [comment]
I know that feeling ;-)
