### ISSUE TITLE
Visible but not accessible tasks

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#270]
There seems to be no way to show a task while keeping inaccessible to students. When a task is not accessible (outside the deadline), it is "not shown to students". It would be nice to have a task that is visible, but not open yet. Students would then know that they are at the right location, but that submissions are not open yet. Ideally they would also see the opening date.

**Comment by GuillaumeDerval** [comment]
Linked with #250.

**Comment by anthonygego** [comment]
Should be fixed, or at least behaviour has changed with task dispensers. Feel free to reopen if necessary.
