### ISSUE TITLE
'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by CaptainJava01** [UCL-INGI/INGInious#271]
No matter which task I do (even when I do the preinstalled tutorial): Every time I hit the submit button I get following error message:
```
An internal error occurred. Please retry later. If the error persists, send an email to the course administrator.

The grader did not return a readable output : 'NoneType' object has no attribute 'items'
```

What can I do?
Can you help me?

**Comment by anthonygego** [comment]
Did you clone the ``v0.4`` branch of the repository ? Is there any line related to ``inginious-agent-docker`` in the logs ?

**Comment by CaptainJava01** [comment]
I attached a screenshot with the error message
![tmp](https://user-images.githubusercontent.com/26738600/33820452-ca5c7fec-de4f-11e7-9f5d-bdc74b8d0c9f.JPG)

**Comment by anthonygego** [comment]
This looks like a communication issue between the INGInious script inside the container and the agent. It is likely that the container-side script is encountering an error and closes the socket without replying at all.

What is your configuration ? Are you able to run a Docker container without any issue ? Does SSH debugging work or do something more than directly crashing ? Would you be able to fetch the stdout of the mentioned container (this is usually stored in the ``/var/lib/docker`` folder, it should contain the debug info of the INGInious script) ?

@GuillaumeDerval Do you any more idea on how to solve this issue ?

**Comment by CaptainJava01** [comment]
I installed INGInious on CentOS 7 as described in the docs. I'm able to run docker containers. SSH does work but I don't know where to navigate in /var/lib/docker. There is a directory named containers but in that there is no directory named like the container that doesn't return anything.

**Comment by anthonygego** [comment]
If you can run a submission using SSH debug, you may be able to catch the exception by running ``./run`` and then ``exit`` to mimic the usual grading behaviour. This should therefore crash but hopefully with more verbosity.

It's possible that the folders are not available anymore if Docker works fine and destory the container correctly. Maybe ``docker logs`` can be more helpful.

**Comment by CaptainJava01** [comment]
So, finally I got it by removing and installing Inginious again. Now everything is running fine. Now, I tried to set up inginious-lti. I configured it by having a look on this site: https://github.com/UCL-INGI/INGInious/issues/272 However I don't understand how I can bind the account of Moodle and Inginious. Furthermore, I'm getting the error: 

`

Python | /usr/lib/python3.5/site-packages/inginious/frontend/pages/lti.py in GET_AUTH, line 21
-- | --
GET http://192.168.235.128:8080/@af3784b7a585727dbf1d937c025a5730e5487236@/lti/task

`
Can you help me again?

**Comment by CaptainJava01** [comment]
Thanks, it seems to work now.
