### ISSUE TITLE
New LTI documentation

### ISSUE THREAD

**Issue by tijcolem** [UCL-INGI/INGInious#272]
Hello, 

It appears you merged the lti and web-app into one single interface (this is great btw) in the master branch. Do you have documentation for how to correctly set this up?  Our CS dept at the University of Colorado would really like to use this for auto-grading and using it within our Moodle instance. The older version had issues with separation of LTI users and web-app users so the web-app could not review any submission via LTI.  If this new version solves this problem this will be a home run! 

It's unclear to me how to set up the new LTI interface as the url to access the LTI course task appear to have changed. It used to be https://HOST:PORT/launch/course_id/task_id
Do you still need to define the LTI config file 'configuration.lti.yaml' or do you include the parameters and use them in 'configuration.yaml.'  I'm also unsure of what to include in the UI 'LTI Keys' input box.   

I realize this is probably premature and the docs are coming but I would love to start working with this now as the  LTI user ids have been a crippling using the application. Any help setting up a basic task via LTI would be greatly appreciated. 

Thanks for supporting a great application.  -Tim

**Comment by anthonygego** [comment]
Hi,
Here's the way to configure an LTI course:
- In the admin pannels under Settings tab, click on *Enable LTI*. Then, you'll have to set a pair of ``key:secret`` in the *LTI keys* area. You can set multiple pairs if you want. Here I set the ``lticonsumer`` key with ``lticonsumer`` secret.
![capture du 2017-12-14 08-14-39](https://user-images.githubusercontent.com/4233013/33979925-df0242a2-e0a6-11e7-9a6c-7e1251c5a6b9.png)
This indeed makes the ``configuration.lti.yaml`` file obsolete.
- Check the *Send grades back* to send them to Moodle.
- The new launch URL is ``https://host:port/lti/course_id/task_id``

@francoismichel reported that there was an issue with sessions, that can expire immediately in some cases, so I'll keep this issue open until this is fixed.

LTI users now need to bind their account with the INGInious one. Once their account is bound with the course context (courseid + LTI key), they will be automatically logged into INGInious via LTI. This requires all the LTI users to be able to sign in or register into INGInious, which is typically the case if you use a common authentication mechanism. You can disallow public registration by settings ``allow_registration`` to ``false`` in the ``configuration.yaml`` file.

Please note however that INGInious usernames (and profiles) are now distinct from the authentication service username to avoid conflicts when multiple auth methods are set. So they set their username at the first login. Original usernames from the authentication source are saved in DB but not yet displayed in the admin interface. It is also planned to add additional fields from an auth method such as a different student identifier than username (registration number), curriculum,... but this is not yet implemented.

**Comment by tijcolem** [comment]
Many thanks for providing an example to configure the LTI.   LTI is now working. 
I really like the way this is implemented with this new version. 

I also noticed you added Google OAuth. This will make the registration a breeze for students and further simplify the LTI workflow.  Nice work with all of this! We are planning to be use this next semester in our courses at CU Boulder. 

-Tim

-Tim
