### ISSUE TITLE
Exception occured in container ....is not JSON serializable)

### ISSUE THREAD

**Issue by tijcolem** [UCL-INGI/INGInious#279]
Hello, 

As always, thanks for supporting such a nice auto-grader. Our CS dept at CU looks forward to using it this Spring semester in many of our courses. 

In the most recent version, I noticed a somewhat critical error that I'm hoping you may know what's going on. 

When I use the file upload problem type I always get this error after submitting the file. 

<img width="857" alt="screen shot 2018-01-11 at 6 25 46 pm" src="https://user-images.githubusercontent.com/7087120/34858440-8a21f444-f70d-11e7-8235-8d4e3742ccbf.png">

"An internal error occurred. Please retry later. If the error persists, send an email to the course administrator. [Submission #5a582b59bd8bcc13c0040de1]
Exception occured in container (b'print("Hello World!")' is not JSON serializable)"

 When I run the '01_getting_started' task in the Tutorial it works just fine, but if I add a sub-problem and use type file upload it throws the error "JSON is not serializable" as seen above. 

I also changed one of my own tasks from file upload to code submission and it works fine when using containers to grade so it does seem isolated to the file upload feature. 

I also noticed that when viewing the previous submissions, the files are indeed being uploaded as I can view the content of the files. My first suspicion was the files were not being uploaded but this doesn't appear to be the case. 

I tried to isolate where in the code this might be occurring.  

inginious/frontend/pages/tasks.py 
 function def POST(self, courseid, taskid, isLTI): 

    elif "@action" in userinput and userinput["@action"] == "check" and "submissionid" in userinput:

    ...<in this block> 

     return self.submission_to_json(result, is_admin, False, True if default_submission is None else default_submission['_id'] == result['_id'], t
ags=task.get_tags())

this is the print out of the result objects when stepping through the block above using the 01_getting_started task with the added file upload sub-problem. 

{'submitted_on': datetime.datetime(2018, 1, 12, 1, 41, 5, 581000), 'archive': None, 'response_type': 'rst', 'result': 'crash', 'text': 'Exception occured in cont
ainer (b\'print("Hello World!")\' is not JSON serializable)', 'input': ObjectId('5a581231bd8bcc11187a317d'), 'stderr': '', 'custom': {}, 'username': ['colemat2']
, 'courseid': 'tutorial', 'tests': {}, '_id': ObjectId('5a581231bd8bcc11187a317f'), 'problems': {}, 'taskid': '01_getting_started', 'status': 'error', 'stdout': 
'', 'grade': 0.0}

{'submitted_on': datetime.datetime(2018, 1, 12, 1, 41, 5, 581000), 'archive': None, 'response_type': 'rst', 'result': 'crash', 'text': 'Exception occured in cont
ainer (b\'print("Hello World!")\' is not JSON serializable)', 'input': {'thecode': 'print("Hello World!")', 'thecode_twp': {'value': b'print("Hello World!")', 'f
ilename': 'hello.py'}}, 'stderr': '', 'custom': {}, 'username': ['colemat2'], 'courseid': 'tutorial', 'tests': {}, '_id': ObjectId('5a581231bd8bcc11187a317f'), '
problems': {}, 'taskid': '01_getting_started', 'status': 'error', 'stdout': '', 'grade': 0.0}

Anyway, I guess my first question is have you seen this error before? Perhaps it's something with my implementation but I wanted to see if you can reproduce this on your system. 

Thanks again for any help you may be able to offer.  I'll also keep digging.  

-Tim

**Comment by tijcolem** [comment]
Update on this. I believe I tracked it down to a python dictionary that contains a binary format value. 

Here is an example of dic being passed to the grading container using a simple hello_world.py file. 

e.g. 
__inputdata.json
{'type': 'start', 'input': {'thecode': 'print("Hello World!")', '@username': 'colemat', 'thecode2': {'value': b'print("Hello World!")', 'filename': 'hello.py'}, '@lang': 'en'}, 'debug': True}

 'value': b'print("Hello World!") this what causes this routine (below) in the receiving docker container to fail. 

/usr/bin/INGInious
def _start_cmd_sync(self, data):
...
f.write(json.dumps(data) 

This is where it throws the "not serializable exception" 

I made a change to the way the frontend reads in the file upload and decoding it as ascii.  I'm not sure if this is the right approach but this does seem to work. 

inginious/frontend/tasks_code_boxes.py

def adapt_input_for_backend(self, input_data):
                "value": input_data[self.get_complete_id()].value.decode("ascii")  }

**Comment by anthonygego** [comment]
I'll look at this as soon as possible. However, we'd been using base64 for a long time to communicate between the webapp and the agents before transferring binary. I don't remember quite well when this migration was done so I strongly recommend you to rebuild the containers from the master branch source code (the docker hub ones are made for v0.4).

    docker build -t ingi/inginious-c-base base-containers/base
    docker build -t ingi/inginious-c-default base-containers/default

And see if the problem still occurs.

**Comment by tijcolem** [comment]
Thanks for the reply. Rebuilding the containers from the master branch did indeed solve the problem. Thanks!
