### ISSUE TITLE
Admin login

### ISSUE THREAD

**Issue by abdelmaj** [UCL-INGI/INGInious#280]
Hi,
I downloaded inginious-webapp and am running it on the localhost. When I run inginious am able to login as a user not as an admin. And when I click on the course admin link in the tutorial it gives me "page not found error"  Can you please guide me on how to login as an admin so I can create a course.

**Comment by anthonygego** [comment]
Hi,

Which version are you using ?

- If you have cloned the ``v0.4`` branch, you should add a superadmin user in the ``configuration.yaml`` file under the key ``superadmins``.

      superadmins:
        - me
        - you

  In this case the user is provided by one of the authentication method. If you've setup the database one, you should register yourself as a normal user.

- If you have cloned the ``master`` branch, the superadmin user is created when running the ``inginious-install`` script and should automatically be added in the ``configuration.yaml`` file.

**Comment by abdelmaj** [comment]
Thanks for your response.
Am using v4 and I use inginious-install to generate the configuration file. However it does not ask me for a password like the user during the configuration generation.
Also I noticed that I do not have the /admin/* file created. I do not know if am missing something.
Also Am installing it on Ubuntu 16.04 image that runs inside virtualbox.

**Comment by GuillaumeDerval** [comment]
You should create a user and then use it as administrator. Feel free to reopen the issue if something is not right :-)
