### ISSUE TITLE
unrecognized arguments: webapp

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#287]
I installed inginious using "sudo -H pip3 install --upgrade git+https://github.com/UCL-INGI/INGInious.git"

then I run:

    $ inginious-install webapp

and got: 

    usage: inginious-install [-h] [--file FILE]
    inginious-install: error: unrecognized arguments: webapp

**Comment by anthonygego** [comment]
You only need to run ``inginious-install`` with no argument using the code in the master branch. Both the frontend has been merged.

**Comment by erelsgl** [comment]
OK. So maybe the documentation here should be fixed
http://inginious.readthedocs.io/en/latest/install_doc/installation.html#installing-inginious
