### ISSUE TITLE
Installation guide does not correspond to tools in master branch

### ISSUE THREAD

**Issue by donnm** [UCL-INGI/INGInious#288]
I'm following the install guide:

http://inginious.readthedocs.io/en/latest/install_doc/installation.html

When I get to the part about configuring lti or webapp, the installation instructions do not correspond to the tools installed via pip/git master. Specifically the syntax for `inginious-install lti` in the tool installed seems to save the configuration in a file `lti` instead of setting up the lti module.

In fact I can't figure out where to find the inginious-lti executable, although there is an inginious-webapp installed.

I installed with `pip3 install --upgrade git+https://github.com/UCL-INGI/INGInious.git` as root.

**Comment by GuillaumeDerval** [comment]
The documentation is not up-to-date for the master branch and this branch is currently not made for production, but rather for dev setups.

You should instead use the v0.4 branch which is stable, which has an up-to-date documentation.

The LTI support has been merged with the webapp in the master branch.

**Comment by donnm** [comment]
OK, I see. The installation documentation needs to be updated so that the pip3 install command installs the v0.4 branch, and not the master (dev) branch.

**Comment by GuillaumeDerval** [comment]
If you use the "stable" branch of the documentation, it is up-to-date:
http://inginious.readthedocs.io/en/stable/install_doc/installation.html#installing-inginious

However, it is possible that we have links that point to "latest", which we should indeed modify.
We should also put a warning at the beginning of the documentation to ensure that users are on the right branch.

**Comment by donnm** [comment]
Thanks. I followed the documentation link from the README.md on the github main page. It points to "latest".
