### ISSUE TITLE
Cannot log in as newly created "superadmin"

### ISSUE THREAD

**Issue by donnm** [UCL-INGI/INGInious#289]
During `inginious-install` and creating of the `configuration.yaml` I set up an admin user `superadmin` with a password. This username password combination does not work in the webapp UI, however.

My `configuration.yaml` contains:

```
superadmins:
- superadmin

```

**Comment by donnm** [comment]
Thinking back about this I may have misunderstood the prompts posed by `inginious-install lti`, but the confusing part was that it asked for a username and password, which then could not be used to log in to the system.

**Comment by amrondonp** [comment]
I found a 'hack' if you will
Every time I deploy a new INGInious instance, I run this code on a mongo console

```
use INGInious
db.users.insert({
    "username" : "superadmin",
    "realname" : "superadmin",
    "language" : "english",
    "password" : "964a5502faec7a27f63ab5f7bddbe1bd8a685616a90ffcba633b5ad404569bd8fed4693cc00474a4881f636f3831a3e5a36bda049c568a89cfe54b1285b0c13e",
    "email"    : "superadmin@inginous.org",
    "bindings" : {

    }
})
```

That hash that you see there is the hash for 'superadmin' so in this case the user name would be superadmin as well as the password

**Comment by anthonygego** [comment]
Using v0.4 with ``db_auth`` plugin, you should create the user by registrating first.

Using v0.5 (master) the user should be created by the install script, but you're not the only ones who reported it actually does nothing. Some database initialization should be missing. This will be investigated.

**Comment by GuillaumeDerval** [comment]
@anthonygego did you investigate?

**Comment by anthonygego** [comment]
Not yet, this concerns the core code base and not plugins.
