### ISSUE TITLE
lighttpd/fastcgi/flup issues on Debian

### ISSUE THREAD

**Issue by donnm** [UCL-INGI/INGInious#291]
The install guide is written for CentOS, so following along for Debian is non-trivial.

Debian's lighttpd includes fastcgi, but the flup module for inginious-webapp is missing when run with this combination, so we see this error in journalctl:

```
lighttpd[19212]: Traceback (most recent call last):
lighttpd[19212]:   File "/usr/local/bin/inginious-webapp", line 69, in <module>
lighttpd[19212]: 2018-02-05 15:33:01,891 - inginious.agent.docker - INFO - Agent started
lighttpd[19212]: 2018-02-05 15:33:01,891 - inginious.agent.docker - INFO - Saying hello to the backend
lighttpd[19212]: 2018-02-05 15:33:01,892 - inginious.agent.mcq - INFO - Agent started
lighttpd[19212]: 2018-02-05 15:33:01,892 - inginious.agent.mcq - INFO - Saying hello to the backend
lighttpd[19212]: 2018-02-05 15:33:01,892 - inginious.backend - INFO - Backend started
lighttpd[19212]:     import flup.server.fcgi as flups
lighttpd[19212]: ImportError: No module named 'flup'
lighttpd[19212]: 2018-02-05 15:33:01,896 - inginious.client - INFO - Connecting to backend
```

Installing the default flup with `pip3 install flup` fails (not working for python3).
Attempted to resolve by `pip3 install flup6` yields a hung connection to the server.
Attempted to resolve by `pip3 install flup-py3` yields 500 internal error with messages in `/var/log/lighttpd/error.log`:

```
2018-02-05 15:44:27: (mod_fastcgi.c.2424) unexpected end-of-file (perhaps the fastcgi process died): pid: 16861 socket: unix:/tmp/fastcgi.socket-0
2018-02-05 15:44:27: (mod_fastcgi.c.3175) response not received, request sent: 1196 on socket: unix:/tmp/fastcgi.socket-0 for /inginious-webapp?, closing connection
```

My `/etc/lighttpd/conf-available/10-fastcgi.conf`:

```
# /usr/share/doc/lighttpd/fastcgi.txt.gz
# http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs:ConfigurationOptions#mod_fastcgi-fastcgi

server.modules   += ( "mod_fastcgi" )
server.modules   += ( "mod_rewrite" )

alias.url = (
    "/static/" => "/usr/local/lib/python3.5/dist-packages/inginious/frontend/static/"
)

fastcgi.server = ( "/inginious-webapp" =>
    (( "socket" => "/tmp/fastcgi.socket",
        "bin-path" => "/usr/local/bin/inginious-webapp",
        "max-procs" => 1,
        "bin-environment" => (
            "INGINIOUS_WEBAPP_HOST" => "0.0.0.0",
            "INGINIOUS_WEBAPP_PORT" => "80",
            "INGINIOUS_WEBAPP_CONFIG" => "/var/www/INGInious/configuration.yaml",
            "REAL_SCRIPT_NAME" => ""
        ),
        "check-local" => "disable"
    ))
)

url.rewrite-once = (
    "^/favicon.ico$" => "/static/icons/favicon.ico",
    "^/static/(.*)$" => "/static/$1",
    "^/(.*)$" => "/inginious-webapp/$1"
)

```

The `inginious-webapp` process is running, but it seems lighttpd can't talk to it.

**Comment by GuillaumeDerval** [comment]
The lacking requirement is
`pip3 install "flup>=1.0.3.dev"`

You can install the whole project with CGI enabled:
pip3 install --upgrade "git+https://github.com/UCL-INGI/INGInious.git@v0.4#egg=project[cgi]"

We should make the syntax here clearer, but it's written in the documentation: http://inginious.readthedocs.io/en/v0.4/install_doc/installation.html#installing-inginious

I leave this issue opened as a todo to make this part of the documentation clearer.

**Comment by donnm** [comment]
Thanks! That solved it. Indeed that was unclear in the docs. It does say to add [cgi], but neglects to say you also need "#egg=project" in the url.

With that I have it running under lighttpd, but found out I had to update some aliases in `/etc/lighttpd/conf-available/10-fastcgi.conf`.

```
alias.url = (
   # "/static/" => "/usr/local/lib/python3.5/dist-packages/inginious/frontend/static/"
    "/static/common/" => "/usr/local/lib/python3.5/dist-packages/inginious/frontend/common/static/",
    "/static/webapp/" => "/usr/local/lib/python3.5/dist-packages/inginious/frontend/webapp/static/"
)
```

**Comment by donnm** [comment]
Just a question here since I'm debugging LDAP issues. To install both fastcgi and ldap modules would we use the following?

```
pip3 install --upgrade "git+https://github.com/UCL-INGI/INGInious.git@v0.4#egg=project[cgi,ldap]"
```

Language in the docs seems to imply only one (v0.4):

> simply add [cgi], [ldap] or [saml2] to the above command, depending on your needs
