### ISSUE TITLE
lti frontend POST exception from tool consumer link

### ISSUE THREAD

**Issue by donnm** [UCL-INGI/INGInious#292]
I'm trying to get the lti frontend set up with Blackboard. The tool is approved by the admin, I've set up the key and secret on the consumer side as well as the lti configuration. A previous blocker of oauth authentication was fixed by correcting the system time (off by one hour).

Now when I click the link to INGInious I've set up (`https://servername/launch/tutorial/01_getting_started`) I get the following error from lighttpd:

inginious.lti.pages.utils - INFO - ERROR: POST exception 'user_id'

It's not very descriptive, and poking around seems to be caused by an exception at line 79 in `frontend/lti/user_manager.py`:

```
            "username": ext_user_username if self._lti_user_name == 'ext_user_username' else user_id,
```

Does this mean my tool consumer (Blackboard) is not sending this field? How can I debug what is sent in the POST request from the tool consumer?

**Comment by anthonygego** [comment]
We've never tested it with Blackboard. However, the LTI spec mentions the ``user_id`` field should be returned. Maybe the returned format is not a string which may cause some problems and we should simply do a cast before.

You can check the passed data using testing tools like : http://lti.tools/saltire/ => *Test tool provider*. There is a help button in the navigation bar.

**Comment by donnm** [comment]
Our INGInious instance lies behind a firewall, so external testing tools are not really possible. I'll try debugging with print statements.

In the meantime, is there any documentation on how to have lti+webapp at the same time using v0.4 and fastcgi?

**Comment by GuillaumeDerval** [comment]
> In the meantime, is there any documentation on how to have lti+webapp at the same time using v0.4 and fastcgi?

Everything we have is on inginious.rtfd.org. It may not be that much, sorry. It should be simpler with v0.5.
