### ISSUE TITLE
OAuth Issue

### ISSUE THREAD

**Issue by tijcolem** [UCL-INGI/INGInious#293]
Hi, 

We are now actively using INGInious for 2 classes and soon to be 4 classes. Once again, thanks for supporting a great software product! 

I have a very odd issue that stems from Oauth. We have a user base of around 150 users currently registered in the system, which all created their accounts via Google Oauth.  A handful of users (4)  reported that when they log into their accounts via OAuth, it logs them into another user account. 

For example, here are two users as defined in Mongodb ( note I changed the real names for privacy issues) that have this issue. 

User: foobar1

{ "_id" : ObjectId("5a73e8e8d9358563c74a8271"), "bindings" : {
"GoogleAuthMethod" : [ "**********01894655", { } ] }, "realname" : "foobar1
Ettachfini", "email" : "foobar1@colorado.edu", "username" : "foobar1", "language" : "en",
"ltibindings" : { "CSCI-3155" : { "CSCI3155" : "1310" } } }

User: foobar2

{ "_id" : ObjectId("5a73e5bbd9358563c74a825f"), "bindings" : {
"GoogleAuthMethod" : [ "*********66354406", { } ] }, "realname" : "foobar2", "email" : "foobar2@colorado.edu", "username" : "foobar2", "language" : "en" }

User foobar2 logs in via Google Oauth with proper credentials and gets logged in as user foobar1. 

Here's is what I know. 

1 ) All users have unique GoogleAuth Numeric ID's.

2 ) The affected users can register via Google Oauth on our developer server running the same INGInious code and can login to the correct user account.  This dev system only has 10 users, so the issue appears to present itself with more users. 

3 ) From #2, I confirmed the scope mapping (email, name) are being mapped correctly to the user account. 

4 ) Before they login into INGInious, they are logged out of all Oauth applications and use Chrome browser in incognito mode to log in. They again go to a different account once logged in. 

My first guess was that a MongoDB query was returning an incorrect user, but that doesn't appear to be the case.  Now, I'm not looking at this section of code: 

https://github.com/UCL-INGI/INGInious/blob/e65d04a2e813cfc5247695f2e3a51b324e308382/inginious/frontend/plugins/auth/google_auth.py#L38-L47

Perhaps on the callback method, the argument auth_storage["oauth_state"] is being passed the wrong state. It's difficult to reproduce as only a few users are affected and they need to login for me to see what's happening. 

Anyway, I thought I'd point this out and see if anyone else has this issue. For now, the workaround is to disable Google Oauth and use another auth method. I'll try to get more info and trap this error and update this issue. 

-Tim

**Comment by anthonygego** [comment]
This "race condition" was reported to me yesterday and was fixed in e65d04a. I recommend you to update as soon as you can. Using external auth, empty usernames can now exist with no password if users have not set their username yet, but these usernames were left as the matching key to open the session. Therefore any unitialized account left in DB can trigger such an unwanted behaviour.

Unfortunately this leaves incorrect entries in DB, if you do not have a way to fetch data from the auth source without being authenticated as the concerned users, I recommend you to delete the faulty accounts from database.

**Comment by tijcolem** [comment]
Thank you for the quick reply. That makes's sense. I applied the update so hopefully the fixes the issue.  Will close. Thanks!
