### ISSUE TITLE
Remove the "custom" type in the task editor

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#3]
The custom subproblem type only allows to create "boxes" in code subproblems.

There should be an interface to do it without editing json code manually.

**Comment by anthonygego** [comment]
I suggest to extract or delete (is it even used somewhere ?) the "custom" problem type from the code base and rely on subproblems instead. This will remove the need for boxes that makes the code problem implementation quite complicated. In case of extraction the boxes code can be put in a plugin.

**Comment by GuillaumeDerval** [comment]
This was a feature of Pythia 1, and if I remember well it was used only by a single exercise which may have been discarded since then.

It allowed to create things like 
```
for(int i = <empty box>; <empty box>; i++) {
    <empty box>
}
```

It can be really useful, but now that INGInious has evolved a lot, it will certainly better fit in a plugin.

**Comment by Drumor** [comment]
This is not relevant anymore
