### ISSUE TITLE
feedback-grade doesn't support variables 

### ISSUE THREAD

**Issue by napsta32** [UCL-INGI/INGInious#303]
When scripting, you can't use an environment variable to the feedback-grade function:

```bash
#!/bin/bash
GRADE=0
[...]
feedback-grade $GRADE
```

You also can't send the grade argument via stdin:
```bash
#!/bin/bash
GRADE=0
[...]
echo $GRADE | feedback-grade
```

**Comment by anthonygego** [comment]
This is more a shell issue. The problem should be somewhere else in your code, as a simple ``run`` file like this will work:

    #!/bin/bash
    SCORE=56
    feedback-grade $SCORE

    if [ "$SCORE" -gt "50" ]
    then
        feedback-result success
    else
        feedback-result failed
    fi

**Comment by napsta32** [comment]
You are right I used an operator that erased my GRADE variable.
