### ISSUE TITLE
Binding to existing LMS suggests wrong student

### ISSUE THREAD

**Issue by ForrestBarnes** [UCL-INGI/INGInious#329]
When binding INGInious to Moodle, the suggested account to bind to is sometimes wrong. Cannot include additional info without compromising student privacy. In my particular environment (CSEL), one flag for this event should be an INGInious account name that does not match the tool identifier.

**Comment by GuillaumeDerval** [comment]
I am sorry I am not sure what is the exact problem here.

Is the problem occurring:
- While binding (for the first time) the LTI user id from Moodle with the INGInious login?
     - In that case, is the problem in the "binding" window that should open outside the LTI window (where you should login with your INGInious account, and then it lists the LTI info) ? Do you mean that the info listed there is wrong? (see screenshot to confirm it's the right page). In that case, which info is wrong?
<img width="875" alt="capture d ecran 2018-06-11 a 09 29 41" src="https://user-images.githubusercontent.com/498483/41218034-1130d7d0-6d5a-11e8-96bb-f1088a581741.png">

- While reconnecting?

**Comment by ForrestBarnes** [comment]
Yes. While binding for the first time, the INGInious account name is the wrong name.

**Comment by GuillaumeDerval** [comment]
INGInious do not "suggest" an INGInious account to bind to. It simply proposes to link the _account the account you are currently connected to_ with the LTI one.

Maybe the student is using a shared computer, on which a real INGInious (not LTI) session is open for another student? In that case, is it possible to log out, and then log in to the right account.

If you are not really not connected to a _true_ INGInious account before binding and that it indicates a wrong username, please tell us. I would be a gigantic bug :O

**Comment by ForrestBarnes** [comment]
I believe it bound the wrong INGInious account to my Moodle. I logged into Moodle on my personal computer (never touched INGInious before), and the INGInious window said something along the lines of "you need to make an INGInious account." I then created an INGInious account. Once I email-confirmed the new INGInious account I went back to Moodle and saw the "Authorization Required" window. I clicked "Bind My Account" without checking the info first (yes, big mistake on my part, but I assumed it would be correct because it only appeared once my INGInious account was confirmed). Now this is the screen I see:
![capture](https://user-images.githubusercontent.com/12518566/41234361-2daaf44c-6d49-11e8-82d5-e99fd07a42b3.PNG)
I don't know who Austin is. It's not me or my instructor, but it might be a past instructor. I went to my INGInious account a day later (today) and there is nothing in My Courses, so I believe that somehow my Moodle was bound to the wrong INGInious account.

I'm not sure if this evidence alone is sufficient for a full investigation, but a classmate of mine had a similar issue, if not the same issue. They found that the INGInious account name was wrong when they attempted to bind Moodle to it. I don't yet know if they were on a personal or shared computer, or if the link was proposed before or after they created an INGInious account. I (or they) will give you more info soon.

**Comment by GuillaumeDerval** [comment]
I strongly believe that everything you see is expected behavior.

First, the « author » that you see should not be you, it is the creator of the task. Probably a previous instructor.

Secondly, the fact you do not see this particular course in the « my courses » section is perfectly normal. LTI courses do not appear for students there, only for instructors.

If I remember well, there is a way to check that your account is bound to LTI in the preferences of your account, at least if your INGInious version is recent enough.

So probably everything is OK; maybe you should double-check with your instructor.

I will close this issue; if you confirm that something is really wrong and is not human error, feel free to reopen this/another issue.
