### ISSUE TITLE
Detect memory outage. 

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#33]
When a submission hits the memory limit on the container, it would be nice to have a distinct error message instead of "failed". 

I do not know if it is possible to detect this.
In particular, some code may end with a sucessful feedback even though some process was killed for its abusive memory consuption.
In any case, this is not an expected scenario.

**Comment by GuillaumeDerval** [comment]
There is no direct solution for this in the Linux, as the OS will (most of the time, except when OOM killer is run) not kill the program consuming too much memory, but instead returning ENOMEM to its system calls.

A post on StackOverflow I found (http://stackoverflow.com/questions/6132333/how-to-detect-out-of-memory-segfaults) suggest to run ```strace -f``` + check dmesg to verify if there was an ENOMEM or if the OOM Killer did something. 

That's definitively something to try if you really need to detect such memory exception, but I also don't think that INGInious should do that automatically: there may be some situations where an ENOMEM is an excepted behaviour, using strace everywhere will probably be really complicated and, as said in the ```man```of ```strace```:  ```A traced process runs slowly.```

**Comment by layus** [comment]
It seems to me that the process does not receive ENOMEM and gets killed when memory usage reaches the limit.

My observations are the same as what is described in http://stackoverflow.com/questions/20096632/limit-memory-on-a-docker-container-doesnt-work#answer-20111960
That is, the process is killed with `Exit 137`.

What most probably happens is that overcommit is allowed within the container, and the process gets killed when it uses too much (already (over)allocated) memory, with no possibility to receive an ENOMEM.
This is better explained in the following link, with the hint that there exists a way to tune overcommit correctly.
http://forum.openvz.org/index.php?t=msg&th=6238&goto=30900&S=c97209f073f9d74379c4712aca4080bf#msg_30900

Kernel documentation is here https://www.kernel.org/doc/Documentation/vm/overcommit-accounting.
More investigations are required to see how this overcommit policy gets applied to docker containers.

**Comment by GuillaumeDerval** [comment]
This implies that most of the time, it is the OOM Killer that kills a process inside a container.
Checking dmesg is probably harmless, and will provide more fine-grained output.

I will probably link this issue with #32 , as a new command for running student's code will probably be created.
