### ISSUE TITLE
INGInious should handle groups of students.

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#34]
When a task is the result of a collaborative work, inginious should provide a way to indicate that.

The main problem with the current implementation is that all the students of a group can submit individually the same deliverable. This is difficult to detect and leads to extra grading work.
It gets even worse when students of the same group submit different deliverables...

This is very important as many projects/assignements are collaborative.

**Comment by GuillaumeDerval** [comment]
Implemented in the Web App in the recents commits from @anthonygego
