### ISSUE TITLE
Grading container hangs with 100 % CPU until timeout after run script is finished

### ISSUE THREAD

**Issue by mabynke** [UCL-INGI/INGInious#343]
In our course, we have a mysterious problem where after the run script has finished, the grading container does not exit, but is stuck at 100 % CPU usage until the task eventually times out. This occurs only sometimes, but for some reason the probability seems to depend on the number of available CPU cores. For the task we are using to test, the time limit is set to 90 seconds. When it works as intended, it takes in the order of 10 s to grade. We have tried setting the time limit to 240 s as well without that fixing the problem, it just takes longer to time out.

On virtual machine A given 2 cores, this happened in 9/15 tries.
On virtual machine A given 4 cores, this happened in 2/15 tries.
On virtual machine B given 2 CPUs, this happened in 7/15 tries.
On virtual machine B given 25 CPUs, this happened in 0/21 tries.
On physical machine C with 6 cores, this happened in 0/40 tries.
Tested on the same task in all cases.

As you can see, giving virtual machine B (our deployment machine) a lot of CPUs seems to be a workaround for us.

If we are quick on the trigger, we are able to enter the grading container, attach to the process and read the output before the run script is done. After the run-file has finished, some more text is usually printed by INGInious followed by a lot of seemingly random characters. When it hangs, however, only some of this is printed. It varies what and how much is printed before it hangs. An example from one run:
```
�type�result2018-08-21 14:19:21,793 - inginious.container - INFO - received intern message {'type': 'done'}
```
When it hangs, CPU usage goes up to 100 % and stays there until timeout.

We are using version 0.4.

**Comment by anthonygego** [comment]
I'm almost pretty sure we fixed such an issue a few months ago, because we had the same issue 100% of the time with one of our config, but I don't remember what was the cause exactly and if the fix was pushed in v0.4 branch. @GuillaumeDerval, @BIG-COW do you remember ?

**Comment by mlhetland** [comment]
Would be

**Comment by GuillaumeDerval** [comment]
This commit fixes it.
https://github.com/UCL-INGI/INGInious/commit/813ffaf1f609dd4dc5d1a4ee35ad667efec669b3
