### ISSUE TITLE
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by kwangkim** [UCL-INGI/INGInious#344]
INGInious works well with a python server, but it did not work well with apache.
(I gave up to install with lighttpd server.)

I got the following error.
```
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 13] Permission denied
```

**Comment by kwangkim** [comment]
I just found the answer from [https://stackoverflow.com/a/45361406](https://stackoverflow.com/a/45361406).

```
sudo /usr/sbin/setsebool -P httpd_can_network_connect 1
```
I think the documentation should contain this.

**Comment by GuillaumeDerval** [comment]
There is currently no documentation on how to use SELinux with INGInious. If you leave SELinux enabled, you will have a number of other issues. 

If you succeed at making it work with INGInious (the difficult part is with the docker containers), please open an issue with your insights :-)
