### ISSUE TITLE
Allow students to save answers without submitting

### ISSUE THREAD

**Issue by mabynke** [UCL-INGI/INGInious#349]
In our course we restrict the number of submissions students can make. However, this means it is impossible for them to save their progress until later – they have to answer all the questions in the task in one go and hope that their network connection, browser or computer doesn't restart their session. See for instance #214. Many of them find this frustrating, and they have my sympathy.

A «save» feature would help our students a lot!

**Comment by Drumor** [comment]
This is done using browser localStorage #479
