### ISSUE TITLE
Task unavailable on agent. Please retry later, the agents should synchronize soon. If the error persists, please contact your course administrator.

### ISSUE THREAD

**Issue by amrondonp** [UCL-INGI/INGInious#352]
Hello, I have been testing INGinious on an environment where the agents are separated from the webapp machine. However, I get this error when trying to make a submission.

`An internal error occurred. Please retry later. If the error persists, send an email to the course administrator. [Submission #5ba2bdd304c9ac09e76ddff9]
Task unavailable on agent. Please retry later, the agents should synchronize soon. If the error persists, please contact your course administrator.`

I am aware that if I copy and paste the task folder from the app to the agent it works.

I have tried to look into the docs to see more about the `agent synchronization` process but I was unable to

How are we expected to manage the synchronization? Is it a command that you have to run periodically? Is it something that you have to do manually on each agent host? Or perhaps there is an additional configuration that I need to check?

Thank you :)

**Comment by anthonygego** [comment]
Hello,

There is no synchronization mechanism for the tasks included in INGInious, because it's a simple filesystem and lots of software already do that very well. You can use any solution (distributed or not) as it can be mounted in your filesystem. Actually an NFS share is probably the simplest solution and will fit to most usages.

**Comment by amrondonp** [comment]
Hello,

I have decided to use sshfs for security proposes. I think this clarification should be in the docs, in the part that you explain how to deploy a remote agent :)

Thanks for the reply
