### ISSUE TITLE
Sendmail interoperability

### ISSUE THREAD

**Issue by bartwojcik** [UCL-INGI/INGInious#360]
Despite this line (web.py docs states that if this is None it will use /usr/sbin/sendmail):
```
smtp_conf = config.get('smtp', None)
```
I am not able to get it to work with msmtp provided sendmail binary. Perhaps it still isn't being set to None? I verified that sendmail command works and permissions are ok. My config has no smtp section (was not even aware it can before trying it with sendmail).

**Comment by anthonygego** [comment]
The webpy mail sending logic is there if you want to debug:

https://github.com/webpy/webpy/blob/90badb20a66a508c437c3774a7d4b947bb907ba3/web/utils.py#L1465-L1507

It seems not to include a default value when fetching the ``smtp_server`` value out of the dictionary, so it may crash it the key does not exist. Maybe we should explicitly set the value to None.

**Comment by anthonygego** [comment]
I'll close this as we have migrated to Flask and the behaviour may have changed. Feel free to re-open an issue if necessary.
