### ISSUE TITLE
Concurrent INGInious instances cause "Internal error. Server restarted"

### ISSUE THREAD

**Issue by amrondonp** [UCL-INGI/INGInious#362]
I have been testing a production instance on out university and the students have been getting "Internal error. Server restarted" pretty consistently. I think I've identified the root cause of the problem.

**Problem** : Submissions are marked as failed with "Internal Error: server restarted" when multiple inginious-webapp instances are run.

**Simplest steps to reproduce**: 
Note: Although this issue appeared on an Apache deployment it can be reproduced easier with the inginious-webapp command.

1. Launch an inginious-webapp instance ``inginious-webapp``
2. Make any submission on any task
3. **While** the submission is running, launch another instance of ``inginous-webapp``. (It does not matter if it cannot be initiated because the port is already in use, we'll still have the behavior) 

Result:
The submission is marked as failed with "Internal error. Server restarted".

**Code involved**: In the app.py module, when the application is started it marks all the pending submissions as failed with "Internal error: Server restarted".

I understand that the logic there is important in the case that the server crashes while a submission is being evaluated. However, in an (default) Apache deployment, it starts and kills worker processes at any time and each worker process is basically an instance of ``inginious-webapp``. As a result, I have measured that around 15% of the students submissions are not evaluated correctly.

I wonder if you guys know a way of configuring apache so that it will prevent this issue while not affecting the concurrency requirements of a production web server deployment.

In other case, IMO we should rethink the logic of marking a submission as failed due to a concurrent server instance being launch while a submission is evaluated, specially if we want to support apache as a production web server for INGInious.

**Comment by GuillaumeDerval** [comment]
The web server seems to start new INGInious instances at random time, which is not the way INGInious expects to run. You should ensure your web server keep instances running between requests :-)
