### ISSUE TITLE
Redirect issue when not using root path for URLs

### ISSUE THREAD

**Issue by mlhetland** [UCL-INGI/INGInious#367]
I'm not sure this is an issue with INGInious – it may very well be my configuration (either of INGInious or of lighttpd) that is faulty…

Anyway: We're trying to run INGInious in the subdirectory `/inginious` on a server. And mostly, this works – and INGInious's own redirects seem to function correctly in all cases but one (that we have identified): `https://‹hostname›/inginious/admin/TDT4120` is redirected to `https://‹hostname›/inginious/inginious/admin/TDT4120/settings`, rather than `https://‹hostname›/inginious/admin/TDT4120/settings`.

From what I can tell, the INGInious source for this redirect is no different from others; it redirects to
```
self.app.get_homepath() + '/admin/{}/settings'.format(courseid)
```
Given that things generally work (and `get_hoomepath` is used all over the place), I'd think this was the right URL. I guess it *might* be my attempt at adjusting the rewrite rules for lighttpd. There I have:
```
"REAL_SCRIPT_NAME" => "/inginious"
url.rewrite-once = (
    "^/inginious/favicon.ico$" => "/static/icons/favicon.ico",
    "^/inginious/static/(.*)$" => "/static/$1",
    "^/inginious/(.*)$" => "/inginious-webapp/$1"
)
```
I'm not sure I quite get what the INGInious docs say about `REAL_SCRIPT_NAME` (which, in the ordinary setup, is empty):
>The `REAL_SCRIPT_NAME` environment variable must be specified under lighttpd if you plan to access the application from another path than the specified one. In this case, lighttpd forces to set a non-root path `/inginious-webapp`, while a root access if wanted, in order to serve static files correctly. Therefore, this environment variable is set to an empty string in addition to the rewrite rule.

Now, if I set `REAL_SCRIPT_NAME` to empty, things don't work; with the current setup, it seems to work in general, but not for this one redirect. Any ideas? Am I just borking the config, here?

**Comment by mlhetland** [comment]
As a practical solution, I added the following to `url.redirect` in the lighttpd configuration:
```
"^/inginious-webapp/inginious/admin/TDT4120/settings$" => "/inginious/admin/TDT4120/settings",
"^/inginious-webapp/inginious/admin/TDT4120/tasks$" => "/inginious/admin/TDT4120/tasks"
```

**Comment by anthonygego** [comment]
This is probably not the only redirect that won't work. I think you'll have problems with all the ``web.seeother`` calls in the code.

There's been a while since we stopped using lighttpd, but it seems from the time we launched the v0.4 LTI app separately on a ``/lti/`` subpath we did not specify the ``REAL_SCRIPT_NAME`` at all for the LTI app. I'm not quite sure therefore if the default value was the path specified as the fastcgi entry.

Here's what our config looked like:

    fastcgi.server = ( 
      "/webapp" =>
        (( "socket" => "/path/to/inginious-webapp.fastcgi.socket",
           "bin-path" => "/path/to/inginious-webapp",
           "max-procs" => 1,
           "bin-environment" => (
               "INGINIOUS_WEBAPP_HOST" => "0.0.0.0",
               "INGINIOUS_WEBAPP_PORT" => "443",
               "REAL_SCRIPT_NAME" => "",
               "INGINIOUS_WEBAPP_CONFIG" => "/path/to/configuration.yaml"
           ),
           "check-local" => "disable"
        )),
      "/lti" =>
        (( "socket" => "/path/to/inginious-lti.fastcgi.socket",
           "bin-path" => "/path/to/inginious-lti",
           "max-procs" => 1,
           "bin-environment" => (
               "INGINIOUS_LTI_HOST" => "0.0.0.0",
               "INGINIOUS_LTI_PORT" => "443",
               "INGINIOUS_LTI_CONFIG" => "/path/to/configuration.lti.yaml"
           ),
           "check-local" => "disable"
        ))
     )

    $SERVER["socket"] == ":443" {
      ssl.engine  = "enable",
      ssl.pemfile = "/etc/letsencrypt/live/{{ domain_name }}/ssl.pem",
      ssl.ca-file =  "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem",

      url.rewrite-once = (
          "^/favicon.ico$" => "/static/common/icons/favicon.ico",
          "^/.well-known/(.*)$" => "/.well-known/$1",
          "^/lti/static/(.*)$" => "/static/$1",
          "^/lti/(.*)$" => "/lti/$1",
          "^/static/(.*)$" => "/static/$1",
          "^(.*)$" => "/webapp/$1"
      )

    }

    $SERVER["socket"] == ":80" {
      $HTTP["host"] =~ ".*" {
        url.redirect = (".*" => "https://%0$0")
      }
    }

Therefore I'd say you need to specify ``"/inginious" =>`` as the ``fastcgi`` entry and not ``"inginious-webapp" =>``, without ``REAL_SCRIPT_NAME`` and that you probably don't need  the last rewrite rule. But maybe I'm wrong.

**Comment by mlhetland** [comment]
Hmm. I didn't manage to make that work. I generalized the redirect to
```
"^/inginious-webapp/inginious/(.*)$" => "/inginious/$1"
```
to repair the damage more generally, but it does indeed seem like going back and forth, given that there are rewrites going in the other direction. I guess I'll have to have another look at your version, to see what's not working in my adaptation of it.

**Comment by mlhetland** [comment]
Well, if I rename it to simply `/inginious`, I no longer need the rewrite
```
"^/inginious/(.*)$" => "/inginious-webapp/$1"
```
But for some reason, it just gives me 404s if I don't set `REAL_SCRIPT_NAME` to `"/inginious"`. And if I do, I get the redirect issues again. The “solution“ after this renaming is just
```
"^/inginious/inginious/(.*)$" => "/inginious/$1"
```
I guess I should look in  some look somewhere, and figure out what INGInious is actually looking for when it gives me the 404…

**Comment by anthonygego** [comment]
I'll close this as I dont know if it is still relevant with Flask. It will probably be linked to #707 now.
