### ISSUE TITLE
Functionality for displaying solutions?

### ISSUE THREAD

**Issue by mlhetland** [UCL-INGI/INGInious#368]
In my course, we've migrated from an in-house system, and there are a few things that we're missing from that … among them is the ability to show the students solutions after the deadline has passed. For the default INGInious MC module, that doesn't make much sense, as it requires 100%, but for code, it probably would. For our part, we also have custom grading of MC questions, that accepts a certain percentage, and displaying solutions would make sense even there, for us.

The question is whether (1) such a functionality is already easily available somehow, (2) whether it would be worth adding in general, or (3) whether we should simply implement a custom solution/plugin. It might be enough to display static contents for this (e.g., a PDF file, for that matter), as long as its accessibility is time-dependent.

**Comment by anthonygego** [comment]
Currently there's an additional reStructuredText directive ``hidden-until`` which displays a box informing the students a partial feedback will be available from the date given in argument. ``%Y-%m-%d`` and ``%d/%m/%Y`` date formats are supported, possibly followed by a 24-hour time string.

The following :

    .. hidden-until:: 2018-11-02 14:00

        A temporarily hidden feedback

should display the message only after 2018-11-02 14:00.

You can put there any RST text and if you want a link to a PDF (knowing that your link will be public once the deadline reached)... Feel free to suggest any improvement that could be made.

**Comment by anthonygego** [comment]
When you set a time interval, the exercise is still visible but students can't submit new answers anymore. Previously hidden feedback can be shown by clickling on the submission in the history.

**Comment by mlhetland** [comment]
A followup on the above: An ideal solution for us, I think, would be if it were possible to separate the deadline from the availability interval. I.e., the text of the exercise could be available after the deadline, but you could no longer have it accepted.

A bonus would be if you could still submit your exercises and see if you got it right (just for training purposes), but not get any points. The latter solution we could bake into our scoring functionality, if course, but that has the drawback of requiring a custom deadline variable, which would not display as the deadline in the margin, and which could not be specified in the web interface.

**Comment by mlhetland** [comment]
Oh, I was writing my message just as you were writing yours! Sorry about that :-)

Ah, I see. This seems to be what we need, then. I had just seen the «task hidden to students» part, and missed that that wasn't there after the deadline! Thanks :-)

(The second point about permitting trial submissions without getting points might still be useful, but I guess that's a different feature.)
