### ISSUE TITLE
Login not logging in – until browser restart

### ISSUE THREAD

**Issue by mlhetland** [UCL-INGI/INGInious#370]
Though logging in mostly works fine, sometimes users simply end up not logged in after entering their username/password. Quitting the browser, restarting it and then trying again fixes the problem.

(Caveat: I guess this *might* be related to the not 100% standard setup mentioned in #367, though I believe we saw this issue before we introduced that. Only seen in 0.5, not 0.4.)

**Comment by GuillaumeDerval** [comment]
We cannot reproduce sadly

**Comment by GuillaumeDerval** [comment]
This should be fixed by now. Please let me know if that's not the case.
