### ISSUE TITLE
Feature request: Default value for multiple-choice question

### ISSUE THREAD

**Issue by mmoelle1** [UCL-INGI/INGInious#371]
I use INGInious for a C++ programming class not just for grading the students' answers, but as web-based code development system in classroom. Demos and assignments all follow the layout shown in the figure below:

![screen shot 2018-11-14 at 19 22 52](https://user-images.githubusercontent.com/1992611/48504180-6bdf0c00-e844-11e8-843b-5e3e58ece94c.png)

I make use of the multiple choice question to let students define the C++ standard that should be used to compile the code and a single-line answer to pass command line arguments. This is all handled internally by an adapted `run` script.

Could you please add the possibility to provide a default value for multiple choice questions.

**Comment by anthonygego** [comment]
This is a really specific use case, and should probably be addressed via a plugin.
