### ISSUE TITLE
Plans to make Singularity an alternative to Docker?

### ISSUE THREAD

**Issue by mmoelle1** [UCL-INGI/INGInious#372]
Are there any plans to make ``Singularity`` (https://www.sylabs.io/docs/) an alternative to ``Docker``?

Conversion of a ``Dockerfile`` to a ``Singularity`` image works. The only problem, at first glance, is the file ``/usr/bin/INGInious`` which can only be run by `root` due to the setting
```
-rwx------ 1 root root 16481 Oct 25 16:46 /usr/bin/INGInious
```
Under ``Docker`` this does not seem to cause any problems. The so-created ``Singularity`` image starts fine but yields the following error when run as ``non-root`` user (for obvious reasons):
```
bash: /usr/bin/INGInious: Permission denied
```

I wonder if there is any interest in supporting ``Singularity`` as an alternative to ``Docker`` since it does not need to be run as ``root``, which might be welcomed by many system administrators.

**Comment by anthonygego** [comment]
I'll close this. We'll investigate migrating to podman in the future.
