### ISSUE TITLE
Feedback background color

### ISSUE THREAD

**Issue by ogoletti** [UCL-INGI/INGInious#380]
As displayed on the screenshot attached, the feedback background color is to dark (green/red). 
It seems that it's overriden in the boostrap css. 
![capture d ecran 2018-12-03 a 17 09 38](https://user-images.githubusercontent.com/22364279/49506645-dbae4880-f87e-11e8-9ee6-c6e6601bc0ec.png)
I tried to modify the file but it seems that it's generated.

**Comment by GuillaumeDerval** [comment]
This is as intended, it's the bootswatch style we have.
