### ISSUE TITLE
Google OAuth Login Failure

### ISSUE THREAD

**Issue by bshouse** [UCL-INGI/INGInious#408]
OAuth logins stopped working in an otherwise steady-state installation of INGInious. We started to see the following message in the logs.

```
pid: 20266|app: 0|req: 335117/356532]  () {32 vars in 838 bytes} [Tue May 14 12:05:43 2019] GET  => generated 0 bytes in 9 msecs ( 303) 2 headers in 139 bytes (2 switches on core 0)
Traceback (most recent call last):
  File "/home/inginious/.local/lib/python3.5/site-packages/web/application.py", line 257, in process
    return self.handle()
  File "/home/inginious/.local/lib/python3.5/site-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/inginious/.local/lib/python3.5/site-packages/inginious/frontend/cookieless_app.py", line 92, in _delegate
    return super(CookieLessCompatibleApplication, self)._delegate(f, fvars, args[1:])
  File "/home/inginious/.local/lib/python3.5/site-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/home/inginious/.local/lib/python3.5/site-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/home/inginious/.local/lib/python3.5/site-packages/inginious/frontend/pages/social.py", line 59, in GET
    return self.process_callback(auth_id)
  File "/home/inginious/.local/lib/python3.5/site-packages/inginious/frontend/pages/social.py", line 42, in process_callback
    user = auth_method.callback(auth_storage)
  File "/home/inginious/.local/lib/python3.5/site-packages/inginious/frontend/plugins/auth/google_auth.py", line 35, in callback
    google = OAuth2Session(self._client_id, state=auth_storage["oauth_state"],
KeyError: 'oauth_state'
```

It appears that the oauth_state key is not set in auth_storage. I tried the following items, but it had no effect on the problem.
1. A new OAuth ID & Secret
2. Updated to the latest version of INGInious
3. Tried use both old and new OAuth ID & Secret on new version

I also compared the OAuth process on INGInious with another OAuth application. The only real difference I noticed is that INGInious's GooglAuthMethod return HTTP code 303 while the other returns 302. I am not sure if it has any impact, but otherwise, the workflows match.

Any ideas what may be causing the OAuth failure and how I can debug or resolve it?

Thank you.

**Comment by dirkcgrunwald** [comment]
I think this is fixed by PR #409 (our Colorado inginious is now authenticating)

**Comment by anthonygego** [comment]
This case seems to be different. The ``auth_storage`` dictionary is stored in the session, so once the authorization link has been returned the ``oauth_state`` state should be set and should remain available when the callback is done. It seems you're using a new session here.

Are you able to open an INGInious session in another way (via password for instance) ? If not, maybe you can look if there is something that prevent cookies to work correctly in your browser. This is typically the case if the website is located in an iframe.

**Comment by dirkcgrunwald** [comment]
No, there's no iframe -- just going to https://inginious.csel.io and using the login via google. The Google documentation in the PR indicates that the "openid" scope is required; adding that fixes the error.

**Comment by anthonygego** [comment]
This is weird because a missing scope should not result in a missing key in the dictionary. This would mean that the authorization link generation have failed and so there would never be any callback...

**Comment by anthonygego** [comment]
I'll close this. Feel free to re-open it if this is still relevant.
