### ISSUE TITLE
Use cards rather than alerts for submission with feedback

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#419]
I just drop this here, waiting for approval, before actually coding it.

I find that the current situation (using alerts for displaying feedback) is making the feedback difficult to read. See this example:

<img width="1195" alt="Capture d’écran 2019-08-02 à 17 25 21" src="https://user-images.githubusercontent.com/498483/62380909-8f6cf280-b54a-11e9-81ee-3f5c83297b73.png">

I would propose that instead of using a bootstrap "alert", we use instead a bootstrap card. Here is a screenshot of what it would look like:

<img width="1197" alt="Capture d’écran 2019-08-02 à 17 26 25" src="https://user-images.githubusercontent.com/498483/62380955-add2ee00-b54a-11e9-8cd7-d61835f06c8c.png">

Here is the code used to produce this:
```html
<div class="card border-danger">
    <div class="card-header bg-danger text-white">
        There are some errors in your answer. [...]
        <button type="button" class="close" data-dismiss="alert" style="color: white;"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    </div>
    <div class="card-body">
        <!-- table here -->
     </div>
</div>
```

### Demo success
<img width="1199" alt="Capture d’écran 2019-08-02 à 17 30 17" src="https://user-images.githubusercontent.com/498483/62381236-52edc680-b54b-11e9-886d-6cda2431fa42.png">

### Demo timeout/other warning
<img width="1199" alt="Capture d’écran 2019-08-02 à 17 30 51" src="https://user-images.githubusercontent.com/498483/62381232-508b6c80-b54b-11e9-9c8b-72915abaf0ae.png">

**Comment by anthonygego** [comment]
Approved

**Comment by Drumor** [comment]
Yeah it's easier to read!
