### ISSUE TITLE
ACL feature

### ISSUE THREAD

**Issue by mcanini** [UCL-INGI/INGInious#42]
I'd like to be able to specify which users are allowed to view and submit tasks for my course.
Ideally, I would like to do it by dropping a CSV file into my course git repository. The format of the CSV file is the one I download from the faculty.

This is the file format:
(Skip the first line, e.g. "LINGI2347 en 2014")
Pgrm,Num fac,Nom,Prénom,Noma,Mail,...

The # of columns can vary but the above ones are fixed.

I think from Noma and email address you can recognize a valid UCL / INGI username.

Thanks for implementing this!

**Comment by layus** [comment]
+:100:! This would be a most useful feature.

If I understood well, this is difficult because authentication is based on logins, which is the only column not provided by the csv ?

**Comment by mcanini** [comment]
I don't think it is difficult. But you need to have a way to figure out the correct mapping using an authoritative source.

**Comment by GuillaumeDerval** [comment]
The verification by NOMA will not be possible directly:

* INGInious uses LDAP to check user credentials; however, the NOMA does not seem to be stored on the INGI LDAP server, and the UCL one does not give the information too.
* NOMA is a "UCL-only" feature; we try to keep INGInious agnostic and filtering by NOMA would break this.

However, it seems possible to filter:
* by login
* by email
Easily :-)

**Comment by GuillaumeDerval** [comment]
This will be available soon on our instance of INGInious in INGI.


(:tada: closed issue 42! :tada:)
