### ISSUE TITLE
Inginious-autotest : Container default / java8scala is made for an old/newer version of the docker agent (container version is None, but it should be 2). INGInious will ignore the container.

### ISSUE THREAD

**Issue by jy95** [UCL-INGI/INGInious#448]
As seen in this [log](https://travis-ci.com/UCL-INGI/LEPL1402/builds/130493734#L675), it seems the following containers aren't updated with the [new check](https://github.com/UCL-INGI/INGInious/blob/master/inginious/agent/docker_agent/_docker_interface.py#L48) : 

- [default](https://github.com/UCL-INGI/INGInious/tree/master/base-containers/default) 
- [java8scala ](https://github.com/UCL-INGI/INGInious-containers/tree/master/grading/java8scala)

As [it](https://github.com/UCL-INGI/INGInious/blob/master/inginious-autotest#L133) must be present for  inginious-autotest , no integration testing is possible with the latest version 👎

**Comment by GuillaumeDerval** [comment]
If you docker pull them, it downloads the v0.5 version, which is (obviously) outdated wrt the master branch. Please build them yourself for now if you need them ;-)

**Comment by jy95** [comment]
Currently, I use a fork.
This issue is just there to notify you to not forget to update the containers ^^
As we can see, for 2 tasks, there is a return of the WEB TASK ERROR bug "type object 'Tag' has no attribute 'check_format'"
