### ISSUE TITLE
Limit amount of submissions

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#48]
Currently, INGIinious lacks any smart way to limit the number of submissions.

There are many ways to do that. I think of
1. Hard limit (max. X submission(s), maybe exists ?)
2. Soft limit (after X submissions, points start to decrease)
3. Cooling-off period (must wait X minutes after a submission to be allowed to resubmit)
4. Token bucket (coolong-off with some burstiness allowed; corresponds to the idea of max X submissions per period T).

From an educational point of view, 2 is used in coursera, but it is 3 (or its improved version 4) that I like the most.
This would prevent excessive load on the server, and provide a slight bonus to students that start working early on the assignment.

The main goal of this improvement is to avoid students using INGInious as a debugger ;-)

**Comment by GuillaumeDerval** [comment]
I'm strongly against solutions 1 and 2 (because the server can have problems, grading scripts could have bugs...) (and as a student ;-) ), but I'm open to solutions 3 and 4.

I will probably try to implement the third one.

**Comment by layus** [comment]
After some maturation, it seems to me that a token bucket is perfect.

Example: Students start with a bucket of 0 tokens.
Every half day, a new token is added to the bucket, up to a maximum of six.
When a submission is made, a token is removed from the bucket.

This is much better than the cooling-off period because you are not necessarily blocked when you make stupid error (wrong file upload, typo, etc.) and it keeps the nice property of favoring early submitters.

An approximation of this algorithm is to allow up to six submissions on the last three days. This is not as nice, but is much easier to implement (remaining = 6 - #non_cancelled_submissions_since(now() - 3days)).

**Comment by layus** [comment]
I would like to see some rate-limiting scheme implemented in INGInious before the end of october. 
I have looked in the code, and it seems to me that it boils down to one configuration option (say, "cooldown") and some code like 

```diff
diff --git a/inginious/frontend/webapp/pages/tasks.py b/inginious/frontend/webapp/pages/tasks.py
index 9b7e69c..714870f 100644
--- a/inginious/frontend/webapp/pages/tasks.py
+++ b/inginious/frontend/webapp/pages/tasks.py
@@ -24,6 +24,8 @@ import os
 import posixpath
 import urllib
 
+from datetime import datetime, timedelta
+
 import web
 
 from inginious.frontend.common.task_page_helpers import submission_to_json, list_multiple_multiple_choices_and_files
@@ -105,6 +107,11 @@ class TaskPage(INGIniousPage):
                     if not self.user_manager.task_can_user_submit(task, username):
                         return json.dumps({"status": "error", "text": "You are not allowed to submit for this task."})
 
+                    submissions = self.submission_manager.get_user_submissions(task)
+                    last_submission_time = max(datetime(s["submitted_on"]) for s in submissions))
+                    if last_submission_time > datetime.now() - timedelta(hours = 1):
+                        return json.dumps({"status": "error", "text": "You have exhausted all your attemps. Wait until a new submission is allowed."})
+
                     # Reparse user input with array for multiple choices
                     init_var = list_multiple_multiple_choices_and_files(task)
                     userinput = task.adapt_input_for_backend(web.input(**init_var))
```

Of course, this could be improved by ignoring cancelled submissions and submissions with internal INGInious errors.

Do you think it is feasible for the end of the month ?

**Comment by GuillaumeDerval** [comment]
I will work on that this week :-)

**Comment by layus** [comment]
\o/

**Comment by layus** [comment]
This bug would look more serious if we removed the Critical tag :-).

**Comment by GuillaumeDerval** [comment]
Still critical, still no time to do it.
We are currently determining on what we will work this July, I will _probably_ spend some time on that.
