### ISSUE TITLE
webdav vs webapp

### ISSUE THREAD

**Issue by ThaSami** [UCL-INGI/INGInious#486]
we are using lighttpd on ubuntu server
however i've come to make a decision between webdav / webapp 
inginious will be handling 100-200 students at the same time. so shall we give them access to webdav or webapp ? docker and mongodb are running locally.

**Comment by Drumor** [comment]
Hello,

Pay attention that webdav is only for task files (administration part). Your students cant submit via the webdav.
For your purpose, the webapp is good enough.
