### ISSUE TITLE
Email Access List is Case Sensitive

### ISSUE THREAD

**Issue by ThaSami** [UCL-INGI/INGInious#512]
for example if i register using the email sami@GMAIL.com
but i put in my access list for a specific course: sami@gmail.com
**the two emails won't match!**
if it happens a student is using an upper case letter .. he wont be able to register.

**Comment by davidhbrown** [comment]
Just a comment that, while unusual, it is technically possible for the local part of an email address (before the @) to be case-sensitive: [https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive](https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive)

Normalizing the host/domain part (after the @, probably to lowercase) could be a good convenience for exactly the reason you suggest.
