### ISSUE TITLE
Allow to use network (access outside the container) using a specific conf

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#53]
For now, we have always disabled the network in the containers, because it rans untrusted scripts made by teachers AND students.

The new backend (#36) now separates clearly the grading part (that runs scripts made by a teacher or its assistants) from the student part (that runs scripts made by students).

I intended to make the network available by default in every grading container, and to disable it by default in student container; however, it breaks compatibility with old-style tasks (not using ```run_student```). So network is still disabled.

There should be a way to enable network in each container. Steps:

- Add a configuration option in the ```task.yaml``` (for the grading container **only**) (default: false)
- Modify the studio to take care of the new option
- Modify the backend/agent to allow to start the grading container with/without the network, depending on the option
- Modify ```run_student``` to accept the new option for the student containers
- Modify the agent to take care of that option too.

**Comment by layus** [comment]
I do not (yet) understand why you would want network access. It looks like opening the pandora box :-)
Do you have good use cases that require network access ?
Who would use this ?

**Comment by GuillaumeDerval** [comment]
The goal is (primarily) to allow to open network access for **grading** containers, the ones that runs scripts made by the teachers/assistants (so, considered as "semi-trusted").

For example, @jey1401 asked me once if it was possible to download additional dependencies for R code made by students: student would send their code to INGInious, with a list of dependency to install, and these dependencies would be installed by the grading container on the student container (in a safe way), allowing to test more advanced code while giving some liberty to the students.

**Comment by layus** [comment]
Ok, this makes sense to me.
