### ISSUE TITLE
Number of students

### ISSUE THREAD

**Issue by ogoletti** [UCL-INGI/INGInious#534]
It would be nice to be able to retrieve easily the number of students subscribed to a specific course. 
Either in the `/stats` page or at the top of the `/students` page ?

**Comment by kimmens** [comment]
> It would be nice to be able to retrieve easily the number of students subscribed to a specific course. Either in the `/stats` page or at the top of the `/students` page ?
I second the need for this issue.

**Comment by Drumor** [comment]
busy with ;-)

**Comment by GuillaumeDerval** [comment]
Apparently @Drumor solved the issue but didn't close it :D

**Comment by ogoletti** [comment]
It's done here btw : admin/COURSID/students
