### ISSUE TITLE
Clean install doesn't work

### ISSUE THREAD

**Issue by Sphincz** [UCL-INGI/INGInious#545]
Hi all,
I tried to install inginious on my own server, clean install, and tutorial doesnt work,

When executing taskts, It shows the error message for every environment:
_The grader did not return a readable output : 'NoneType' object has no attribute 'items'_

Before, I tried to build the base container with Dockerfile, change package versions, change containers, every other option, and it still fails. And now, new server, clean, and it doesnt work.

The installation is somehow broken.

Can someone help me? Thank you!

**Comment by GuillaumeDerval** [comment]
I think you are using msgpack 1.0.0 with INGInious v0.6.

You can either rebuild the containers with the fix here (we should put it in the v0.6 branch when we have time) https://github.com/UCL-INGI/INGInious/commit/f0a4da6d095781d964de0847a46eaf505697f0bb
or force an install of msgpack < 1.0.0 in your local python env, and it should work.

**Comment by GuillaumeDerval** [comment]
I assume this is solved? Please add a comment here if that's not the case ;-)
