### ISSUE TITLE
execution of 'Constant' statements is denied

### ISSUE THREAD

**Issue by AtakanDonmez** [UCL-INGI/INGInious#562]
Hi all,

I have followed the Installation and deployment guide to set up INGinious with local backend/agent on my Ubuntu VM on Virtual Box. Evertyhing seems to be working fine up until then. However after I see the message  `inginious.client - INFO - Updated containers` and try to go to localhost I get the error `/usr/local/lib/python3.8/dist-packages/inginious/frontend/templates/index.html:x - execution of 'Constant' statements is denied` from line x goes from 6 to 85. 

About a month ago a similar issue was opened in which the proposed solution was to install an msgpack with version < 1.0.0 however since then the change that requires INGinious to run with msgpack 1.0.0 has been made thus when I try to  download msgpack, for example, 0.6.2 the system doesn't let me and points out to INGinous requirement for 1.0.0.

Let me know if I need to provide more info.
Thank you for the tool and wishing you healthy days!

**Comment by anthonygego** [comment]
We had to fix ``web.py`` dependency to version ``0.40`` as there are some issues with form posting in the later releases. This version do not support python38. I strongly recommend you to use a python36 or python37 virtual environment for the moment.

**Comment by AtakanDonmez** [comment]
Reinstalling INGInious with python 3.6 virtual environment solved the issue thank you!
