### ISSUE TITLE
Bug - Tasks list not displayed in course administration

### ISSUE THREAD

**Issue by vvandenschrieck** [UCL-INGI/INGInious#566]
Hello the Inginious Team!  

I've updated my inginious instance to the last version yesterday, and it seems that the tasks list page in course administration is not working properly since then : Tasks are not shown (see screenshot below), and the new "add section" button does nothing. 
<img width="1418" alt="Capture d’écran 2020-09-10 à 11 55 35" src="https://user-images.githubusercontent.com/1985444/92714685-cd973100-f35c-11ea-85ed-8de2798c4a5e.png">

Tasks are still correctly displayed on the main page of the course.  Maybe there have been some changes in the task.yaml or course.yaml files related to the new section feature?  Or changes in the database?

**Comment by anthonygego** [comment]
The task list is now defined at the course side. The correct minified javacript was recently (a few days ago) pushed. ipe you cache and check that you do not have any javascript error in your console. If you still have issue, disable the minified js to see if something changes.

**Comment by vvandenschrieck** [comment]
Cache wiped, but still the same error in the console : 
Sortable: `el` must be an HTMLElement, not [object Undefined] (all-minified.js : 3087)

How can I disable the minified js?

**Comment by anthonygego** [comment]
``use_minified_js: false`` in the ``configuration.yaml`` file.

**Comment by vvandenschrieck** [comment]
Done! But still not working, same error in console but from JQuery this time : 

<img width="1226" alt="Capture d’écran 2020-09-11 à 10 13 47" src="https://user-images.githubusercontent.com/1985444/92890917-d567db80-f417-11ea-8dda-e6864b7179d2.png">

**Comment by pchaow** [comment]
I solved by make more indent in its template

https://github.com/UCL-INGI/INGInious/issues/585

**Comment by vvandenschrieck** [comment]
Thanks @pchaow, working perfectly now!
