### ISSUE TITLE
Bug - run_student_simple returns empty string with default grading environment

### ISSUE THREAD

**Issue by vvandenschrieck** [UCL-INGI/INGInious#567]
So, i've updated my inginious instance yesterday, and I have troubles with run_student which does not returns the output of the command.  

I used the [LTEST0000] test course to see if the issue was in my scripts or not, and indeed, the python "Hello World" task is not running correctly anymore : 

<img width="1055" alt="Capture d’écran 2020-09-10 à 14 39 16" src="https://user-images.githubusercontent.com/1985444/92730205-b879cc80-f373-11ea-9119-5ffbcf37e981.png">

I suspect that the issue may come from the default container, as my old Java problems are still running as expected.

**Comment by vvandenschrieck** [comment]
Ok I just changed the grading environment for the Hello World task, using Java7 instead of the default one, and it's working properly now.  This confirms what I thought about the issue being in the default container :-).

**Comment by pchaow** [comment]
I've same problem with you even using Java7 in environemnt.
I've log in into the docker and try execute run_student in bash and nothing come out.

**Comment by vvandenschrieck** [comment]
Actually, following one container update, i've lost my Java7 environment so... no way to circumvent the issue anymore :-/

**Comment by GuillaumeDerval** [comment]
This is apparently a problem in the build of the images on docker hub. It's not a problem with the code, but rather with the build infrastructure. We are looking into this; in the meantime, you can build the images locally:
```
# in the inginious repo
cd base-containers
cd base
docker -t ingi/inginious-c-base .
cd ../default
docker -t ingi/inginious-c-default .
# in the directory of your specialized container, eg INGInious-containers/grading/java7
docker -t ingi/inginious-c-java7
```.

**Comment by vvandenschrieck** [comment]
Thanks a lot @GuillaumeDerval, the local build solves the "Hello World" issue! :-).
