### ISSUE TITLE
Bug - <class 'KeyError'> at /auth/callback/uclouvain

### ISSUE THREAD

**Issue by jy95** [UCL-INGI/INGInious#575]
Hello,

It seems this [line](https://github.com/UCL-INGI/INGInious/blob/master/inginious/frontend/plugins/auth/saml2_auth.py#L86) needs additional check (like `"redir_url" in auth_storage`) as I rarely got this when sign in : 

[Moderated]

**Comment by anthonygego** [comment]
I'll have a deeper look into that because this should actually never happen.

**Comment by jy95** [comment]
As I said, It seems to be rare - Now I got this screen when this case occurs : 

![image](https://user-images.githubusercontent.com/9306961/95591780-0b64a380-0a48-11eb-95ce-315230a2a5cb.png)

**Comment by anthonygego** [comment]
This is actually not fixed yet.

**Comment by anthonygego** [comment]
PR #595 changed nothing...
