### ISSUE TITLE
Interface (not that) responsive

### ISSUE THREAD

**Issue by ogoletti** [UCL-INGI/INGInious#587]
When resizing Inginious window, a lot of templates seem non optimized. 
Also, the admin panel could collapse or be minimized to allow for more space. 
Some screenshots to illustrate on a half 1920*1080 screen
![Screenshot 2020-11-05 at 12 15 05](https://user-images.githubusercontent.com/22364279/98234520-df621280-1f60-11eb-9454-3a6f44ac43a7.png)
![Screenshot 2020-11-05 at 12 16 38](https://user-images.githubusercontent.com/22364279/98234530-e2f59980-1f60-11eb-98da-45637848e464.png)

**Comment by GuillaumeDerval** [comment]
Fixed by #589
