### ISSUE TITLE
Check that feedback is actually a string on submission

### ISSUE THREAD

**Issue by jadinm** [UCL-INGI/INGInious#601]
A faulty grading script can set a list instead of a string for feedback. For instance with the following code:

```python
feedback.set_problem_feedback(["a", "problematic", "feedback"], "problem-id")
```
Student submissions made with this grading script cannot be viewed later on. The web interface produces the following stacktrace instead of showing the submission:

![Screenshot_2020-11-25  class 'AttributeError' at submission](https://user-images.githubusercontent.com/4190063/100261973-cfc85f00-2f4b-11eb-9cd0-e6c7101df5aa.png)

Of course, the grading script could have been correct in the first place but that would be cool to have a standard "Internal error" and to be able to visualize the student code instead of a stack trace :)

**Comment by Drumor** [comment]
Solved by #603
