### ISSUE TITLE
Feature Request :  youtube embed in restructure text

### ISSUE THREAD

**Issue by pchaow** [UCL-INGI/INGInious#606]
Can we integrate Youtube embed  restructure directive to problem context?

Youtube Directive can be found at : 
https://gist.github.com/dbrgn/2922648

**Comment by GuillaumeDerval** [comment]
Hello!

You can insert HTML directly in rst, using the following structure:

```
    .. raw:: html
    
        <insert youtube iframe here>
``` 

You can obtain the youtube iframe code by clicking on the "integrate" button in the share box of youtube :-)

**Comment by pchaow** [comment]
Thanks @GuillaumeDerval
