### ISSUE TITLE
[idea] Test the final installation.

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#61]
It would be nice to add tests on the final installation.

These could ensure that
* docker is reachable and up to date
* the tasks folder exists (and is non empty ?)
* some test task can be executed correctly

This would allow users to be reasonably sure that they did not
* forgot to install python packages
* misconfigured some important value
* forgot to install some plugin (a missing json plugin can be very annoying)

More generally, the test suite could be generalized to run locally.
For this to work, we need to be sure that the tests cannot corrupt the current installation.

**Comment by GuillaumeDerval** [comment]
Having a real "frontend installer" (like wordpress for example, but of course in a simpler version) is something I really want to do.

From what I remember, the tests are running on a separate DB, and as INGInious is r-o on task files (if you do not touch at the studio), it should be ok.
