### ISSUE TITLE
How do students register to courses?

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#630]
Apologies for the simple question - I could not find it in the documentation.

How does a student register to a course? Can he just register independently, or should I (the instructor) register each individual student?

I read the [teacher documentation](https://inginious.readthedocs.io/en/latest/teacher_documentation.html) but did not find this information.

**Comment by Drumor** [comment]
Hello @erelsgl,

Depending on how you set your course registration, the students may register independently. You can also set a password on the course or work with an ACL.

**Comment by anthonygego** [comment]
If you have deployed version v0.6, they have a dialog on the bottom of their course list to register. Now registration is done via the course page. Administrators are currently not considered as students and don't see these options.
