### ISSUE TITLE
Who should create the tasks, backup, download and temporary folders?

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#633]
The [installation guide](https://inginious.readthedocs.io/en/latest/install_doc/installation.html) says (in the Web Server part):

```
Create a folder for INGInious, for example /var/www/INGInious... Put your configuration file in that folder, as well as your tasks, backup, download, and temporary (if local backend) directories (see Configuring INGInious for more details on these folders).
```

I understand that the configuration file is the file `configuration.yaml` generated by the `inginious-install` script.  What about the other directories - should I create them myself? 

The directories for "tasks" and "backup" was mentioned during configuration - the default was "." but I chose a different option and created these directories myself. What about the other two - "temporary" and "download" - what are they and how should I create / name them?

**Comment by anthonygego** [comment]
They are not used anymore, don't worry. I keep the issue opened not to forget to update this.

**Comment by anthonygego** [comment]
I suggest to merge this with #646
