### ISSUE TITLE
Execution of "Constant" statement is denied

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#634]
I re-installed INGInious on a fresh server (Ubuntu 20.04 with Apache2). When I open the main page, the URL changes to "http://ip.address/courselist", I get "500 Internal Server Error", and the `error.log` shows:

```
[Sat Feb 20 22:27:04.123436 2021] [wsgi:error] [pid 35233:tid 140378934052608] [client 93.172.119.50:50580] /usr/local/lib/python3.8/dist-packages/inginious/frontend/templates/internalerror.html:85 - execution of 'Constant' statements is denied
```

**Comment by anthonygego** [comment]
web.py, the web framework on which the code relies, is no longer (actively ?) maintained and has accumulated a lot of issues with time. You can update it to run the app on recent Python versions but you won't be able to send big forms as there is another pending issue at the python cgi level this time. I suggest you to stay on a Python 3.6 setup when deploying the v0.6 branch.

web.py is currently being replaced by Flask and the migration should be finished in a few days. v0.7 will probably be released next month and be able to run flawlessly on recent Python versions.

**Comment by erelsgl** [comment]
OK, then I will wait for v0.7 and Flask.

**Comment by anthonygego** [comment]
I'll close this as the Flask migration is done. A warning concerning the python version has been backported in the docs.

**Comment by erelsgl** [comment]
Is Flask already mentioned in the docs? Since I do not see any change here: https://docs.inginious.org/en/latest/install_doc/installation.html

**Comment by anthonygego** [comment]
It also relies on the WSGI interface, therefore there is no change in the installation procedure, this is transparent to the typical user.
