### ISSUE TITLE
Error "403 Forbidden" when accessing the "static" folder

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#635]
After a fresh installation on Ubuntu 20.04 + Apache2, when I try to access "http://ip-address/static/" or "curl http://localhost/static/" I get an error: "You don't have permission to access this resource."

**Comment by anthonygego** [comment]
This is specific to your setup and the best advice I can give you is to look at your Apache logs. Maybe a path is not the same anymore in your fresh install.

**Comment by erelsgl** [comment]
I looked at the "static" folder and saw that all files belong to user "root" and group "staff". Is this the right behavior? Shouldn't they belong to the Apache2 user/group (called `www-data` on Ubuntu)?

**Comment by anthonygego** [comment]
Maybe. This depends if they have read access set to other users. 

Your Apache logs should be explicit: if this is a file permission issue, the error log will mention "Permission denied" when opening the file. If there is nothing such, this is probably Apache that refuses to serve the file. In that case, according to the LogLevel set, you may have some insight on what's going wrong in the access logs.

**Comment by erelsgl** [comment]
Here is the error I get:

```
[Sun Feb 21 14:53:05.310803 2021] [autoindex:error] [pid 708:tid 140532151273216] [client 127.0.0.1:47026] AH01276: Cannot serve directory /usr/local/lib/python3.8/dist-packages/inginious/frontend/static/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
```

Indeed, the error is gone when I add an `index.html` file to the `static` folder. But I guess this file should not be there.

**Comment by anthonygego** [comment]
If it searches for a directoy index, that's probably because you try to access the directory without specifying a file. This is a normal behaviour: directory listing is often disallowed by default. If you can't, however, access the actual files by typing the complete path, you have an issue.

**Comment by erelsgl** [comment]
Indeed, I can access files from the static folder. So it was probably not a bug.
