### ISSUE TITLE
Documentation suggestion: add a part on testing the installation

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#636]
I suggest to add to the intallation documentation, a page such as the following:

Checking the installation
-------------------------

To check that the various parts of the system are correctly installed, you can use the following commands.

1. Check that docker is active:
```
    systemctl status docker
```

2. Check that mongo db is active:
```
    systemctl status mongodb
```

Both of them should be in status "active (running)".

3. Check that wsgi is installed:
```
    apache2 -M 
```

The last line should be "wsgi_module (shared)".

4. Check access to a file in the `static` folder, e.g.:
```
    curl http://localhost/static/icons/wb.svg
```

5. Check access to the `courselist` folder:
```
    curl http://localhost/courselist
```

**Comment by anthonygego** [comment]
Closed by https://github.com/UCL-INGI/INGInious/commit/960ff14453e130cef0e2a8388697d026c3821a79
