### ISSUE TITLE
"Exception: No configuration file found"

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#640]
I re-installed INGInious on a fresh server, this time Ubuntu 18.04 with Python 3.6.9. When I do `curl http://localhost` I get this error in Apache error.log:

```
[Wed Feb 24 15:25:25.203708 2021] [wsgi:error] [pid 31248:tid 140078647064320] [client 127.0.0.1:59012] mod_wsgi (pid=31248): Target WSGI script '/usr/local/bin/inginious-webapp' cannot be loaded as Python module.
[Wed Feb 24 15:25:25.203800 2021] [wsgi:error] [pid 31248:tid 140078647064320] [client 127.0.0.1:59012] mod_wsgi (pid=31248): Exception occurred processing WSGI script '/usr/local/bin/inginious-webapp'.
[Wed Feb 24 15:25:25.204105 2021] [wsgi:error] [pid 31248:tid 140078647064320] [client 127.0.0.1:59012] Traceback (most recent call last):
[Wed Feb 24 15:25:25.204151 2021] [wsgi:error] [pid 31248:tid 140078647064320] [client 127.0.0.1:59012]   File "/usr/local/bin/inginious-webapp", line 56, in <module>
[Wed Feb 24 15:25:25.204205 2021] [wsgi:error] [pid 31248:tid 140078647064320] [client 127.0.0.1:59012]     raise Exception("No configuration file found")
[Wed Feb 24 15:25:25.204262 2021] [wsgi:error] [pid 31248:tid 140078647064320] [client 127.0.0.1:59012] Exception: No configuration file found
```

It seems the main error is the last one "No configuration file found". However, I did put my configuration file in `/var/www/inginious` since I ran all the installation inside that folder:

```
total 60
drwxr-xr-x  4 www-data www-data  4096 Feb 24 15:28 .
drwxr-xr-x  4 root     root      4096 Feb 24 15:05 ..
-rw-rw-r--  1 root     root     34520 Feb 23 15:32 LICENSE
-rw-rw-r--  1 root     root       131 Feb 23 15:32 README.rst
drwxr-xr-x  2 root     root      4096 Feb 24 15:28 agent_tmp
-rw-r--r--  1 root     root       187 Feb 24 15:18 configuration.yaml
drwxrwxr-x 15 root     root      4096 Feb 24 15:13 tutorial
```

Here is the configuration file:
```
backend: local
backup_directory: .
local-config: {}
mongo_opt:
    database: INGInious
    host: localhost
plugins: []
superadmins:
- superadmin
tasks_directory: .
use_minified_js: false
```

Maybe I did something wrong during the installation. I suggest to add a specialized installation guide for INGInious + Apache, since the order of steps is somewhat different.

**Comment by anthonygego** [comment]
Did you set the `INGINIOUS_WEBAPP_CONFIG` environment variable as mentioned ? In systemd-based Linux distributions, the services have their own environment variables scopes. On RHEL-based systems, the Apache service has an environment file located in `/etc/sysconfig/httpd`. Refer to the appropriate documentation and look for something similar. 

The environment file is usually specified with the entry `EnvironmentFile` in the systemd services files:

      [root@host] # systemctl status httpd
      ● httpd.service - The Apache HTTP Server
      Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
      <truncated...>

      [root@host] # cat /usr/lib/systemd/system/httpd.service | grep Environment
      EnvironmentFile=/etc/sysconfig/httpd

**Comment by erelsgl** [comment]
I use Apache2, the environment variables are usually put in /etc/apache2/envvars. I added to the end of this file, the following lines:

```
export INGINIOUS_WEBAPP_CONFIG="/var/www/inginious/configuration.yaml"
export INGINIOUS_WEBAPP_HOST="0.0.0.0"
export INGINIOUS_WEBAPP_PORT="80"
```

**Comment by anthonygego** [comment]
> In systemd-based Linux distributions, the services have their own environment variables scopes.

    root@aa9edb4bd60d:/# cat /etc/lsb-release 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=18.04
    DISTRIB_CODENAME=bionic
    DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
    root@aa9edb4bd60d:/# cat /lib/systemd/system/apache2.service | grep Environment
    Environment=APACHE_STARTED_BY_SYSTEMD=true
    
The `envvars` file is a shell script that is used for `apache2ctl` and probably old distributions relying on sysvinit. You must either add the variables in the service file or add an `EnvironmentFile` entry to the service file as this is done in RHEL systems. But do not specify the `envvars` file as it is not in the same format.

**Comment by erelsgl** [comment]
Yes, this is exactly what I see in `cat /lib/systemd/system/apache2.service | grep Environment` - I do not have an `EnvironmentFile` entry at all. Also, I do not have an `/etc/sysconfig` folder at all.
