### ISSUE TITLE
LTI Open edX "Couldn't validate LTI request"

### ISSUE THREAD

**Issue by tritran-cotai** [UCL-INGI/INGInious#641]
Hi team,

I use Inginious V0.6 
I have no problem when running Inginious webapp and can perfectly operate. 
But I got this error when I am trying to integrate Inginious with Open edX via LTI.
Following images shows my key and secrect use to integrate.
![Screen Shot 2021-02-26 at 11 29 38](https://user-images.githubusercontent.com/73578630/109255118-ec638400-7825-11eb-9d99-11f78c4acff5.png)
<img width="1047" alt="Screen Shot 2021-02-26 at 11 30 23" src="https://user-images.githubusercontent.com/73578630/109255163-069d6200-7826-11eb-8e4f-06ca494117fa.png">

When I launch Inginious from edX course I got this error
`Couldn't validate LTI request`.
I changed the log configuration to "DEBUG" in configuration.yaml and get this log from console

```
inginious_1  | 2021-02-26 03:51:14,256 - inginious.webapp.pages - DEBUG - _parse_lti_data:<Storage {'lis_result_sourcedid': 'course-v1%3AedX%2BDemoX%2BDemo_Course:-b8fd3a8afd5741c9b1426df902512f08:student', 'lti_message_type': 'basic-lti-launch-request', 'context_label': 'edX', 'roles': 'Instructor', 'oauth_timestamp': '1614310691', 'lti_version': 'LTI-1p0', 'resource_link_id': '-b8fd3a8afd5741c9b1426df902512f08', 'oauth_consumer_key': 'test123456', 'context_id': 'course-v1:edX+DemoX+Demo_Course', 'user_id': 'student', 'oauth_callback': 'about:blank', 'context_title': 'Demonstration Course', 'custom_component_display_name': 'Inginious', 'oauth_signature_method': 'HMAC-SHA1', 'launch_presentation_return_url': '', 'oauth_signature': '/qH8BLqXwVI+WAl6m4/BRaShgXI=', 'oauth_nonce': '109201160130678726541614310691', 'oauth_version': '1.0', 'lis_outcome_service_url': '/preview/xblock/block-v1:edX+DemoX+Demo_Course+type@lti_consumer+block@b8fd3a8afd5741c9b1426df902512f08/handler/outcome_service_handler'}>
inginious_1  | 2021-02-26 03:51:14,259 - inginious.webapp.pages - INFO - Couldn't validate LTI request
inginious_1  | 2021-02-26 03:51:14,261 - inginious.webapp.requests - INFO - 34.126.68.54:60970 - "HTTP/1.1 POST /lti/demo/hello" - 403 Forbidden
```

From this information I have no idea how to process to fix the error.
Could you please help me take a look to see what should I do to fix this problem?

Thank you so much.

**Comment by anthonygego** [comment]
Your configuration seems OK and the LTI request too. The LTI requests expire in time and thus in addition to the secret a timestamp is also checked. You should probably check if both communicating servers have the same time. They can obviously use be on different timezones, but their universal time should be approximately the same.

**Comment by tritran-cotai** [comment]
> Your configuration seems OK and the LTI request too. The LTI requests expire in time and thus in addition to the secret a timestamp is also checked. You should probably check if both communicating servers have the same time. They can obviously be on different timezones, but their universal time should be approximately the same.

Thank @anthonygego. I checked them already. Their timezone are both UTC on host machine (Google Compute Engine). edX and inginious both run on docker container and they are both UTC. 

Is there any other information I should investigate ?

**Comment by anthonygego** [comment]
There are also some checks that are made on the request headers, it would be interesting to check the webserver configuration. In case you have configured a proxy, all the headers may not be forwarded to the app.

If you want to debug further, you can still try to add some prints in https://github.com/UCL-INGI/INGInious/blob/v0.6/inginious/frontend/lti_request_validator.py
The two ``validate...`` functions must return True, and ``get_client_secret`` should return your secret.

The rest of the logic is outside INGInious and located in the lti package : https://github.com/pylti/lti/blob/master/src/lti/tool_provider.py#L50

**Comment by tritran-cotai** [comment]
> There are also some checks that are made on the request headers, it would be interesting to check the webserver configuration. In case you have configured a proxy, all the headers may not be forwarded to the app.
> 
> If you want to debug further, you can still try to add some prints in https://github.com/UCL-INGI/INGInious/blob/v0.6/inginious/frontend/lti_request_validator.py
> The two `validate...` functions must return True, and `get_client_secret` should return your secret.
> 
> The rest of the logic is outside INGInious and located in the lti package : https://github.com/pylti/lti/blob/master/src/lti/tool_provider.py#L50

Thanks for your suggestion. I check these functions but they all return valid result. 
I have put some code for debug oauthlib in /inginious/frontend/pages/lti.py
```python
import web
...
import logging
import oauthlib
import sys
oauthlib.set_debug(True)
log = logging.getLogger('oauthlib')
log.addHandler(logging.StreamHandler(sys.stdout))
log.setLevel(logging.DEBUG)
...
```
After check the console I found these debug log
```
inginious_1  | 2021-03-01 10:29:32,120 - inginious.webapp.pages - DEBUG - _parse_lti_data:<Storage {'lti_version': 'LTI-1p0', 'oauth_version': '1.0', 'context_label': 'edX', 'context_id': 'course-v1:edX+DemoX+Demo_Course', 'oauth_timestamp': '1614594571', 'launch_presentation_return_url': '', 'lti_message_type': 'basic-lti-launch-request', 'oauth_signature_method': 'HMAC-SHA1', 'oauth_callback': 'about:blank', 'roles': 'Instructor', 'user_id': 'student', 'lis_outcome_service_url': '/preview/xblock/block-v1:edX+DemoX+Demo_Course+type@lti_consumer+block@b8fd3a8afd5741c9b1426df902512f08/handler/outcome_service_handler', 'resource_link_id': '-b8fd3a8afd5741c9b1426df902512f08', 'oauth_consumer_key': 'test123456', 'oauth_nonce': '33677257996638751431614594571', 'oauth_signature': 'AOgUgBsKQVySQuLD4fUf8neIfDM=', 'lis_result_sourcedid': 'course-v1%3AedX%2BDemoX%2BDemo_Course:-b8fd3a8afd5741c9b1426df902512f08:student', 'custom_component_display_name': 'Inginious', 'context_title': 'Demonstration Course'}>
inginious_1  | Verify HMAC-SHA1 failed: signature base string: POST&http%3A%2F%2Fcode-grader.cot.ai%2Flti%2Fdemo%2Fhello&context_id%3Dcourse-v1%253AedX%252BDemoX%252BDemo_Course%26context_label%3DedX%26context_title%3DDemonstration%2520Course%26custom_component_display_name%3DInginious%26launch_presentation_return_url%3D%26lis_outcome_service_url%3D%252Fpreview%252Fxblock%252Fblock-v1%253AedX%252BDemoX%252BDemo_Course%252Btype%2540lti_consumer%252Bblock%2540b8fd3a8afd5741c9b1426df902512f08%252Fhandler%252Foutcome_service_handler%26lis_result_sourcedid%3Dcourse-v1%25253AedX%25252BDemoX%25252BDemo_Course%253A-b8fd3a8afd5741c9b1426df902512f08%253Astudent%26lti_message_type%3Dbasic-lti-launch-request%26lti_version%3DLTI-1p0%26oauth_callback%3Dabout%253Ablank%26oauth_consumer_key%3Dtest123456%26oauth_nonce%3D33677257996638751431614594571%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1614594571%26oauth_version%3D1.0%26resource_link_id%3D-b8fd3a8afd5741c9b1426df902512f08%26roles%3DInstructor%26user_id%3Dstudent
inginious_1  | [Failure] request verification failed.
inginious_1  | 2021-03-01 10:29:32,128 - inginious.webapp.pages - INFO - Couldn't validate LTI request
inginious_1  | Valid client: True
inginious_1  | Valid signature: False
```
It seem that something wrong when building base string for signature. 
If you have any experience on this, it will be very helpful for me to investigate and fix this issue ?

**Comment by anthonygego** [comment]
There's a chance the issue comes from the openedX setup then as the signature comes with the initial post request. You can also use the saLTIre tools to test and try to isolate the issue:
- Your INGInious setup : https://saltire.lti.app/platform. Just set the message url (launch url), key and secret in the "security model" tab, click on save in the top bar, and then connect.
- Your openedX setup: https://saltire.lti.app/tool

**Comment by tritran-cotai** [comment]
> There's a chance the issue comes from the openedX setup then as the signature comes with the initial post request. You can also use the saLTIre tools to test and try to isolate the issue:
> 
> * Your INGInious setup : https://saltire.lti.app/platform. Just set the message url (launch url), key and secret in the "security model" tab, click on save in the top bar, and then connect.
> * Your openedX setup: https://saltire.lti.app/tool

Thanks for you advice.
I tried to simulate request to my inginious server with minimum data for request but still got the same issue.
![Screen Shot 2021-03-03 at 10 29 29](https://user-images.githubusercontent.com/73578630/109748524-97e84c00-7c0b-11eb-990d-e56a4907c1cc.png)
![Screen Shot 2021-03-03 at 10 33 15](https://user-images.githubusercontent.com/73578630/109748740-f1e91180-7c0b-11eb-99c6-8ee3b6817986.png)

```
inginious_1  | 2021-03-03 03:18:27,391 - inginious.webapp.pages - DEBUG - _parse_lti_data:<Storage {'oauth_callback': 'about:blank', 'oauth_signature_method': 'HMAC-SHA1', 'oauth_nonce': 'b7ff07cf20582fd94deb269737234402', 'oauth_timestamp': '1614741469', 'oauth_consumer_key': 'test123456', 'oauth_version': '1.0', 'oauth_signature': 'Df0+7e7ULnd/xELdA7tuqWREznk='}>
inginious_1  | Verify HMAC-SHA1 failed: signature base string: POST&http%3A%2F%2Fcode-grader.cot.ai%2Flti%2Fdemo%2Fhello&lti_message_type%3Dbasic-lti-launch-request%26lti_version%3DLTI-1.0%26oauth_callback%3Dabout%253Ablank%26oauth_consumer_key%3Dtest123456%26oauth_nonce%3Db7ff07cf20582fd94deb269737234402%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1614741469%26oauth_version%3D1.0
inginious_1  | [Failure] request verification failed.
inginious_1  | Valid client: True
inginious_1  | Valid signature: False
```

Could it be any issue in my INGInious setup ?

**Comment by anthonygego** [comment]
Double-check if your secret is correctly formatted in your ``course.yaml`` file. We already had issues where there was a trailing `\n` saved even if there are supposed to be trimmed.

If this looks good, I think my only remaining suggestion is to have a hard look at why the signature is not validated, some pointers:
- https://github.com/oauthlib/oauthlib/blob/b69fa53fd836dc559aa7fcd78ce075bcbe361629/oauthlib/oauth1/rfc5849/endpoints/base.py#L230
- https://github.com/oauthlib/oauthlib/blob/b69fa53fd836dc559aa7fcd78ce075bcbe361629/oauthlib/oauth1/rfc5849/signature.py#L422

**Comment by tritran-cotai** [comment]
> Double-check if your secret is correctly formatted in your `course.yaml` file. We already had issues where there was a trailing `\n` saved even if there are supposed to be trimmed.
> 
> If this looks good, I think my only remaining suggestion is to have a hard look at why the signature is not validated, some pointers:
> 
> * https://github.com/oauthlib/oauthlib/blob/b69fa53fd836dc559aa7fcd78ce075bcbe361629/oauthlib/oauth1/rfc5849/endpoints/base.py#L230
> * https://github.com/oauthlib/oauthlib/blob/b69fa53fd836dc559aa7fcd78ce075bcbe361629/oauthlib/oauth1/rfc5849/signature.py#L422

Thanks @anthonygego .
Could you please help me take a look to see whether this configuration is correct ?

<img width="1076" alt="Screen Shot 2021-03-04 at 09 05 22" src="https://user-images.githubusercontent.com/73578630/109899750-e7d91880-7cc8-11eb-9458-20a3293d3b6f.png">

**Comment by anthonygego** [comment]
This seems good.

> > There's a chance the issue comes from the openedX setup then as the signature comes with the initial post request. You can also use the saLTIre tools to test and try to isolate the issue:
> > 
> > * Your INGInious setup : https://saltire.lti.app/platform. Just set the message url (launch url), key and secret in the "security model" tab, click on save in the top bar, and then connect.
> > * Your openedX setup: https://saltire.lti.app/tool
> 
> Thanks for you advice.
> I tried to simulate request to my INGInious server with minimum data for request but still got the same issue.
> ![Screen Shot 2021-03-03 at 10 29 29](https://user-images.githubusercontent.com/73578630/109748524-97e84c00-7c0b-11eb-990d-e56a4907c1cc.png)
> ![Screen Shot 2021-03-03 at 10 33 15](https://user-images.githubusercontent.com/73578630/109748740-f1e91180-7c0b-11eb-99c6-8ee3b6817986.png)
> 
> ```
> inginious_1  | 2021-03-03 03:18:27,391 - inginious.webapp.pages - DEBUG - _parse_lti_data:<Storage {'oauth_callback': 'about:blank', 'oauth_signature_method': 'HMAC-SHA1', 'oauth_nonce': 'b7ff07cf20582fd94deb269737234402', 'oauth_timestamp': '1614741469', 'oauth_consumer_key': 'test123456', 'oauth_version': '1.0', 'oauth_signature': 'Df0+7e7ULnd/xELdA7tuqWREznk='}>
> inginious_1  | Verify HMAC-SHA1 failed: signature base string: POST&http%3A%2F%2Fcode-grader.cot.ai%2Flti%2Fdemo%2Fhello&lti_message_type%3Dbasic-lti-launch-request%26lti_version%3DLTI-1.0%26oauth_callback%3Dabout%253Ablank%26oauth_consumer_key%3Dtest123456%26oauth_nonce%3Db7ff07cf20582fd94deb269737234402%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1614741469%26oauth_version%3D1.0
> inginious_1  | [Failure] request verification failed.
> inginious_1  | Valid client: True
> inginious_1  | Valid signature: False
> ```
> 
> Could it be any issue in my INGInious setup ?

Actually, based on this, I see something that might be an issue. You're using https to serve the website, but if you look at the signature base string in your log it contains only ``http``. Therefore I guess the two platforms do not compute the signature based on the same URL and the verification fails. I think it is worth checking if there is no webserver misconfiguration that would result in bad redirects, or a proxy issue. If configured well, INGInious should detect the ``https`` scheme correctly.

**Comment by tritran-cotai** [comment]
> This seems good.
> 
> > > There's a chance the issue comes from the openedX setup then as the signature comes with the initial post request. You can also use the saLTIre tools to test and try to isolate the issue:
> > > 
> > > * Your INGInious setup : https://saltire.lti.app/platform. Just set the message url (launch url), key and secret in the "security model" tab, click on save in the top bar, and then connect.
> > > * Your openedX setup: https://saltire.lti.app/tool
> > 
> > 
> > Thanks for you advice.
> > I tried to simulate request to my INGInious server with minimum data for request but still got the same issue.
> > ![Screen Shot 2021-03-03 at 10 29 29](https://user-images.githubusercontent.com/73578630/109748524-97e84c00-7c0b-11eb-990d-e56a4907c1cc.png)
> > ![Screen Shot 2021-03-03 at 10 33 15](https://user-images.githubusercontent.com/73578630/109748740-f1e91180-7c0b-11eb-99c6-8ee3b6817986.png)
> > ```
> > inginious_1  | 2021-03-03 03:18:27,391 - inginious.webapp.pages - DEBUG - _parse_lti_data:<Storage {'oauth_callback': 'about:blank', 'oauth_signature_method': 'HMAC-SHA1', 'oauth_nonce': 'b7ff07cf20582fd94deb269737234402', 'oauth_timestamp': '1614741469', 'oauth_consumer_key': 'test123456', 'oauth_version': '1.0', 'oauth_signature': 'Df0+7e7ULnd/xELdA7tuqWREznk='}>
> > inginious_1  | Verify HMAC-SHA1 failed: signature base string: POST&http%3A%2F%2Fcode-grader.cot.ai%2Flti%2Fdemo%2Fhello&lti_message_type%3Dbasic-lti-launch-request%26lti_version%3DLTI-1.0%26oauth_callback%3Dabout%253Ablank%26oauth_consumer_key%3Dtest123456%26oauth_nonce%3Db7ff07cf20582fd94deb269737234402%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1614741469%26oauth_version%3D1.0
> > inginious_1  | [Failure] request verification failed.
> > inginious_1  | Valid client: True
> > inginious_1  | Valid signature: False
> > ```
> > 
> > 
> > Could it be any issue in my INGInious setup ?
> 
> Actually, based on this, I see something that might be an issue. You're using https to serve the website, but if you look at the signature base string in your log it contains only `http`. Therefore I guess the two platforms do not compute the signature based on the same URL and the verification fails. I think it is worth checking if there is no webserver misconfiguration that would result in bad redirects, or a proxy issue. If configured well, INGInious should detect the `https` scheme correctly.

@anthonygego you are right !!! This is my setup problem and problem solved.
Thank you very much for your dedicated support.
