### ISSUE TITLE
Failed to create the course

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#643]
I logged in as a superadmin, entered "demo" and clicked "Create new course". I got the following error:

![image](https://user-images.githubusercontent.com/1462215/109396630-2f634b80-793b-11eb-8b1b-2cd8f16f5aca.png)

**Comment by anthonygego** [comment]
Check if the folder permissions are good. As you're running it through Apache the folder should belong to the Apache user, otherwise it won't be able to create new folders/files.

**Comment by erelsgl** [comment]
Here is my inginious folder:

```
drwxr-xr-x  4 www-data www-data  4096 Feb 24 15:28 .
drwxr-xr-x  4 root     root      4096 Feb 24 15:05 ..
-rw-rw-r--  1 www-data www-data 34520 Feb 23 15:32 LICENSE
-rw-rw-r--  1 www-data www-data   131 Feb 23 15:32 README.rst
drwxr-xr-x  2 www-data www-data  4096 Feb 24 15:28 agent_tmp
-rw-r--r--  1 www-data www-data   187 Feb 24 15:18 configuration.yaml
drwxrwxr-x 15 www-data www-data  4096 Feb 24 15:13 tutorial
```

**Comment by anthonygego** [comment]
I recommend you to keep have a specific folder as the tasks folder and not to share it with the main one, as every subfolder is treated as a potential course. That doesn't explain the issue though. You may want to add a ``raise`` instruction here : https://github.com/UCL-INGI/INGInious/blob/v0.6/inginious/frontend/pages/mycourses.py#L45 to trigger the exception and get the stacktrace.

The $common folder can be used to share common files accross the different tasks. I however do not remember exactly if this feature was already present in v0.6

**Comment by anthonygego** [comment]
Ensure that you specified an absolute path for the folders in the configuration file, otherwise the webserver will use its user homepath as the current working directory.

**Comment by erelsgl** [comment]
You mean to replace the "." that is created by default, with something like "/var/www/inginious"?
