### ISSUE TITLE
Something went wrong while sending you activation email

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#645]
After a fresh installation, I try to register with username, password and email. I get the following error.

![image](https://user-images.githubusercontent.com/1462215/109411904-d08aea00-79ad-11eb-8428-fde245e06262.png)

There is no new error in the `error.log`.

**Comment by anthonygego** [comment]
Indeed, there is not much logging. Typically this fails when your smtp settings are not good.

**Comment by erelsgl** [comment]
I do not know much about smtp. Is it possible to just disable the email feature, and let anyone register with username & password?

**Comment by anthonygego** [comment]
This is really insecure as 1) this removes all protection against bots, 2) the email is used as primary key for external bindings, leading to the possibility of accounts hijacking. I strongly recommend to setup an external auth method (ldap, saml,...) and disable email registration in the case.

However if your use case is really limited and in a closed network, you can remove this line : https://github.com/UCL-INGI/INGInious/blob/v0.6/inginious/frontend/pages/register.py#L102 as well as the emailing blocks. But this may really break things.

**Comment by erelsgl** [comment]
> Indeed, there is not much logging. Typically this fails when your smtp settings are not good.

I did not install smtp at all (it is a fresh server). What exactly should I install so that INGInious can send mail?

**Comment by anthonygego** [comment]
You do not especially need to install anything. In most cases, you simply need to set the SMTP credentials of an existing mailing service (your institutional one, or one given by a cloud computing service provider) in the configuration file as yo you would do for your mail client.

**Comment by erelsgl** [comment]
OK, thanks. I suggest to add this step to the `inginious-install` script. Right now it is only explained in the "Configuration Reference", and there, too, the top of page says: "The best way to configure INGInious is to use inginious-install. See Configuring INGInious."

**Comment by erelsgl** [comment]
I now added this at the end of my configuration.yaml:

```
smtp:
    sendername: 'INGInious At Ariel <inginious.at.ariel@gmail.com>'
    host: 'smtp.gmail.com'
    port: 587
    username: 'inginious.at.ariel@gmail.com'
    password: '[randomly-generated-password]'
    starttls: True
```

Then I did `systemctl reload apache2` and retried to register, and I got the same error: " Something went wrong while sending you activation email. Please contact the administrator. "

**Comment by anthonygego** [comment]
You can simply put a  ``raise`` before this line  https://github.com/UCL-INGI/INGInious/blob/v0.6/inginious/frontend/pages/register.py#L114

That will trigger the exception with the complete trace and smtplib error message.

**Comment by erelsgl** [comment]
I found out that Gmail blocked the SMTP connection attempt, claiming that the connecting application (i.e., INGInious) has "low security level". What can I do?

**Comment by erelsgl** [comment]
P.S. this raises a couple of other issues that may be worth fixing:

* When there is a problem with the email, the username is still registered, so I cannot register again with the same username, but also cannot login with this username. 
* It would be good to add a meaningful log message in case of problems with sending email.

**Comment by anthonygego** [comment]
> A much better solution would be to somehow upgrade INGInious to "high security level app", but I do not know how to do this.

The emailing library is not the same anymore in master due to the migration from web.py to Flask. I know that the web.py implementation is quite lightweight. I will test this with a gmail account asap.

 I'll take time to fix these issues in the same time, there are still relevant to the master branch.

**Comment by anthonygego** [comment]
I investigated the issue. Google does not allow password authentication by defaut anymore on SMTP. Instead, they rely on OAuth with an SMTP extension named ``XOAUTH2``. It seems Microsoft followed. However:

- This is not a standardized feature yet for SMTP and therefore not present in common implementations.
- OAuth is mainly designed for use with personal accounts and not service accounts. This makes sense for personal mailboxes such as GMail, Outlook/Hotmail...
- OAuth requires a complex scheme to setup, this is not just a password anymore, that is not quite adapted for this usage:
   - You need to setup an developper account with an application, and let it in developer mode as it is not meant to be used by other users in this case.
   - It then requires to generate an access token via a browser-based authentication. This tokens expires in time, and the only chance not to have to re-authenticate via the browser again is to get a refresh token, which can be used indefinetely to generate a new access token. Such a refresh token is not given by default by OAuth services. It's the case for Google though.

OAuth is already used in INGInious for external authentications, and the OAuth particularities almost always require a similar but distinct implement depending on the service. While this makes sense for an external email client like Outlook, Thunderbird, Evolution,... to implement such a feature, this is less the case for a service account.

Therefore, as this is typically not a good idea to use personal mailboxes to send service messages, I think the most appropriate reaction now is to update the documentation to mention those possible issues when using personal mailboxes, until a more common and generic procedure emerges.

**Comment by erelsgl** [comment]
Instead of relying on third parties, why not just install a local SMTP server during the inginious-install?

**Comment by GuillaumeDerval** [comment]
SMTP servers are typically very hard to install correctly. Mostly because if you do not do very very specific and complex things all your mails end in spam boxes.

**Comment by erelsgl** [comment]
‎This can happen also with gmail accounts. A simple solution is to just tell the registering user "please check your SPAM folder"; this is good to do in any case.

**Comment by fillipefeitosa** [comment]
Hello there. 

I understand this is a very old topic. But the smtp problem is quite frustrating actually, because it leads the deploy useless, since it does not allow anyone to actually create an account and login to enroll into courses. 

I could not find any easy instructions on documentations, and I subscribe to the comments upwards:


> OK, thanks. I suggest to add this step to the `inginious-install` script. Right now it is only explained in the "Configuration Reference", and there, too, the top of page says: "The best way to configure INGInious is to use inginious-install."

The first thing one would do after a fresh install (i am using docker-compose), is to make a task and test if the task runs. Email configuration and user creation could come prematurely on documentation, since it is vital for the web app to run. By the way, there could be also an explanation on main documentation. 

If help is needed to organize this I could provide. But I need to make my instance run first though.
