### ISSUE TITLE
Suggestion: add an installation guide for Ubuntu + Apache2

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#647]
After many trials and failures, I finally managed to install INGInious on Ubuntu with Apache 2. I wrote a guide for this. It may be useful for others.

[inginious-install-ubuntu-apache.zip](https://github.com/UCL-INGI/INGInious/files/6060393/inginious-install-ubuntu-apache.zip)

**Comment by Drumor** [comment]
Could you please put that in a pull request?
