### ISSUE TITLE
Cannot make container temp directory

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#650]
I finally managed to register and submit the first task in the tutorial course. I received the attached error: "An internal error occurred. Please retry later. If the error persists, send an email to the course administrator. [Submission #603fbc2bc2d6716e5474e521]"

"Cannot make container temp directory."

There is nothing in the error.log.

I verified that my /var/www/inginious folder and all its subfolders are owned by the Apache user www-data.

![Screenshot from 2021-03-03 18-42-03](https://user-images.githubusercontent.com/1462215/109840316-ac026c80-7c50-11eb-8685-cba3cd373623.png)

**Comment by anthonygego** [comment]
As you're running with the local backend option, apache is the user who runs everything. Check that you have a

    local-config:
        tmp_dir: /var/www/inginious/agent_tmp
 
 entry with an absolute path in your ``configuration.yaml`` file. Otherwise you'll have the same issue than with the other folders.

**Comment by erelsgl** [comment]
This solved the problem. Thanks
