### ISSUE TITLE
Batch operations - page not found

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#652]
In task 2 of the tutorial course, there is a link to "The Batch operations feature", at `/admin/tutorial/batch`. Clicking this link leads to an "Error 404". I am not sure if this is a bug in the tutorial or in the system.

**Comment by GuillaumeDerval** [comment]
Batch operations have been removed from INGInious quite some time ago ;-)
I think @darkyne removed it from the tutorial course some days ago.

**Comment by darkyne** [comment]
Indeed the tutorials were  updated few days ago. Old features were removed and new ones added. But this new version of the tutorials is not compatible with the current v0.6 you are using. 
Inginious should probably release version 0.7 shortly and thus the new tutorials will not have the issues you are pointing out ;)
