### ISSUE TITLE
Task creation

### ISSUE THREAD

**Issue by cmunyabarenzi** [UCL-INGI/INGInious#66]
It has again become possible to submit answers to tasks and get a feedback. However, whenever I try to create a new task, this pop-up error message still appears in the upper right corner. Re-loading the page or re-authenticating does not solve it. Any ideas on what could be the problem?
![screenshot from 2015-07-21 12 49 45](https://cloud.githubusercontent.com/assets/4334642/8799431/47ac5a32-2faa-11e5-967c-ae542a814e16.png)

**Comment by anthonygego** [comment]
It should be fixed :-)

**Comment by cmunyabarenzi** [comment]
Yes, thanks.
