### ISSUE TITLE
Nothing appears in "Grading Environment" when selecting Standard container (Docker) 

### ISSUE THREAD

**Issue by hdlozanorojas** [UCL-INGI/INGInious#673]
I have a problem, INGInious is already installed but when creating a task, nothing appears in the "grading environment" space and I don't know how to solve this, since I have already tried some things and nothing solves this problem anyway. 

![Evidencia](https://user-images.githubusercontent.com/70306718/119279576-37592180-bbf2-11eb-8459-7879f6cb7a3f.png)

I appreciate the help you can give me in this case.

**Comment by anthonygego** [comment]
Did you build the containers ? What does ``docker images`` return ? In case of error you should have something in the INGInious logs.

**Comment by hdlozanorojas** [comment]
Yes, I built the containers, however I don't know if that remains in a folder or if it has to be created somewhere, because it seems that the agent does not execute the necessary containers from the images and they do not appear in the "grading environment" space. The documentation doesn't mention anything about it either. I attach the image showing that the docker images are built. 

![image](https://user-images.githubusercontent.com/70306718/119603120-3242d080-bdb2-11eb-9781-45b720bf66bb.png)

Thanks for the help, I really would like to use the tool but it has not been possible.

**Comment by anthonygego** [comment]
Is there anything printed concerning the containers in the agent logs ?

According to your screenshot, you are running a 23 days old version of master and the agent version was updated in e628a908a79a863bae09dd6de8c2591ac0c81d9a, which may coincide with the oldest build dates in your machine.

You can apply this filter to be sure they do not need to be rebuilt:

    docker images --filter "label=org.inginious.grading.agent_version=3"

**Comment by hdlozanorojas** [comment]
When verifying they were not actually built in version 3 of the agent, I built one of those so that it will remain in version 3 as shown in the lower attachment. However, the "grading environment" still does not appear. 

![image](https://user-images.githubusercontent.com/70306718/119699845-31dd2080-be18-11eb-9171-dafde26a9bb5.png)

On the other way, when reviewing the apache logs, some errors are observed, which could perhaps be those that do not allow the docker to run for the "grading environment". I would like to know if there is any solution for this problem. 

![image](https://user-images.githubusercontent.com/70306718/119699946-4d482b80-be18-11eb-8310-7486d2e1b715.png)

**Comment by anthonygego** [comment]
OK, the running user cannot open the Docker socket. You need to add the ``httpd`` user to the ``docker`` group : ``usermod -aG docker httpd``. This manipulation may vary according to your distribution as users can have different names.

**Comment by vvandenschrieck** [comment]
I'm having similar issue since my last system update.  My containers are tagged with agent version 2, and running "inginious-containers-update" does not change anything.  What's the procedure to built the containers to version 3?

**Comment by darkyne** [comment]
Indeed, the script "inginious-containers-update" had some issues and the docker hub images were old.
These issues were corected and the containers updating process should be easier in a very near future.
