### ISSUE TITLE
get_input("@random") alternative in the various script language

### ISSUE THREAD

**Issue by akemery** [UCL-INGI/INGInious#687]
Hi,
I want to know the variants of inginious API for for different scripting languages such as bash, python3 and so on.  

For example to get the random value 
   1- In RST it is ```input["@random"]```
   2- In python it is ```get_input("@random)```
  3- In bash I don't know

I have the same question for feedback-result, feedback-tag, feedback-msg, and so on.

**Comment by anthonygego** [comment]
You can find examples for both languages here : https://docs.inginious.org/en/v0.7/teacher_doc/run_file.html#feedback-commands.
Most of the shell scripts also have a "--help" argument that shows the syntax to use.

"@random" has to be considered as a typical problem id.

**Comment by akemery** [comment]
Cool, Thanks
