### ISSUE TITLE
ssh_student: ssh sesssion freeze after inactivity

### ISSUE THREAD

**Issue by darkyne** [UCL-INGI/INGInious#698]
it was brought up to me that in case of long exercises using ssh_student, the ssh session may freeze because of inactivity (if the student takes too long without giving any input for example).

I suppose it may be possible to configure the inactivity timeout in the ssh_config file but not sure if this is really an issue or should stay like that.

**Comment by GuillaumeDerval** [comment]
See the `ClientAliveInterval` and `TCPKeepAlive` parameters in the `sshd_config` file (in the container)

https://linux.die.net/man/5/sshd_config

**Comment by anthonygego** [comment]
In all cases, if the session freezes but the container does not stop immediately after it is clearly an unwanted behaviour.

**Comment by darkyne** [comment]
Yep, thanks.
Just not sure if I should put something very long by default or make it a parameter the teacher would set up.

I'll do more tests to see the actual behaviour but I would say, if it freezes because of inactivity, the container should stop immediately (and return to the run script).

**Comment by darkyne** [comment]
Ok I have tried to meet this scenario but actually my ssh_session never freezes even if I don't interact with the terminal for several minutes (it just ends up timing out when the task timeout is reached).

This issue was actually related to a user whose terminal freezes after 2-3 minutes of inactivity, being related to a ssh session or not, it's simply a "feature" of his terminal... So it is finaly not related to ssh_student after all.

Actually, ssh_student returns (and the run script continues) when it detects there is no ssh session active.
So for this user specific case, when his terminal freezed, he can open a new terminal and connect with ssh to continue the exercise (and close the freezed one) and finally when the 2nd terminal is closed, INGInious detects there is no ssh session active and the run script continues.

He just did that and it worked fine.

So I suppose we can just close this :)
