### ISSUE TITLE
English typos in frontend

### ISSUE THREAD

**Issue by augustindelecluse** [UCL-INGI/INGInious#729]
Some typos are present within the frontend of Inginious:

- From the main page of a course, "Groups management" should be "Group management".
- In the same way, from the administration page of a course, "Users management" should be "User management".

Correcting this should be a matter of changing the strings in the templates and the corresponding translations. Another impacted file is the installation.rst within the admin documentation.

**Comment by Drumor** [comment]
Feel free to make a PR with those modification :+1:
