### ISSUE TITLE
Requirement of multiprocessing package

### ISSUE THREAD

**Issue by FRidh** [UCL-INGI/INGInious#73]
INGInious works exclusively on Python 2.7 according to the documentation. 
`setup.py` lists that multiprocessing is required, however, multiprocessing is part of the standard library of Python 2.7. Is there any particular reason for this dependency?

**Comment by anthonygego** [comment]
I don't think there's a particular version dependency and that the list was autogenerated. It thus can be removed. @GuillaumeDerval could you confirm this ?

**Comment by GuillaumeDerval** [comment]
Yep. It was autogenerated by pip freeze, and can probably be removed.
(a good question would be: why was it listed by pip?)
