### ISSUE TITLE
[filesystems/local] Expected behavior for move()

### ISSUE THREAD

**Issue by nrybowski** [UCL-INGI/INGInious#754]
The `move()` signature says that the destination must not exist:

https://github.com/UCL-INGI/INGInious/blob/8d49326d6e73ce887519dff518735d709c099685/inginious/common/filesystems/provider.py#L101-L102

However, the LocalFSProvider does not enforce this requirement and will override an existing destination:

https://github.com/UCL-INGI/INGInious/blob/8d49326d6e73ce887519dff518735d709c099685/inginious/common/filesystems/local.py#L110-L115

Which one is the expected behavior?

**Comment by anthonygego** [comment]
We can keep the Unix behaviour (the one implemented in shutil : https://docs.python.org/3/library/shutil.html#shutil.move) and replace our docstring by the appropriate behaviour description.
