### ISSUE TITLE
Submission Submission grades infinitely - docker Grading Container cant start - Error: exec user process caused: no such file or directory

### ISSUE THREAD

**Issue by lorenzPowedale** [UCL-INGI/INGInious#757]
exec user process caused: no such file or directory
docker logs
<img width="552" alt="Bildschirmfoto 2021-12-14 um 09 04 14" src="https://user-images.githubusercontent.com/87168687/145957447-c81de919-302d-40ce-9354-73d8a27cc8ca.png">

INGInious webapp
<img width="1440" alt="grafik" src="https://user-images.githubusercontent.com/87168687/145957709-ca3d1aab-0fc1-4b85-9eaf-0a54997e9fc1.png">

/var/log/apache2/error.log
<img width="1440" alt="grafik" src="https://user-images.githubusercontent.com/87168687/145957894-448ab781-32e5-4128-80d3-0aea3640084e.png">

**Comment by anthonygego** [comment]
Hello,

There's a chance you don't have the containers matching your INGInious version installed.

Which version did you install ? It looks like this is an old one given the layout and footer dates. If this is a new setup, I recommend you to install at least v0.7 (the docs should be updated for, please indicate the docs you followed if this is not the case). The setup script should help you build the appropriate containers.

If you're simply updating an older one, you may have to update the containers manually by building ``ingi/inginious-c-base`` and ``ingi/inginious-c-default`` from the ``base-containers`` folder in the repo, with this kind of command:

    [user@host INGInious] $ docker build -t ingi/inginious-c-base base-containers/base/

**Comment by lorenzPowedale** [comment]
> Hello,
> 
> There's a chance you don't have the containers matching your INGInious version installed.
> 
> Which version did you install ? It looks like this is an old one given the layout and footer dates. If this is a new setup, I recommend you to install at least v0.7 (the docs should be updated for, please indicate the docs you followed if this is not the case). The setup script should help you build the appropriate containers.
> 
> If you're simply updating an older one, you may have to update the containers manually by building `ingi/inginious-c-base` and `ingi/inginious-c-default` from the `base-containers` folder in the repo, with this kind of command:
> 
> ```
> [user@host INGInious] $ docker build -t ingi/inginious-c-base base-containers/base/
> ```

Im working on an INGInious Docker container for school right now. My teacher has been using 0.5 for a while now, so I am unable to upgrade without talking it over with him.

Is there a way to manually install 0.5 containers for INGInious?

P.S. thanks for the quick reply

**Comment by lorenzPowedale** [comment]
So I now installed the Containers again and it shows me the 0.5 Tag.
<img width="1440" alt="grafik" src="https://user-images.githubusercontent.com/87168687/145968146-a6b28d09-0f02-4774-be10-dafbba56d4c1.png">

When I start a default INGInious grading container manually I get the same error. Could it be possible, that the "run" file doesn't get sent to the Container.

Maybe an error with msgpack?

**Comment by anthonygego** [comment]
It could be linked to msgpack because we experienced breaking changes since v1.0 , indeed. I recommend you to try to rebuild the containers from `ìnginious-0.5`` branch of the repository : https://github.com/UCL-INGI/INGInious/tree/inginious-0.5/base-containers.

You can check if the msgpack version in the container matches the one on the host.

**Comment by anthonygego** [comment]
At least the container runs and exits "normally" because this error message is produced inside. Are you able to launch the task in debug mode (button next to submit) ? If yes, check if there actually is a /task folder that have been created, and if your task files are located inside.

**Comment by lorenzPowedale** [comment]
Could it be possible that the INGInious Docker Container checks for the file on the Docker host?

**If yes, check if there actually is a /task folder that has been created, and if your task files are located inside.:**

No I cant connect to the ssh connection. But while I wait for the establishment of a ssh connection I can /bin/bash into the docker container. This gave me some time to search for the run file.

<img width="1385" alt="grafik" src="https://user-images.githubusercontent.com/87168687/146619750-c8c4e21e-6a9c-4cf9-8f63-618f4b21ead5.png">

This shows that the task folder is completely empty.

On the Docker the run file is present though
<img width="1385" alt="grafik" src="https://user-images.githubusercontent.com/87168687/146619910-22fb5311-e7b5-4af4-8d74-4d41b5a29124.png">

How does the communication from INGInious to the Grading Docker work. What "libraries" do you use? How can I give the Docker this run file

Thanks in advance,
Lorenz

**Comment by anthonygego** [comment]
zmq and msgpack are the library used.

Not quite sure to understand your setup. Are you running the frontend inside a container ? If yes, the frontend (or, at least, the docker agent if run separately) and the docker daemon host should find the course files at the same path, because the agent tells the Docker API to mount the task folder in read-only mode. Those files are not transmitted between the components.

As the container runs, you should check if there is no mounting error, in the docker logs probably.

**Comment by lorenzPowedale** [comment]
I fixed it:
container is available at:https://hub.docker.com/r/validhtlrennweg/inginious-dockerized
