### ISSUE TITLE
INGInious MongoDB Redundancy

### ISSUE THREAD

**Issue by lorenzPowedale** [UCL-INGI/INGInious#762]
Is there any way to have two redundant MongoDB Databases  and use them with INGInious?

**Comment by anthonygego** [comment]
Yes, MongoDB comes with replication (and also sharding) features. For basic replication, you need three nodes (an additional arbiter is required).

Once configured, you'll have to change the mongo URL to connect to add the replicaSet name. This way, the mongo client will be able to redirect the request in case one of the node goes down.

You'll find all the information in the mongodb docs :
- https://docs.mongodb.com/manual/replication/
- https://docs.mongodb.com/manual/tutorial/deploy-replica-set/

**Comment by lorenzPowedale** [comment]
> 

Thanks :D

**Comment by lorenzPowedale** [comment]
Thanks :)

**Comment by lorenzPowedale** [comment]
Wirh replication is it possible that both servers can write or is it a Master-Slave type system?

**Comment by anthonygego** [comment]
Replication is only master-slave, I think. You always write to the primary, but you can configure the system to allow the secondary for reading operations.

You should probably be able to distribute the write requests using sharding. I haven't have to rely on sharding yet so I recommend you to refer to the mongodb docs if you're interested. It'll be the most accurate information.

**Comment by lorenzPowedale** [comment]
> 

the problem with sharding is that there is no failover. when one server dies I lose half of the data

Thanks anyway, I will hopefully find a solution :)

**Comment by anthonygego** [comment]
You can combine sharding and replication. Sharding with no redundancy would have no (or very little) interest in production environments.
