### ISSUE TITLE
Fixed naming of groups

### ISSUE THREAD

**Issue by pschaus** [UCL-INGI/INGInious#80]
I would like to be able to name explicitly the groups.
If I remove a group, the other naming should be unchanged.

**Comment by anthonygego** [comment]
The groups model was thought to be flexible while remaining lightweight (it was re-written several times). Your two issues makes me think you may want to use the classroom concept, even if your groups aren't classrooms in reality. In fact, the classroom concept in INGInious is associated to a physical entity while the group is a virtual one (this will be clarified in documentation).

I think you may want to create several classrooms of students containing only one submission group with all classroom members inside. This will enables the 2 *distinct* facilities giving you statistics, easy downloads while keeping submissions accounted for all users.

This might seem crazy but it is not. Maybe we didn't find the right words to express the corresponding functionalities. This was especially designed to enable simultaneously the use of groups like many others LMS (Moodle, Claroline...) and the specific group structure of UCL LFSAB1401 course (in summary we splitted the broad concept of "groups" in two, for this special purpose).

**Comment by pschaus** [comment]
Hi Anthony,

I followed your advice and I created 28 different classrooms instead of my
28 groups in a single classroom.
Problem 1:  I don't see how to assign students in my class rooms. In every
classrooms I have 0 students (they are all in the default classroom).
Question 1: I would like to let the students register themselves in each
classroom and the only group in this classroom. Is that possible?
Cheers

Pierre

**Comment by anthonygego** [comment]
- There's a + sign next to the "Ungrouped users" title which you can click to add students in classrooms.

- Currently this feature is not available but it can be implemented soon.

**Comment by pschaus** [comment]
Ok got it Anthony.
suggestion:  have the list of unregistered students on top in every classroom and a drag and drop next to each student would allow me to change its classroom. This would be the "classroom view".
Then inside a classroom view, I cannot import students but only assign them to groups.
I have 140 students to assign to classrooms manually, it is a bit boring with the current gui ;-)

**Comment by anthonygego** [comment]
The newly added teams allow managing a unique layer of submission groups more easily.
http://inginious.readthedocs.io/en/latest/teacher_doc/course_admin.html#classrooms-and-teams
