### ISSUE TITLE
Remote SSH manager is not closing properly

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#82]
For an unknown reason, the remote ssh manager(s) tend to not close properly when an INGInious frontend shut down.

It seems that the socket is still open after the shutdown.

**Comment by GuillaumeDerval** [comment]
@oliviertilmans Should fix your problem; Tell me if it's not the case.

**Comment by oliviertilmans** [comment]
Reinstalled the package with the proper dependencies, still no luck
Stuck around
https://github.com/UCL-INGI/INGInious/blob/master/inginious/utils/remote_debugger/inginious-remote-debug#L65
I never get to the
retval = retval.strip()

**Comment by GuillaumeDerval** [comment]
It seems that it is in fact two bugs: the one that is now solved in INGInious, and a misconfiguration of the lighttpd.

I put on my sysadmin hat and look at the problem ;-)

**Comment by oliviertilmans** [comment]
It does work now.
