### ISSUE TITLE
[inginious-agent-docker] Fail to kill the container : Exception in handle_kill_job

### ISSUE THREAD

**Issue by jyounggo** [UCL-INGI/INGInious#824]
Inginious-agent-docker failed to kill the container for some reason intermittently, and the timeout watcher registered for the container is running infinitely.
When this issue happened, the student can only see the page showing "INGInious is currently grading your answers(almost done)" and can't cancel the task.

May 28 21:40:21 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:21,348 - inginious.agent.docker - DEBUG - 1278175148
May 28 21:40:22 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:22,350 - inginious.agent.docker - DEBUG - 0
May 28 21:40:22 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:22,351 - inginious.agent.docker - DEBUG - 1278175148
May 28 21:40:23 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:23,561 - inginious.agent.docker - DEBUG - Container output ended with an IncompleteReadError; It was probably killed.
May 28 21:40:23 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:23,562 - inginious.agent.docker - WARNING - Container 42dcc832ef60aa426759428c2ffa8321725da42ca4f9bd99722fc25b0dba7059 has not given any result
May 28 21:40:23 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:23,562 - inginious.agent.docker - DEBUG - 0
May 28 21:40:23 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:23,562 - inginious.agent.docker - DEBUG - 0
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:24,151 - inginious.agent.docker - ERROR - Exception in handle_kill_job
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]: Traceback (most recent call last):
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/docker/api/client.py", line 268, in _raise_for_status
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     response.raise_for_status()
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     raise HTTPError(http_error_msg, response=self)
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]: requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/42dcc832ef60aa426759428c2ffa8321725da42ca4f9bd99722fc25b0dba7059/kill
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]: During handling of the above exception, another exception occurred:
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]: Traceback (most recent call last):
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/inginious/agent/docker_agent/__init__.py", line 641, in kill_job
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     await self._docker.kill_container(self._container_for_job[message.job_id])
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/inginious/common/asyncio_utils.py", line 67, in _inner
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     return await self._loop.run_in_executor(self._executor, f)
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     result = self.fn(*self.args, **self.kwargs)
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/inginious/agent/docker_agent/_docker_interface.py", line 204, in kill_container
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     self._docker.containers.get(container_id).kill(signal)
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/docker/models/containers.py", line 276, in kill
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     return self.client.api.kill(self.id, signal=signal)
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     return f(self, resource_id, *args, **kwargs)
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/docker/api/container.py", line 798, in kill
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     self._raise_for_status(res)
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/docker/api/client.py", line 270, in _raise_for_status
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     raise create_api_error_from_http_exception(e)
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:   File "/home/inginious/.local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]:     raise cls(e, response=response, explanation=explanation)
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]: docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/42dcc832ef60aa426759428c2ffa8321725da42ca4f9bd99722fc25b0dba7059/kill: Conflict ("Cannot kill container: 42dcc832ef60aa426759428c2ffa8321725da42ca4f9bd99722fc25b0dba7059: Container 42dcc832ef60aa426759428c2ffa8321725da42ca4f9bd99722fc25b0dba7059 is not running")
May 28 21:40:24 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:24,562 - inginious.agent.docker - DEBUG - 0
May 28 21:40:25 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:25,562 - inginious.agent.docker - DEBUG - 0
May 28 21:40:25 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:25,562 - inginious.agent.docker - DEBUG - 0
May 28 21:40:26 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:40:26,066 - inginious.agent.docker - ERROR - Exception in handle_kill_job

The above error is repeated 3~4 times and the watcher is displaying "0" every second.

...
ay 28 21:41:15 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:15,579 - inginious.agent.docker - DEBUG - 0
May 28 21:41:15 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:15,579 - inginious.agent.docker - DEBUG - 0
May 28 21:41:16 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:16,579 - inginious.agent.docker - DEBUG - 0
May 28 21:41:16 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:16,580 - inginious.agent.docker - DEBUG - 0
May 28 21:41:17 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:17,580 - inginious.agent.docker - DEBUG - 0
May 28 21:41:17 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:17,580 - inginious.agent.docker - DEBUG - 0
May 28 21:41:18 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:18,580 - inginious.agent.docker - DEBUG - 0
May 28 21:41:18 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:18,580 - inginious.agent.docker - DEBUG - 0
May 28 21:41:19 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:19,580 - inginious.agent.docker - DEBUG - 0
May 28 21:41:19 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:19,580 - inginious.agent.docker - DEBUG - 0
May 28 21:41:20 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:20,581 - inginious.agent.docker - DEBUG - 0
May 28 21:41:20 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:20,581 - inginious.agent.docker - DEBUG - 0
May 28 21:41:21 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:21,581 - inginious.agent.docker - DEBUG - 0
May 28 21:41:21 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:21,581 - inginious.agent.docker - DEBUG - 0
May 28 21:41:22 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:22,581 - inginious.agent.docker - DEBUG - 0
May 28 21:41:22 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:22,581 - inginious.agent.docker - DEBUG - 0
May 28 21:41:23 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:23,581 - inginious.agent.docker - DEBUG - 0
May 28 21:41:23 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:23,582 - inginious.agent.docker - DEBUG - 0
May 28 21:41:24 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:24,582 - inginious.agent.docker - DEBUG - 0
May 28 21:41:24 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:24,582 - inginious.agent.docker - DEBUG - 0
May 28 21:41:25 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:25,582 - inginious.agent.docker - DEBUG - 0
May 28 21:41:25 inginious-agent-01 inginious-agent-docker[1238]: 2022-05-28 21:41:25,582 - inginious.agent.docker - DEBUG - 0

**Comment by anthonygego** [comment]
Does this always happens or only when using run_student or ssh shell ?
Is SELinux enabled ?
What's your Docker version ? Do you have any additional useful information in the Docker logs ?

**Comment by jyounggo** [comment]
1.
This issue happens intermittently while using run_student for the grading(no ssh shell and no SELinux enabled)

2.
Following is the output of "docker info"
---
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 36
  Running: 0
  Paused: 0
  Stopped: 36
 Images: 4
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-180-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.41GiB
 Name: inginious-agent-01
 ID: NMM3:SOXZ:PYT5:LEUK:7MUN:J7RY:TNMZ:ID2J:B3NK:Z47J:75WS:VJ5L
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

--

3.
Regarding docker lock, I can't find much useful information but I can see the warning/info diplays whenever grading container is running.


Jun 07 21:07:11 inginious-agent-01 dockerd[1359]: time="2022-06-08T03:07:11.025459436Z" level=warning msg="Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap."
Jun 07 21:07:11 inginious-agent-01 dockerd[1359]: time="2022-06-08T03:07:11.666371317Z" level=info msg="ignoring event" container=ea6cfd82673fa610cb2fb2b8da68c27510fb74b52ac5deec7e58e51ff246243c module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 07 21:07:11 inginious-agent-01 dockerd[1359]: time="2022-06-08T03:07:11.864377829Z" level=info msg="ignoring event" container=2d194d68e939ccf18afb024f43851a9d9093ac2dfa6856618eda2f590a034d12 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"

**Comment by anthonygego** [comment]
Looks good. The cgroups warning in the logs should be false negative as the docker info command identifies it as version 1. I see you're running Ubuntu so maybe you can try deactivate AppArmor.

Getting a zero value from the watcher should mean that the container has not even started as it returns the cpu usage of the container. If you can catch the issue while it is running, it could be interesting to see if a new container was actually launched (docker ps should display running command run_student_intern), and if it has launched, to see if it has any logs (docker logs xxx)

Which INGInious version are you running ? I can't find easily in which commit the ``kill_job`` function is at line 641 in ``docker_agent/__init__.py`` file.
