### ISSUE TITLE
setup.py hard-depends on deprecated package

### ISSUE THREAD

**Issue by oliviertilmans** [UCL-INGI/INGInious#84]
Currently forces you to have
docker-py==1.3.0.dev0,
which is not available on pypi anymore (was it ever the case?)

Seems to work 'ok' here with docker-py 1.3, anything blocking from changing it to
docker-py>=1.3.0
?

**Comment by GuillaumeDerval** [comment]
This package was never available on Pypi, it is a custom version of docker-py available on my account. We are waiting for them to implement some features that I temporarily hardcoded.

Maybe I should take time to redo this properly and make a PR...

In the meantime, you can just use the --process-dependency-links option of pip when you install INGInious. It should automatically download the custom docker-py.

**Comment by oliviertilmans** [comment]
I did not check the dependency link, thought pip would use them by default if mentioned, my bad.
