### ISSUE TITLE
[frontend] Impossible to properly download the binary file of a submission

### ISSUE THREAD

**Issue by precondition** [UCL-INGI/INGInious#868]
**Describe the bug**

When selecting a submission, INGInious adds a button that lets the user download the submitted file through URL query parameters `?submissionid=XXX&questionid=YYY` (from what I gathered).

This correctly opens the file-save dialog window when downloading a source code file like .py or .java.

However, in the case of binary file format such as .xslx, it opens a new tab filled with garbled text like "PK8�5U_rels/.rels���N�0��{�*�5�@���LH�!4�$n���ă�". Copy-pasting the content or saving the page with Ctrl+S don't work — I'm guessing because unprintable binary characters are missing.

**INGInious installation details**
- Version:  v.0.8.2
- Containers version (if applicable) [e.g. the git hash]

**To Reproduce**
1. Go to https://inginious.info.ucl.ac.be/course/pae/SINF2MS
2. Submit a .xlsx file
3. Click on the submission
4. Click on the "Save submission file" blue button

**Expected behavior**
The save-file dialog box should open, offering you where to save the binary file.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Browser : Firefox
 - Version : 104

**Additional context**

**Comment by AlexandreDoneux** [comment]
It appears the problem has been resolved prior to @thremilien's PR. Closing this issue.
