### ISSUE TITLE
LTI/Moodle integration does not appear to be working anymore in UCLouvain ecosystem

### ISSUE THREAD

**Issue by tbarbette** [UCL-INGI/INGInious#869]
**Describe the bug**
Moodle gives me : "Accès interdit Error while parsing the LTI request"
Note also the documentation proposes to create LTI keys with underscores in the names "_" which is forbidden.

Probably UCLouvain updated to the latest moodle version and the LTI version is now 1.3. I see reference to 1.1 support in the doc.

**INGInious installation details**
- Version: UCLouvain current for both
- Containers version (if applicable) [e.g. the git hash]

**To Reproduce**
1. Tick "Enable LTI mode"
2. Set URL to https://moodle.uclouvain.be/course/view.php?id=5788
3. Add some alphanumerical LTI keys (I don't think it's used on Moodle)
4. Tick "send notes" or not (I tried both)

On Moodle:
5. Add an external activity
6. Set up URL to https://inginious.info.ucl.ac.be/lti/LINFO2241/exercise_id (and follow other steps from the documentation)

**Expected behavior**
I see the exercise on Moodle, and I can submit from Moodle :)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser [e.g. chrome, safari] : Chrome

**Additional context**
Generally, as UCLouvain seems to set up on using Moodle after the COVID crisis, it would be great to increase the integration with Moodle. From the current documentation, it's a bit unclear what to expect or what is currently supported. But being able to submit a project from Moodle, using Moodle groups would be interesting in my case.

**Comment by anthonygego** [comment]
While I can't get the deployed Moodle version, LTI 1.1+ is still supported in latest version of Moodle (LTI1.3 being still quite a new standard), but is called "Legacy LTI". Both the local instances have been used together this semester by other students, hitherto without issues.

> Add some alphanumerical LTI keys (I don't think it's used on Moodle)

You have to specify them as INGInious does not support no authentication. Please refer to the Moodle docs here: https://docs.moodle.org/400/en/External_tool_settings

If you still experience issues, please send us the time at which the request are made via the appropriate internal support channels or add me as course administrator. 

I'll close this issue and open a new one to prepare migration to the new standard.
