### ISSUE TITLE
[frontend/installer] prefixes mess when building containers with dependencies

### ISSUE THREAD

**Issue by anthonygego** [UCL-INGI/INGInious#871]
**Describe the bug**
When building the containers using the installer scripts, containers with dependencies that are not base will fail to build, because their parent container is added to the list with a prefix.

Container without prefix is added to a ``todo`` dictionary when asked to the user, and with prefix when parsed automatically. However, the logic then check the todo lists using both nomenclatures.

https://github.com/UCL-INGI/INGInious/blob/64d71e3a9339a538b29b535f472d1fe301897e78/inginious/frontend/installer.py#L465

The whole code needs to be cleaned.

**INGInious installation details**
- Version: 0.7+

**To Reproduce**
1. Launch inginious-install up to container build and answer yes
2. Select a container with dependencies (for install pyjavacpp)
3. It will fail to build searching for non-existing folder

**Expected behavior**
Parsing works and builds the appropriate container if necessary

**Comment by nrybowski** [comment]
See also https://github.com/UCL-INGI/INGInious/issues/833.
