### ISSUE TITLE
Make INGInious friendly for networking tasks

### ISSUE THREAD

**Issue by oliviertilmans** [UCL-INGI/INGInious#89]
- Add /etc/hosts to the mount namespace (so that we can simulate custom domain names by adding them to that file)
- Assign a globally scoped IPv6 address to the container when it is supposed to have network access instead of only an IPv4 one

**Comment by GuillaumeDerval** [comment]
Point (1) is solved by 17cc092db9fd176e676761225ac268f71103067f

Point (2) is not solvable in INGInious directly, it depends on the local configuration of the Docker daemon instance used by INGInious. :-)
