### ISSUE TITLE
[frontend/course administration] Add a way to hide all tasks from a section / hide a section

### ISSUE THREAD

**Issue by AurelienBuchet** [UCL-INGI/INGInious#914]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to hide a section to the students or quickly hide all tasks within a given section.

**Describe the solution you'd like**
Add an option on the sections similar to the closed by default to make all tasks and/or the section itself hidden/visible.

**Comment by nrybowski** [comment]
Similar to https://github.com/UCL-INGI/INGInious/issues/433
