### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by gonzeD** [UCL-INGI/INGInious#938]
Hello, 

Is the mailing list still active? I tried registering using the link in the readme (https://sympa-2.sipr.ucl.ac.be/sympa/info/inginious), but I think the website does not list it anymore. If this is indeed the case, maybe the link in the readme should be removed?

**Comment by anthonygego** [comment]
Hi,

Yes the mailing list is still active. It seems there was visibility issues since the last platform update. Thank you for reporting this. This should be fixed now.
