### ISSUE TITLE
Frontend crashes in new installations due to Flask compatibility

### ISSUE THREAD

**Issue by RazNitzanCyber** [UCL-INGI/INGInious#942]
A new release of the Flask package (2.3.0, see https://flask.palletsprojects.com/en/2.3.x/changes/) removed the property _**session_cookie_name**,_ which is still in use by INGInious frontend (inginious/frontend/flask/mongo_sessions.py). This is causing a frontend crash in every new installation of INGInious (from scratch), which installs the new Flask library as one of its dependencies.

**INGInious installation details**
- Version: 0.8.6 and earlier 0.8.x releases

**Comment by anthonygego** [comment]
Thanks for reporting this ! A fix will be pushed very soon.

**Comment by RazNitzanCyber** [comment]
Thanks for the quick fix. Everything is working fine now 😃
