### ISSUE TITLE
Could you update document for osx? (docker-machine)

### ISSUE THREAD

**Issue by kwangkim** [UCL-INGI/INGInious#95]
I think docker does not support boot2docker any more.
https://docs.docker.com/mac/step_one/

I tried install inginious on my mac, it did not works well.

For example, DOCKER_HOST is now `tcp://192.168.99.100:2376`

Could you update the installation manual?

**Comment by GuillaumeDerval** [comment]
I will wipe my local installation of Docker and update the tutorial next week.

**Comment by GuillaumeDerval** [comment]
Sorry for the delay; I added a new backend specifically for docker-machine and I updated the inginious-install tool; do running it solve your problem?

(do not forget to use the dev version of INGInious, not the one in the pip repos)

**Comment by GuillaumeDerval** [comment]
Closing this issue since there is no response; feel free to update if the problem still exists.
