### ISSUE TITLE
Most LDAPs are case-insensitive

### ISSUE THREAD

**Issue by GuillaumeDerval** [UCL-INGI/INGInious#99]
A config option to do strtolower on the usernames when using LDAP is then needed.

**Comment by layus** [comment]
Why do you need to strtolower if the LDAP really is case-insensitive? Do you mean that the ldap is case-sensitive and uses ony lowercase?

**Comment by GuillaumeDerval** [comment]
Because MongoDB is case-sensitive, and then it considers that "something" and "someThing" are two different users.

**Comment by layus** [comment]
Makes sense... We all have to live with DOS inheritance :-).
